### ISSUE TITLE
GitHub-API rate limit is exceeded.

### ISSUE THREAD

**Issue by marek22k** [Tobi823/ffupdater#100]
I have the problem in two devices. Both uses a VPN.

Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.GithubRateLimitExceededException: GitHub-API rate limit  @is exceeded.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:56)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResource(ApiConsumer.kt:23)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invokeSuspend(ApiConsumer.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/jamal2362/Styx/releases/latest
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:50)
	... 8 more
```
Device information:
| key | value |
| --- | --- |
| version name | 74.5.3 |
| version code | 90 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | FP3 |
| brand | Fairphone |
| device | FP3 |
| manufacturer | Fairphone |
| model | FP3 |
| product | FP3 |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1639969449000 |

**Comment by LeSnake04** [comment]
Same for me:
Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.GithubRateLimitExceededException: GitHub-API rate limit is exceeded.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:56)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResource(ApiConsumer.kt:23)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invokeSuspend(ApiConsumer.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/jamal2362/Styx/releases/latest
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:50)
	... 8 more
```
Device information:
| key | value |
| --- | --- |
| version name | 74.5.3 |
| version code | 90 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | universal8890 |
| brand | samsung |
| device | heroltexx |
| manufacturer | samsung |
| model | SM-G930F |
| product | heroltexx |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1633455712000 |

**Comment by Tobi823** [comment]
Bad news - the Styx browser is not longer maintained. You should switch to a different browser. See #101 

The GitHub repository of Styx is deleted / is set to private - and this causes the "GitHub-API rate limit is exceeded" error.
