### ISSUE TITLE
download fails and opening cache folder throws android.os.FileUriExposedException 

### ISSUE THREAD

**Issue by schumischumi** [Tobi823/ffupdater#107]
Hi,
I try to install ungoogled chromium with ffupdater. 
the download and checksum works fine but while I try to install it I get a the message "the operation has failed in a general way. the system will always try to provide an exact reason for the failure, but in some rare cases this can be provided." (translated german2english). 
clearing the cache does not work in if I try to access the cache folder the app throws the android.os.FileUriExposedException:

```
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:2141)
at android.net.Uri.checkFileUriExposed(Uri.java:2391)
at android.content.Intent.prepareToLeaveProcess(Intent.java:11186)
at android.content.Intent.prepareToLeaveProcess(Intent.java:11156)
at android.content.Intent.prepareToLeaveProcess(Intent.java:11135)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1724)
at android.app.Activity.startActivityForResult(Activity.java:5429)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
at android.app.Activity.startActivityForResult(Activity.java:5379)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
at android.app.Activity.startActivity(Activity.java:5781)
at android.app.Activity.startActivity(Activity.java:5734)
at de.marmaro.krt.ffupdater.InstallActivity.onCreate$lambda-2(InstallActivity.kt:110)
at de.marmaro.krt.ffupdater.InstallActivity.$r8$lambda$BQh98yaOt6ypRybEju-aqqwu53Q(Unknown Source:0)
at de.marmaro.krt.ffupdater.InstallActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:7509)
at android.view.View.performClickInternal(View.java:7486)
at android.view.View.access$3600(View.java:841)
at android.view.View$PerformClick.run(View.java:28709)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
UPDATE: If I navigate with the file browser directly to the download folder and install the apk manually from there, it works fine.

Device information:
| key | value |
| --- | --- |
| version name | 75.0.0 |
| version code | 91 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | sdm710 |
| brand | Xiaomi |
| device | grus |
| manufacturer | Xiaomi |
| model | Mi 9 SE |
| product | grus_eea |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1621974223000 |

PS: thanks for the great app and no hurry!

**Comment by Tobi823** [comment]
I will take a closer look at the problem after the university exams.

You have two problems:

- Installation failed with an **unspecific** error:
  -  (here is the Android documentation https://developer.android.com/reference/android/content/pm/PackageInstaller#STATUS_FAILURE). This means that the failed installation is caused by something else and **NOT** by:
     - STATUS_FAILURE_ABORTED: The operation failed because it was actively aborted. 
     - STATUS_FAILURE_BLOCKED: The operation failed because it was blocked.
     - STATUS_FAILURE_CONFLICT: The operation failed because it conflicts (or is inconsistent with) with another package already installed on the device.
     - STATUS_FAILURE_INCOMPATIBLE: The operation failed because it is fundamentally incompatible with this device. For example, the app may require a hardware feature that doesn\'t exist, it may be missing native code for the ABIs supported by the device, or it requires a newer SDK version, etc.
     - STATUS_FAILURE_INVALID: The operation failed because one or more of the APKs was invalid.
     - STATUS_FAILURE_STORAGE: The operation failed because of storage issues.
   - You are using a Xiaomi smartphone. Can you try disable the "MIUI optimization"? Some users had similar problems and "solved" them by disabling "MIUI optimization". (The first Google search result: https://www.quora.com/How-do-I-enable-disable-MIUI-optimization).
 - Opening the FFUpdater folder from FFUpdater results in an `android.os.FileUriExposedException`:
   - Accessing files and folder across different Android manufacturers and versions is complicated. I guess that FFUpdater must be improved.

**Comment by Tobi823** [comment]
FFUpdater 75.1.0 uses a different (I hope more reliable) method for downloading updates. Maybe it will fix your issue.
