### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Ronsekaon** [Tobi823/ffupdater#112]
Stacktrace:
```
de.marmaro.krt.ffupdater.installer.SessionInstaller$SessionInstallerException: Fail to install app.
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.install(SessionInstaller.kt:57)
	at de.marmaro.krt.ffupdater.InstallActivity$Companion.triggerInstallationProcess(InstallActivity.kt:406)
	at de.marmaro.krt.ffupdater.InstallActivity$State._init_$triggerInstallationProcess(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$State.access$_init_$triggerInstallationProcess(InstallActivity.kt:195)
	at de.marmaro.krt.ffupdater.InstallActivity$State$11.invoke(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$State$11.invoke(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:169)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.io.IOException: Failed to allocate 227167300 because only 45162496 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
	at android.os.Parcel.readParcelable(Parcel.java:2990)
	at android.os.Parcel.createException(Parcel.java:2083)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:469)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:945)
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.installInternal(SessionInstaller.kt:91)
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.install(SessionInstaller.kt:55)
	... 15 more
```
Device information:
| key | value |
| --- | --- |
| version name | 74.5.3 |
| version code | 90 |
| build type | release |
| SDK version | 29 |
| android release | 10 |
| board | exynos9810 |
| brand | samsung |
| device | star2lte |
| manufacturer | samsung |
| model | SM-G965F |
| product | star2ltexx |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1634610803000 |

**Comment by Tobi823** [comment]
It seems that your smartphone does not have enough free space to download+install the app. How much memory do you have free (what does Android report in settings > storage) ?

**Comment by Ronsekaon** [comment]
i will check now. i have got a 500gb sdcard in extenal storage.

**Comment by Tobi823** [comment]
Can you check if version 75.2.0 fixed your issue?
