### ISSUE TITLE
Crash when clearing the downloaded apks

### ISSUE THREAD

**Issue by fabmazz** [Tobi823/ffupdater#118]
Android version: 11

Stacktrace:
```
java.lang.IllegalStateException: External download folder should exists.
	at de.marmaro.krt.ffupdater.ManageStorageActivity.onCreate$lambda-4(ManageStorageActivity.kt:17)
	at de.marmaro.krt.ffupdater.ManageStorageActivity.$r8$lambda$LH3kjUHNlQ56uzQh9z2f-7aMP0M(Unknown Source:0)
	at de.marmaro.krt.ffupdater.ManageStorageActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.0.1 |
| version code | 92 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | universal8890 |
| brand | samsung |
| device | heroltexx |
| manufacturer | samsung |
| model | SM-G930F |
| product | heroltexx |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1641751430000 |

**Comment by Tobi823** [comment]
Should be fixed in version 75.1.0
