### ISSUE TITLE
Brave stable. Issues installing with ffupdater 75.2.0 apk

### ISSUE THREAD

**Issue by PsykoRider** [Tobi823/ffupdater#125]
Stacktrace:
```
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2209)
	at android.net.Uri.checkFileUriExposed(Uri.java:2402)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11421)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11394)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11373)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1742)
	at android.app.Activity.startActivityForResult(Activity.java:5533)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:5486)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5892)
	at android.app.Activity.startActivity(Activity.java:5845)
	at de.marmaro.krt.ffupdater.InstallActivity.onCreate$lambda-2(Unknown Source:59)
	at de.marmaro.krt.ffupdater.InstallActivity.a(Unknown Source:0)
	at de.marmaro.krt.ffupdater.b.onClick(Unknown Source:10)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8283)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.2.0 |
| version code | 95 |
| build type | release |
| SDK version | 31 |
| android release | 12 |
| board | lmi |
| brand | POCO |
| device | lmi |
| manufacturer | Xiaomi |
| model | POCO F2 Pro |
| product | lmi_eea |
| SOC manufacturer | QTI |
| SOC model | SM8250 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1649256271000 |

**Comment by Tobi823** [comment]
did the previous version (for example 75.1.0) work?

When will this error occurs? Before or after the actual file download?

**Comment by PsykoRider** [comment]
1. Yes.
2. After file download.

**Comment by Tobi823** [comment]
I need your help to pinpoint the bug. Can you install this version and report if it works now? (If you installed FFUpdater from F-Droid version, you have to uninstall it first)
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8500608/ffupdater-release.zip)

**Comment by PsykoRider** [comment]
There are still issues with brave.  however with the download and installation of Firefox it works both in this version and in the previous one

**Comment by Tobi823** [comment]
I guess I found the bug. Fix will be available in the next version.
