### ISSUE TITLE
Crash when screen closes

### ISSUE THREAD

**Issue by sprlptr48** [Tobi823/ffupdater#128]
It happened when i left the app open downloading an app, screen got automatically closen and when i opened the screen i saw it crashed.
Here is the log:

Stacktrace:
```
java.net.SocketTimeoutException: timeout
	at o4.o$c.l(:1)
	at o4.o$b.read(:20)
	at l4.c$b.read(Unknown Source:15)
	at t4.s.read(:4)
	at t4.j.read(Unknown Source:7)
	at de.marmaro.krt.ffupdater.download.ProgressResponseBody$trackTransmittedBytes$1.read(Unknown Source:5)
	at t4.s$a.read(:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at t2.e.D(:1)
	at de.marmaro.krt.ffupdater.download.FileDownloader.downloadFileInternal(:5)
	at de.marmaro.krt.ffupdater.download.FileDownloader.access$downloadFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.download.FileDownloader$downloadFileInternal$1.invokeSuspend(Unknown Source:12)
	at o3.a.resumeWith(Unknown Source:8)
	at c4.d0.run(Unknown Source:86)
	at f4.a.y(Unknown Source:0)
	at f4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.2.0 |
| version code | 95 |
| build type | release |
| SDK version | 28 |
| android release | 9 |
| board | universal8895 |
| brand | samsung |
| device | greatlte |
| manufacturer | samsung |
| model | SM-N950F |
| product | greatltexx |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1627023819000 |

**Comment by Tobi823** [comment]
Should be fixed in 75.3.0
