### ISSUE TITLE
Crash during “o4.t: stream was reset: CANCEL”


### ISSUE THREAD

**Issue by Elkiwa** [Tobi823/ffupdater#142]
Stacktrace:
```
o4.t: stream was reset: CANCEL
	at o4.o$b.read(:4)
	at l4.c$b.read(Unknown Source:15)
	at t4.s.read(:4)
	at t4.j.read(Unknown Source:7)
	at de.marmaro.krt.ffupdater.download.ProgressResponseBody$trackTransmittedBytes$1.read(Unknown Source:5)
	at t4.s$a.read(:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at t2.e.D(:1)
	at de.marmaro.krt.ffupdater.download.FileDownloader.downloadFileInternal(:5)
	at de.marmaro.krt.ffupdater.download.FileDownloader.access$downloadFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.download.FileDownloader$downloadFileInternal$1.invokeSuspend(Unknown Source:12)
	at o3.a.resumeWith(Unknown Source:8)
	at c4.d0.run(Unknown Source:86)
	at f4.a.y(Unknown Source:0)
	at f4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.2.1 |
| version code | 96 |
| build type | release |
| SDK version | 32 |
| android release | 12 |
| board | oriole |
| brand | google |
| device | oriole |
| manufacturer | Google |
| model | Pixel 6 |
| product | oriole |
| SOC manufacturer | Google |
| SOC model | Tensor |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1646089444000 |

**Comment by Tobi823** [comment]
should be fixed in the next version
