### ISSUE TITLE
.

### ISSUE THREAD

**Issue by LGX-65535-Dev** [Tobi823/ffupdater#147]
Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.GithubRateLimitExceededException: GitHub-API rate limit is exceeded.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:56)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResource(ApiConsumer.kt:23)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invokeSuspend(ApiConsumer.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/bromite/bromite/releases/latest
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:52)
	... 8 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.0.0 |
| version code | 91 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | Kars |
| brand | KDDI |
| device | NAX |
| manufacturer | SHARP |
| model | SHV44 |
| product | NAX_jp_kdi |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1639682097000 |

**Comment by Tobi823** [comment]
It is already fixed. Upgrade to the latest FFUpdater version 75.4.0
