### ISSUE TITLE
Check for update fails multiple times

### ISSUE THREAD

**Issue by bellpepper8** [Tobi823/ffupdater#152]
This error code appears after manually trying to check for an update for my browsers and also when the app does background update check.

Stacktrace:
```
a3.n: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at a3.h.b(:6)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(:6)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResource(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invokeSuspend(Unknown Source:13)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invoke(Unknown Source:8)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invoke(Unknown Source:4)
	at t2.e.j0(Unknown Source:6)
	at u.d.v0(:4)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consumeNetworkResource(:2)
	at de.marmaro.krt.ffupdater.app.impl.fetch.github.GithubConsumer.requestReleases(Unknown Source:128)
	at de.marmaro.krt.ffupdater.app.impl.fetch.github.GithubConsumer.updateCheck(Unknown Source:74)
	at de.marmaro.krt.ffupdater.app.impl.Brave.updateCheckWithoutCaching(Unknown Source:190)
	at de.marmaro.krt.ffupdater.app.BaseAppWithCachedUpdateCheck.updateCheck(Unknown Source:140)
	at de.marmaro.krt.ffupdater.app.BaseAppWithCachedUpdateCheck.access$updateCheck(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.BaseAppWithCachedUpdateCheck$updateCheckAsync$2$1.invokeSuspend(Unknown Source:30)
	at q3.a.resumeWith(Unknown Source:8)
	at e4.f0.run(Unknown Source:86)
	at h4.a.q(Unknown Source:0)
	at h4.a$a.run(:5)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at h3.a.a(Unknown Source:56)
	at d3.a.a(Unknown Source:18)
	... 19 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.4.0 |
| version code | 98 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | sofia |
| brand | motorola |
| device | sofia |
| manufacturer | motorola |
| model | moto g power |
| product | sofia_retail |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1643616663000 |

**Comment by Tobi823** [comment]
I think that the GitHub rate limit was triggered and FFUpdater failed to detect it. Will be improvedin version 75.4.3.
