### ISSUE TITLE
Error updating Brave Nightly

### ISSUE THREAD

**Issue by pedrojosawczuk** [Tobi823/ffupdater#169]
A notification appeared to update Brave Nightly.
I clicked and this crash screen appeared.
#### I don't know if this error is reproducible.

Stacktrace:
```
java.lang.IllegalStateException: PackageInfo for file '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/com.brave.browser_nightly.apk' is null.
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:47)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:32)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:116)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Timestamp: 2022-05-10T05:55:33.434

```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 32 |
| android release | 12 |
| board | trinket |
| brand | Xiaomi |
| device | ginkgo |
| manufacturer | Xiaomi |
| model | Redmi Note 8 |
| product | ginkgo |
| SOC manufacturer | Qualcomm |
| SOC model | SM6125 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1649960903000 |

**Comment by Tobi823** [comment]
I was not able to reproduce the error. But I add some additional checks to make FFUpdater more resilient against this error.
