### ISSUE TITLE
Crash Updating Iceraven

### ISSUE THREAD

**Issue by locuturus** [Tobi823/ffupdater#172]
Stacktrace:
```
java.lang.IllegalArgumentException: PackageInfo has no signingInfo and no signatures.
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.extractSignature(Unknown Source:164)
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:28)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:32)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:116)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Timestamp: 2022-05-13T21:53:13.582

```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 32 |
| android release | 12 |
| board | sunfish |
| brand | google |
| device | sunfish |
| manufacturer | Google |
| model | Pixel 4a |
| product | sunfish |
| SOC manufacturer | Qualcomm |
| SOC model | SM7150 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1651786763000 |

**Comment by Tobi823** [comment]
I was not able to reproduce the error. But I add some additional checks to make FFUpdater more resilient against this error.
