### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by carbongreat13** [Tobi823/ffupdater#173]
Stacktrace:
```
java.lang.IllegalArgumentException: File '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.mozilla.klar.apk' must exists.
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:87)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:116)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.4.2 |
| version code | 100 |
| build type | release |
| SDK version | 32 |
| android release | 12 |
| board | barbet |
| brand | google |
| device | barbet |
| manufacturer | Google |
| model | Pixel 5a |
| product | barbet |
| SOC manufacturer | Qualcomm |
| SOC model | SM7250 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1645557861000 |

**Comment by Tobi823** [comment]
I was not able to reproduce the error. But I add some additional checks to make FFUpdater more resilient against this error.
