### ISSUE TITLE
FFUpdater crash reporter - android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

### ISSUE THREAD

**Issue by hlovdal** [Tobi823/ffupdater#174]
Stacktrace:

```text
de.marmaro.krt.ffupdater.app.impl.exceptions.NetworkException: Fail to consume 'https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.armeabi-v7a/artifacts/public/logs/chain_of_trust.log'.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend()
	at r3.a.resumeWith()
	at f4.e0.run()
	at i4.a.p()
	at i4.a$a.run(:5)
Caused by: java.net.UnknownHostException: Unable to resolve host "firefox-ci-tc.services.mozilla.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at t2.e.b()
	at o4.d.a(:30)
	at o4.a.intercept(:11)
	at p4.f.b(:3)
	at m4.a.intercept(:22)
	at p4.f.b(:3)
	at p4.a.intercept(:16)
	at p4.f.b(:3)
	at p4.h.intercept(:25)
	at p4.f.b(:3)
	at o4.e.f(:10)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:9)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume()
	... 5 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
	... 20 more
```

Device information:

```text
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 23 |
| android release | 6.0.1 |
| board | flo |
| brand | google |
| device | flo |
| manufacturer | asus |
| model | Nexus 7 |
| product | razor |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1467839953000 |
```

**Comment by Tobi823** [comment]
Did the error looked like this?

![Screenshot_20220608_125343](https://user-images.githubusercontent.com/10066140/172599557-ef45d69a-f567-4a26-ab1b-8d8d8eab60f6.png)

If yes, I can't fix it - it is just a temporary network issue and you have to try it again.

If not, reopen this issue and explain the bug in detail.
