### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by th3me** [Tobi823/ffupdater#178]
Stacktrace:
```
java.lang.IllegalStateException: PackageInfo for file '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.bromite.bromite.apk' is null.
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:47)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:32)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:116)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 32 |
| android release | 12 |
| board | msmnile |
| brand | OnePlus |
| device | OnePlus7T |
| manufacturer | OnePlus |
| model | HD1900 |
| product | OnePlus7T |
| SOC manufacturer | Qualcomm |
| SOC model | SM8150 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1650359101000 |

**Comment by Tobi823** [comment]
I was not able to reproduce the error. But I add some additional checks to make FFUpdater more resilient against this error.
