### ISSUE TITLE
Crash: Socket Timeout Exception

### ISSUE THREAD

**Issue by myuseraccount** [Tobi823/ffupdater#180]
Stacktrace:
```
a3.n: java.net.SocketTimeoutException: timeout
	at a3.h.b(:6)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:21)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:13)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Caused by: java.net.SocketTimeoutException: timeout
	at r4.o$c.l(:1)
	at r4.o$b.read(:20)
	at o4.c$b.read(Unknown Source:15)
	at w4.s.read(:4)
	at w4.s.F(Unknown Source:21)
	at w4.m.read(:2)
	at w4.l.read(:12)
	at w4.s$a.read(:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at h3.a.o(Unknown Source:31)
	at h3.a.b0(Unknown Source:43)
	at h3.a.d0(Unknown Source:87)
	at d3.n$a.a(Unknown Source:51)
	at d3.p.a(Unknown Source:2)
	at d3.b$a.a(:1)
	at d3.m.a(Unknown Source:2)
	at d3.n$a.a(Unknown Source:47)
	at d3.p.a(Unknown Source:2)
	at d3.a.a(Unknown Source:29)
	... 8 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | k6853v1_64_titan |
| brand | samsung |
| device | a32x |
| manufacturer | samsung |
| model | SM-A326U |
| product | a32xsq |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1642415950000 |

**Comment by Tobi823** [comment]
Will be fixed in the next version
