### ISSUE TITLE
Crash: IllegalArgumentException: port out of range:-1

### ISSUE THREAD

**Issue by saintech** [Tobi823/ffupdater#181]
Stacktrace:
```
java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
	at java.security.AccessController.doPrivileged(AccessController.java:43)
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
	at o4.m.a(:3)
	at o4.l.<init>(:5)
	at o4.d.a(:17)
	at o4.a.intercept(:11)
	at p4.f.b(:3)
	at m4.a.intercept(:22)
	at p4.f.b(:3)
	at p4.a.intercept(:16)
	at p4.f.b(:3)
	at p4.h.intercept(:25)
	at p4.f.b(:3)
	at o4.e.f(:10)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:9)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:13)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 29 |
| android release | 10 |
| board | k63v2_64_bsp |
| brand | Gigaset |
| device | GS290 |
| manufacturer | Gigaset |
| model | GS290 |
| product | GS290_EEA |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | dev-keys,dev-release |
| build time | 1608047995000 |

**Comment by Tobi823** [comment]
Will be fixed in the next version
