### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YozGrg** [Tobi823/ffupdater#185]
Stacktrace:
```
de.marmaro.krt.ffupdater.security.FingerprintValidator$UnableCheckApkException: Can't find signatures of the APK file.
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:58)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:121)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at t3.a.resumeWith(Unknown Source:8)
	at g4.d0.run(Unknown Source:94)
	at j4.a$a.run(SourceFile:9)
Caused by: de.marmaro.krt.ffupdater.download.ApkSignatureNotFoundException: PackageInfo has no signingInfo and no signatures.
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.extractSignature(SourceFile:8)
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:45)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:26)
	... 6 more
Timestamp: 2022-06-09T12:32:19.138

```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.1 |
| version code | 103 |
| build type | release |
| SDK version | 29 |
| android release | 10 |
| board | universal8890 |
| brand | samsung |
| device | crownlte |
| manufacturer | samsung |
| model | SM-G965F |
| product | crownltexx |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1616159517000 |

**Comment by Tobi823** [comment]
Maybe I introduced a new logic bug which prevents newer devices to use the old (deprecated) API (for extracting signatures). Can you try version 75.1.2?

**Comment by Tobi823** [comment]
#183 I think the bug is now fixed
