### ISSUE TITLE
Crashes on install

### ISSUE THREAD

**Issue by lucker999** [Tobi823/ffupdater#19]
The app has successfully downloads Firefox Klar, verified checksum, but if i pouch the button Install, it attempted an installation and crashes.

It happens both with FF installed (directly from the link) and if I try to install FF with the FFupdater.

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_PERMISSIONS pkg=com.android.packageinstaller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1836)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1556)
	at android.app.Activity.startActivityForResult(Activity.java:3787)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:3744)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4096)
	at android.app.Activity.startActivity(Activity.java:4026)
	at de.marmaro.krt.ffupdater.InstallActivity.onNewIntent(InstallActivity.java:324)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1234)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1246)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2639)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2651)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2660)
	at android.app.ActivityThread.access$1600(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by Tobi823** [comment]
Was this bug introduced with the latest FFUpdater version?
Can you install and test older FFUpdater versions? (F-Droid allows to downgrade any app)

I can't reproduce this bug with the Android emulator. I need your help to fix it.

**Comment by Tobi823** [comment]
Can you test this version?
[ffupdater-debug.zip](https://github.com/Tobi823/ffupdater/files/5766212/ffupdater-debug.zip)

You should be able to install Firefox Klar (and other apps).
Because this is just a quick hack, FFUpdater will not report the successful app installation.

**Comment by lucker999** [comment]
Thank you for the suggestions.

The previous two versions prior 70 (65.5 & 65&4 I guess) both work a bit better: they allow me to choose an app to install ff with, but in the list there is no "package installer", so it is impossible to install downloaded ff klar. At least it doesn't crash if I try to update manually installed ff klar. If I try to install ff klar (not to update), the app crashes.

The debug version works, it correctly download ff klar, performs fingerprint check, and install the latest version. Although the installer notification I the app keeps spinning even the ff is installed and could be used. 

Some suggestions:
- it would be really nice to reuse a downloaded file if a ff browser for the repeated installation, bit to download it each time
- information about the app (version, link to issue, etc) in the menu would be nice to have

**Comment by Tobi823** [comment]
The issue should now be fixed (in version 71.0.0).

FFUpdater retries up to two times before crashing (when contacting the server for available versions)

> it would be really nice to reuse a downloaded file if a ff browser for the repeated installation, bit to download it each time
This is quite tricky because I have to store many information.

> information about the app (version, link to issue, etc) in the menu would be nice to have
Sounds good #26
