### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by HarriDuc** [Tobi823/ffupdater#190]
Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.NetworkException: Fail to consume 'https://api.github.com/repos/mozilla-mobile/focus-android/releases/latest'.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:35)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at t2.e.b(Unknown Source:5)
	at o4.d.a(:30)
	at o4.a.intercept(:11)
	at p4.f.b(:3)
	at m4.a.intercept(:22)
	at p4.f.b(:3)
	at p4.a.intercept(:16)
	at p4.f.b(:3)
	at p4.h.intercept(:25)
	at p4.f.b(:3)
	at o4.e.f(:10)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:9)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:13)
	... 4 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 20 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | QC_Reference_Phone |
| brand | samsung |
| device | a02q |
| manufacturer | samsung |
| model | SM-A025M |
| product | a02qub |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1643042133000 |

**Comment by Tobi823** [comment]
Try version 75.5.3 - should be fixed. Please comment on this issue if the error occurs again.
