### ISSUE TITLE
Plz help and tell me why and what is going on ive had strange issues happeningim attaching info

### ISSUE THREAD

**Issue by Droc098** [Tobi823/ffupdater#211]
Here is info:
Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.NetworkException: Fail to consume 'https://api.github.com/repos/mozilla-mobile/focus-android/releases/latest'.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:35)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at t2.e.b(Unknown Source:5)
	at o4.d.a(:30)
	at o4.a.intercept(:11)
	at p4.f.b(:3)
	at m4.a.intercept(:22)
	at p4.f.b(:3)
	at p4.a.intercept(:16)
	at p4.f.b(:3)
	at p4.h.intercept(:25)
	at p4.f.b(:3)
	at o4.e.f(:10)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:9)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:13)
	... 4 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 20 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 31 |
| android release | 12 |
| board | denver |
| brand | motorola |
| device | denver |
| manufacturer | motorola |
| model | moto g stylus 5G |
| product | denver_global |
| SOC manufacturer | QTI |
| SOC model | SM4350 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1651266766000 |Stacktrace:
```
de.marmaro.krt.ffupdater.app.impl.exceptions.NetworkException: Fail to consume 'https://api.github.com/repos/mozilla-mobile/focus-android/releases/latest'.
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:35)
	at r3.a.resumeWith(Unknown Source:8)
	at f4.e0.run(Unknown Source:86)
	at i4.a.p(Unknown Source:0)
	at i4.a$a.run(:5)
Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at t2.e.b(Unknown Source:5)
	at o4.d.a(:30)
	at o4.a.intercept(:11)
	at p4.f.b(:3)
	at m4.a.intercept(:22)
	at p4.f.b(:3)
	at p4.a.intercept(:16)
	at p4.f.b(:3)
	at p4.h.intercept(:25)
	at p4.f.b(:3)
	at o4.e.f(:10)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(:9)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:13)
	... 4 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 20 more
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 31 |
| android release | 12 |
| board | denver |
| brand | motorola |
| device | denver |
| manufacturer | motorola |
| model | moto g stylus 5G |
| product | denver_global |
| SOC manufacturer | QTI |
| SOC model | SM4350 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1651266766000 |
![Screenshot_20220718-205818](https://user-images.githubusercontent.com/109565777/179648685-2a74c828-137a-4dd6-aa51-4a520fca1016.png)

**Comment by Tobi823** [comment]
I suspect that your smartphone lost internet connection when you downloaded or installed an app.
Has the error disappeared or remained?

**Comment by Tobi823** [comment]
closed due to inactivity
