### ISSUE TITLE
Error with background update 

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [Tobi823/ffupdater#224]
Stacktrace:
```
java.lang.IllegalArgumentException: Can't extract the signature from the APK file.
	at de.marmaro.krt.ffupdater.security.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:62)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:26)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install(Unknown Source:100)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at t3.a.resumeWith(Unknown Source:8)
	at g4.h0.run(Unknown Source:94)
	at i4.e.run(Unknown Source:11)
	at j4.j.run(Unknown Source:2)
	at j4.a$a.run(SourceFile:9)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.1.0 (112) release |
| Device | M2102J20SG (vayu_global, vayu, msmnile) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | evolution, vayu, release-keys, 1661821806000 |

**Comment by Tobi823** [comment]
Which apps do you update with FFUpdater?

**Comment by Tobi823** [comment]
I need more context to understand this error

**Comment by Bogdan-Torkhov** [comment]
Firefox focus and Firefox
