### ISSUE TITLE
Network issues - torproject.org is blocked 

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [Tobi823/ffupdater#229]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest Vivaldi version.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.extractVersionAndDownloadUrl(SourceFile:14)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$extractVersionAndDownloadUrl(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$extractVersionAndDownloadUrl$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at m4.e.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:9)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to consume 'https://www.torproject.org/download'.
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:6)
	... 5 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:215)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at t4.f.g(SourceFile:20)
	at t4.f.c(SourceFile:20)
	at t4.d.a(SourceFile:54)
	at t4.a.intercept(SourceFile:11)
	at u4.f.b(SourceFile:7)
	at r4.a.intercept(SourceFile:29)
	at u4.f.b(SourceFile:7)
	at u4.a.intercept(SourceFile:23)
	at u4.f.b(SourceFile:7)
	at u4.h.intercept(SourceFile:25)
	at u4.f.b(SourceFile:7)
	at t4.e.f(SourceFile:10)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:11)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(Unknown Source:19)
	... 5 more
	Suppressed: java.net.SocketException: Connection reset
		... 27 more
	Suppressed: java.net.SocketException: Connection reset
		... 27 more
	Suppressed: java.net.SocketException: Connection reset
		... 27 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.2.0 (113) release |
| Device | M2102J20SG (vayu_global, vayu, msmnile) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | evolution, vayu, release-keys, 1661821806000 |

**Comment by Tobi823** [comment]
Looks like a temporary network issue. Does this issue still persist?

**Comment by Bogdan-Torkhov** [comment]
> Looks like a temporary network issue. Does this issue still persist?

Yes,because Russia block torproject.org.

**Comment by Bogdan-Torkhov** [comment]
I think maybe ffupdater need a built in proxy,to fix issues like this.

**Comment by Tobi823** [comment]
That"s bad. I'm thinking of a way to download the Tor Browser anyway.

**Comment by Tobi823** [comment]
Is only the Domain blocked? Or the IPs of the domain?

Can you download the website with one of these commands? If yes, than only the domain is blocked:
```
wget --no-check-certificate --header 'Host:www.torproject.org' https://116.202.120.166/download 
wget --no-check-certificate --header 'Host:www.torproject.org' https://116.202.120.165/download 
wget --no-check-certificate --header 'Host:www.torproject.org' https://158.69.113.194/download 
wget --no-check-certificate --header 'Host:www.torproject.org' https://158.69.113.215/download 
wget --no-check-certificate --header 'Host:www.torproject.org' https://95.216.163.36/download 
```

Which typ of proxy do you want/need to use? HTTP, HTTPS, SOCKSv4 or SOCKSv5?

**Comment by Bogdan-Torkhov** [comment]
Ips also blocked.All types of proxys that you know how to add.And also i want shadow socks.

**Comment by Tobi823** [comment]
FFUpdater now supports Dns-over-HTTPS and HTTP/SOCKS-proxies. You can enable these features in the settings.

Internally OkHttp will be use for communicating with Doh-, HTTP- or SOCKS-server

**Comment by Bogdan-Torkhov** [comment]
Ok,thanks
