### ISSUE TITLE
FFUpdater 77.2.0 crash report

### ISSUE THREAD

**Issue by Diogopestana31** [Tobi823/ffupdater#237]
Stacktrace:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(Unknown Source:288)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at m4.e.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:9)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.2.0 (113) release |
| Device | SM-T510 (gta3xlwifieea, gta3xlwifi, exynos7904) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | VPDJR106, dpi, release-keys, 1658483657000 |

**Comment by root021** [comment]
I have received the same issue:

Stacktrace:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(Unknown Source:288)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at m4.e.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:9)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.2.0 (113) release |
| Device | Pixel 5 (redfin, redfin, redfin) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | calyxos-ic-dev, cdesai, release-keys, 1664921222000 |

**Comment by Tobi823** [comment]
Duplicated of #238
