### ISSUE TITLE
Crash during update of Lite

### ISSUE THREAD

**Issue by mega-stoffel** [Tobi823/ffupdater#24]
Hej there!
I'm running Firefox lite (and Klar and Browser).
But I can't update lite from 2.5.2 to 2.6.0 (the others worked).
It looks like the download is successful, but when it tries to update the package it crashes with this error message.
I tried it many times already, always the same result.

java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.verifyPackageInfo(FingerprintValidator.java:72)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(FingerprintValidator.java:47)
	at de.marmaro.krt.ffupdater.InstallActivity$1.lambda$onReceive$0$InstallActivity$1(InstallActivity.java:262)
	at de.marmaro.krt.ffupdater.-$$Lambda$InstallActivity$1$LqHCXswk3aZ1y_DLFUVKPrapTCs.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Iey4iej3** [comment]
Same here.

**Comment by Tobi823** [comment]
Sorry for the late response.

Can you check if the error is still present in version 71.0.0? (Should be available on F-Droid in the next days)

**Comment by Iey4iej3** [comment]
Still present in 71.0.1 (57).

**Comment by Iey4iej3** [comment]
Crash on 71.0.2 (58). Log:

```
java.lang.NullPointerException at FingerprintValidator.kt:32
java.lang.NullPointerException

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(FingerprintValidator.kt:32)
	at de.marmaro.krt.ffupdater.InstallActivity$State$8$fingerprint$1.invokeSuspend(InstallActivity.kt:263)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


Android Version: 29
```

**Comment by Tobi823** [comment]
My bad - Martin Rey notified me that the latest release of Firefox Lite is unsigned (https://notabug.org/Tobiwan/ffupdater/issues/49)

And that is a big problem. Even if FFUpdater won't crash, you wouldn't be able to update Firefox Lite. Android requires that the signature of the old and the new version of an app must match. 

The only way to install an unsigned update is to uninstall Firefox Lite first

I add a comment to the existing issue on the Github page https://github.com/mozilla-mobile/FirefoxLite/issues/5353 - maybe the developers will respond to it.

What should I do when the developers don't respond? Should I remove FirefoxLite from FFUpdater because it's not longer active developed? But security holes are stilled fixed according to this section in the README:
> Notice - Firefox Lite is currently in Maintenance Mode. No active feature is being done on the product. Older Pull Requests and Issues have been marked with the archived label and have been closed. However, if you feel an issue is critical enough to be re-opened, please leave a note on the issue with an explanation.

**Comment by Iey4iej3** [comment]
Thank you very much. I think that we can close this issue. It is not in any sense an issue of FFUpdater.

**Comment by Tobi823** [comment]
I will remove Firefox Lite for now. If the developers publish a signed update, I can revert my changes.
