### ISSUE TITLE
Can't validate the signature of the APK file because file is missing

### ISSUE THREAD

**Issue by ren7uk** [Tobi823/ffupdater#251]
FF Updater does now show Tor Browser up to date in the browser list though.
Stack trace:
```
java.lang.RuntimeException: Failed to install TOR_BROWSER in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:214)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: Can't validate the signature of the APK file.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install(Unknown Source:219)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at m4.e.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:9)
Caused by: java.io.FileNotFoundException: File '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.torproject.torbrowser.apk' does not exists.
	at de.marmaro.krt.ffupdater.security.PackageManagerUtil.getPackageArchiveInfo(SourceFile:2)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:26)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install(Unknown Source:88)
	... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.2.0 (113) release |
| Device | H4113 (H4113, H4113, sdm660) |
| Manufacturer | Sony (Sony) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | ip-10-248-1-131, hudsonslave, release-keys, 1596765931000 |

**Comment by Tobi823** [comment]
For almost two years I received this kind of bug. But these were always sporadic and I was not able to determine the real cause of this bug.

After a download the downloaded file should be available - but this exception tells me that the file is not available. And I have no idea why ... 

Can you help me and tell me, what and which apps and settings you are using? Maybe some special root app, some special privacy feature, a very slow operating system or a full storage?

**Comment by Tobi823** [comment]
Does this crash still occur?
