### ISSUE TITLE
Network Issue - SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by danifullview** [Tobi823/ffupdater#255]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.UnrecoverableBackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:53)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at n4.a$a.run(SourceFile:82)
Caused by: e3.s: java.net.SocketException: Software caused connection abort
	at e3.h.c(SourceFile:60)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:237)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:20)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at m4.d.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
	at b5.m.read(SourceFile:46)
	at b5.c.read(SourceFile:13)
	at b5.r.read(SourceFile:4)
	at w4.f$c.g(SourceFile:174)
	at w4.q.a(SourceFile:770)
	at w4.f$c.invoke(SourceFile:12)
	at s4.b.a(Unknown Source:2)
	at s4.d.a(SourceFile:19)
	at s4.e.run(SourceFile:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.0 (114) release |
| Device | SM-G970F (lineage_beyond0lte, beyond0lte, exynos9820) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | fb5d356282cf, root, release-keys, 1651117678000 |

**Comment by Tobi823** [comment]
Seems to be a random network error. I will look if I can improve the UI to communicate that this is caused by a (not so uncommon and temporary) network problem
