### ISSUE TITLE
Different fingerprint of MULL_FROM_REPO

### ISSUE THREAD

**Issue by caskera** [Tobi823/ffupdater#257]
Stacktrace:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:226)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: Downloaded application is NOT verified. Expected e4be8d6abfa4d9d4feef03cdda7ff62a73fd64b75566f6dd4e5e577550be8467 but was 260e0a49678c78b70c02d6537add3b6dc0a17171bbde8ce75fd4026a8a3e18d2.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install(SourceFile:241)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at m4.d.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:82)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.1 (115) release |
| Device | ONEPLUS A5010 (OnePlus5T, OnePlus5T, msm8998) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | derpbox, private, release-keys, 1661575290000 |

**Comment by Tobi823** [comment]
is now fixed in 77.3.5
