### ISSUE TITLE
Issued while checking for update of Fennec F-Droid, Report 2 from notification panel in status bar.

### ISSUE THREAD

**Issue by Universalizer** [Tobi823/ffupdater#261]
### **Thanks for your app, but issued while checking for update of Fennec F-Droid, Report 2 from notification panel in status bar, as follows :-**

Stacktrace:
```
de.marmaro.krt.ffupdater.background.UnrecoverableBackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:53)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at n4.a$a.run(SourceFile:82)
Caused by: java.lang.Exception: The app does not support the device
	at de.marmaro.krt.ffupdater.device.DeviceAbiExtractor.findBestAbiForDeviceAndApp(Unknown Source:41)
	at de.marmaro.krt.ffupdater.app.impl.FennecFdroid.findLatestUpdate$ffupdater_release(SourceFile:64)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(Unknown Source:64)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.access$findAppUpdateStatus(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateWithoutLoadingFromCacheAsync$2$1.invokeSuspend(Unknown Source:84)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at m4.d.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	... 1 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.1 (115) release |
| Device | SM-J600G (j6ltedx, j6lte, exynos7870) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | Android 32-bit Only (Not 64-bit)  |         

_By the way can you, “add feature that allows user to send feedback within your app menu”, so that direct reporting can be possible._

**Comment by Tobi823** [comment]
Should be fixed in 77.3.4
