### ISSUE TITLE
Crash from android_getaddrinfo failing

### ISSUE THREAD

**Issue by hlovdal** [Tobi823/ffupdater#269]
I got the following crashreport after a message about not being able to check for 5 days popped up (I only occationally have the device connected to wifi).

Stacktrace:
```
de.marmaro.krt.ffupdater.background.RecoverableBackgroundException: The background job fails due to a recoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:70)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at n4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request latest version of BRAVE in background.
	at de.marmaro.krt.ffupdater.BackgroundJob.checkForUpdates(SourceFile:389)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$checkForUpdates(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$checkForUpdates$1.invokeSuspend(Unknown Source:11)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of Brave.
	at de.marmaro.krt.ffupdater.app.impl.Brave.findLatestUpdate$ffupdater_release(SourceFile:166)
	at de.marmaro.krt.ffupdater.app.impl.Brave$findLatestUpdate$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at m4.d.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	... 1 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of brave-browser from GitHub.
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.updateCheck(SourceFile:2)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$updateCheck$1.invokeSuspend(Unknown Source:19)
	... 5 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to consume 'https://api.github.com/repos/brave/brave-browser/releases?per_page=20&page=1'.
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:90)
	... 5 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at a0.b.c(SourceFile:6)
	at t4.d.a(SourceFile:383)
	at t4.a.intercept(SourceFile:62)
	at u4.f.b(SourceFile:144)
	at r4.a.intercept(SourceFile:164)
	at u4.f.b(SourceFile:144)
	at u4.a.intercept(SourceFile:140)
	at u4.f.b(SourceFile:144)
	at u4.h.intercept(SourceFile:147)
	at u4.f.b(SourceFile:144)
	at t4.e.f(SourceFile:97)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:95)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:20)
	... 5 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 21 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.1 (115) release |
| Device | Nexus 7 (razor, flox, flo) |
| Manufacturer | google (asus) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | b070403c1b02, root, release-keys, 1667300283000 |

**Comment by Tobi823** [comment]
Seems to be a random network error. I will look if I can improve the UI to communicate that this is caused by a (not so uncommon and temporary) network problem
