### ISSUE TITLE
Crash when updating Firefox stable

### ISSUE THREAD

**Issue by bershanskiy** [Tobi823/ffupdater#27]
Application crashed with the following stack trace:
```
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/download_1614178715571_8575317700450285286.apk exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1967)
	at android.net.Uri.checkFileUriExposed(Uri.java:2364)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9778)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9732)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1679)
	at android.app.Activity.startActivityForResult(Activity.java:4482)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
	at android.app.Activity.startActivityForResult(Activity.java:4440)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
	at de.marmaro.krt.ffupdater.installer.IntentInstaller.installInternal(IntentInstaller.kt:60)
	at de.marmaro.krt.ffupdater.installer.IntentInstaller.install(IntentInstaller.kt:38)
	at de.marmaro.krt.ffupdater.InstallActivity$State$10.invokeSuspend(InstallActivity.kt:256)
	at de.marmaro.krt.ffupdater.InstallActivity$State$10.invoke(Unknown Source:10)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invokeSuspend(InstallActivity.kt:113)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:109)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6797)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```

**Comment by Tobi823** [comment]
I've found the bug. The fix will be implemented in version 71.0.3
