### ISSUE TITLE
Kiwi update error.

### ISSUE THREAD

**Issue by dirt2022** [Tobi823/ffupdater#274]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/kiwibrowser/src.next/releases/download/3356207093/com.kiwibrowser.browser-arm64-3356207093-github.apk failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileAsync$2$1.invokeSuspend(Unknown Source:132)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: java.net.SocketTimeoutException: failed to connect to github.com/20.205.243.166 (port 443) from /192.168.31.27 (port 38816) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
	at libcore.io.IoBridge.connect(IoBridge.java:129)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:391)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:231)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:213)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at a5.c.e(Unknown Source:5)
	at w4.f.e(SourceFile:74)
	at w4.f.c(SourceFile:20)
	at w4.d.a(SourceFile:677)
	at w4.a.intercept(SourceFile:62)
	at x4.f.a(SourceFile:144)
	at u4.a.intercept(SourceFile:164)
	at x4.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:140)
	at x4.f.a(SourceFile:144)
	at x4.h.intercept(SourceFile:147)
	at x4.f.a(SourceFile:144)
	at w4.e.f(SourceFile:97)
	at w4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | JDN2-AL50 (JDN2-AL50, HWJDN2, JDN2) |
| Manufacturer | HUAWEI (HUAWEI) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | cn-central-1b-f189cca201593764352721-2149612947-6z4tg, test, release-keys, 1593769262000 |

**Comment by Tobi823** [comment]
Seems to be a random network error. I will look if I can improve the UI to communicate that this is caused by a (not so uncommon and temporary) network problem
