### ISSUE TITLE
Issued While Installing MULL

### ISSUE THREAD

**Issue by Universalizer** [Tobi823/ffupdater#275]
### Stacktrace:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:226)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: Installation failed. resultCode: 1, INSTALL_RESULT: -113
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(SourceFile:111)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(Unknown Source:2)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate$lambda-0(Unknown Source:5)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.b(Unknown Source:0)
	at y.c.a(Unknown Source:6)
	at androidx.activity.result.f.a(Unknown Source:46)
	at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
	at androidx.fragment.app.o.onActivityResult(Unknown Source:5)
	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5223)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5271)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | SM-J600G (j6ltedx, j6lte, exynos7870) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | dpi, release-keys, Android 32-bit armeabi-v7a |         

_Whether screenshot is needed ? , do i need to uninstall the old version and re-install MULL from your app's cached ?,  kindly confirm_

**Comment by Tobi823** [comment]
There was a bug that FFUpdater downloaded the 64bit instead of the 32bit APK. The bug is fixed and you should be able to install Mull.

Or am I missing something?
