### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by carbongreat13** [Tobi823/ffupdater#276]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/mozilla-mobile/focus-android/releases/download/v107.1.0/klar-107.1.0-arm64-v8a.apk failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileAsync$2$1.invokeSuspend(Unknown Source:132)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at e5.m.read(SourceFile:46)
	at e5.c.read(SourceFile:13)
	at e5.r.read(SourceFile:4)
	at z4.f$c.d(SourceFile:174)
	at z4.q.a(SourceFile:770)
	at z4.f$c.invoke(SourceFile:12)
	at v4.b.a(Unknown Source:2)
	at v4.d.a(SourceFile:19)
	at v4.e.run(SourceFile:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | Pixel 5a (barbet, barbet, barbet) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | abfarm-release-rbe-64-00008, android-build, release-keys, 1663612430000 |

**Comment by Tobi823** [comment]
looks like a one time network problem - or am I missing something?

**Comment by carbongreat13** [comment]
This issue occurred only once. It has not occurred since then.

**Comment by Tobi823** [comment]
Thanks for the info 👍🏻
