### ISSUE TITLE
Crash again

### ISSUE THREAD

**Issue by dirt2022** [Tobi823/ffupdater#277]
Stacktrace:
```
java.lang.Exception: Fail to request the latest version of Kiwi
	at de.marmaro.krt.ffupdater.app.impl.AppBase.checkForUpdateAsync(SourceFile:109)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateAsync$1.invokeSuspend(Unknown Source:12)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: h3.s: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 7 column 1 path $
	at h3.h.c(SourceFile:69)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:239)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:20)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 7 column 1 path $
	at o3.a.a(SourceFile:57)
	at k3.a.a(Unknown Source:18)
	at h3.h.c(SourceFile:19)
	... 8 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | JDN2-AL50 (JDN2-AL50, HWJDN2, JDN2) |
| Manufacturer | HUAWEI (HUAWEI) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | cn-central-1b-f189cca201593764352721-2149612947-6z4tg, test, release-keys, 1593769262000 |

**Comment by Tobi823** [comment]
I suspect that the API response from GitHub was temporary invalid. Can you open a new ticket if this happens again?
