### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MichaelMosin** [Tobi823/ffupdater#282]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.UnrecoverableBackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:53)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at q4.a$a.run(SourceFile:82)
Caused by: java.lang.Exception: Fail to request the latest version of FennecFdroid
	at de.marmaro.krt.ffupdater.app.impl.AppBase.checkForUpdateWithoutLoadingFromCacheAsync(SourceFile:109)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateWithoutLoadingFromCacheAsync$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: h3.s: java.net.SocketTimeoutException: timeout
	at h3.h.c(SourceFile:60)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:239)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:20)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.SocketTimeoutException: timeout
	at z4.r$c.j(Unknown Source:4)
	at z4.r$c.l(Unknown Source:8)
	at z4.r$b.read(SourceFile:137)
	at w4.c$b.read(SourceFile:16)
	at e5.r.read(SourceFile:4)
	at e5.r.n(Unknown Source:20)
	at e5.l.read(SourceFile:53)
	at e5.k.read(SourceFile:358)
	at e5.r$a.read(SourceFile:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:180)
	at o3.a.q(Unknown Source:31)
	at o3.a.S(Unknown Source:43)
	at o3.a.U(SourceFile:88)
	at k3.n$a.a(Unknown Source:51)
	at h3.h.c(SourceFile:19)
	... 8 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | SM-G991U (o1qsqw, o1q, lahaina) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | SWDK6223, dpi, release-keys, 1663916191000 |

**Comment by Tobi823** [comment]
looks like a one time network problem - or am I missing something?
