### ISSUE TITLE
Stop download 

### ISSUE THREAD

**Issue by Donieck** [Tobi823/ffupdater#284]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://divestos.org/fdroid/official/us.spotco.fennec_dos_21072020.apk failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileAsync$2$1.invokeSuspend(Unknown Source:132)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: java.net.SocketTimeoutException: timeout
	at z4.r$c.j(Unknown Source:4)
	at z4.r$c.l(Unknown Source:8)
	at z4.r$b.read(SourceFile:137)
	at w4.c$b.read(SourceFile:16)
	at e5.r.read(SourceFile:4)
	at e5.i.read(Unknown Source:7)
	at de.marmaro.krt.ffupdater.network.ProgressResponseBody$trackTransmittedBytes$1.read(Unknown Source:5)
	at e5.r$a.read(SourceFile:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at m4.a0.j(Unknown Source:9)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadFileInternal(SourceFile:146)
	at de.marmaro.krt.ffupdater.network.FileDownloader.access$downloadFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileInternal$1.invokeSuspend(Unknown Source:12)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | Mi A1 (lineage_tissot, tissot, MSM8953) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | 2ca17e09fa46, root, release-keys, 1669705024000 |

**Comment by Tobi823** [comment]
looks like a one time network problem - or am I missing something?
