### ISSUE TITLE
Crash Report - Vivaldi

### ISSUE THREAD

**Issue by H-Tung** [Tobi823/ffupdater#286]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Network exception for Vivaldi.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.checkForUpdateAsync(SourceFile:136)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateAsync$1.invokeSuspend(Unknown Source:12)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | MI PLAY (lotus, lotus, unknown) |
| Manufacturer | xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 8.1.0 (SDK: 27) |
| OS | c3-miui-ota-bd153.bj, builder, release-keys, 1605797284000 |

**Comment by Tobi823** [comment]
looks like a one time network problem - or am I missing something?
