### ISSUE TITLE
Crash due to low disk space

### ISSUE THREAD

**Issue by hlovdal** [Tobi823/ffupdater#287]
Stacktrace:
```
java.lang.RuntimeException: Failed to install VIVALDI in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:226)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: The installation failed because of storage issues.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(Unknown Source:4)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(Unknown Source:38)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(Unknown Source:2)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | Nexus 7 (razor, flox, flo) |
| Manufacturer | google (asus) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | b070403c1b02, root, release-keys, 1667300283000 |

**Comment by Tobi823** [comment]
I was not aware that additional information about the installation failure is stored in bundle.getString("EXTRA_STATUS_MESSAGE"). 

But this information is not standardized and may be different on various devices. I can only display and not parse it.

The additional information may help someone diagnose problems - I will display it: 

![image](https://user-images.githubusercontent.com/10066140/205893713-47b18351-95a2-4fef-9fff-92fbc1ccb150.png)

Except that I can't do anything about your problem. Your device has not enough space left or is somehow not available.
