### ISSUE TITLE
Crashed in Background while downloading the Bromite update.

### ISSUE THREAD

**Issue by ashutoshccet** [Tobi823/ffupdater#291]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/bromite/bromite/releases/download/108.0.5359.109/arm64_ChromePublic.apk failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileAsync$2$1.invokeSuspend(Unknown Source:132)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: java.net.SocketTimeoutException: timeout
	at z4.r$c.j(Unknown Source:4)
	at z4.r$c.l(Unknown Source:8)
	at z4.r$b.read(SourceFile:137)
	at w4.c$b.read(SourceFile:16)
	at e5.r.read(SourceFile:4)
	at e5.i.read(Unknown Source:7)
	at de.marmaro.krt.ffupdater.network.ProgressResponseBody$trackTransmittedBytes$1.read(Unknown Source:5)
	at e5.r$a.read(SourceFile:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at m4.a0.j(Unknown Source:9)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadFileInternal(SourceFile:146)
	at de.marmaro.krt.ffupdater.network.FileDownloader.access$downloadFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadFileInternal$1.invokeSuspend(Unknown Source:12)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | POCO M2 Pro (aosp_miatoll, gram, atoll) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | PixelOS-CI, karan, release-keys, 1667544186000 |

**Comment by Tobi823** [comment]
Your smartphone lost network during the APK download. 

I have no idea how to further improve the handling of this error type. If you have an idea, tell me.

**Comment by Tobi823** [comment]
Or did I miss something. What you mean with "background"? Did you minimized the app?

**Comment by Tobi823** [comment]
Thanks for the info. If the error was caused by the background update check, that's good news. Version 77.4.0 should handle background exceptions much better.
