### ISSUE TITLE
Ffupdater

### ISSUE THREAD

**Issue by VinceFux** [Tobi823/ffupdater#298]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.UnrecoverableBackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:53)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at q4.a$a.run(SourceFile:82)
Caused by: java.lang.Exception: Fail to request the latest version of Brave
	at de.marmaro.krt.ffupdater.app.impl.AppBase.checkForUpdateWithoutLoadingFromCacheAsync(SourceFile:109)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateWithoutLoadingFromCacheAsync$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: h3.s: java.net.SocketException: Software caused connection abort
	at h3.h.c(SourceFile:60)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(SourceFile:239)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.access$consume(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consumeAsync$2$1.invokeSuspend(SourceFile:20)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at e5.m.read(SourceFile:46)
	at e5.c.read(SourceFile:13)
	at e5.r.read(SourceFile:4)
	at z4.f$c.d(SourceFile:174)
	at z4.q.a(SourceFile:770)
	at z4.f$c.invoke(SourceFile:12)
	at v4.b.a(Unknown Source:2)
	at v4.d.a(SourceFile:19)
	at v4.e.run(SourceFile:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | Mi 9T (arrow_davinci, davinci, sm6150) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | release, arrow, release-keys, 1669615729000 |

**Comment by Tobi823** [comment]
Your smartphone lost network during the background update check. (And there is nothing that I can do about it)

I will implement a new notification for network errors in the background job. This should help users to distinguish between critical errors and not so critical network errors.

**Comment by VinceFux** [comment]
THANK YOU!!!!
