### ISSUE TITLE
Crash Error Report

### ISSUE THREAD

**Issue by MetaApo13** [Tobi823/ffupdater#299]
Stacktrace:

```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(SourceFile:105)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at q4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FirefoxNightly.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of mobile.v2.fenix.nightly.latest.arm64-v8a from Mozilla (json).
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.updateCheck(SourceFile:234)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$updateCheck$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/chain-of-trust.json failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:110)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.SocketTimeoutException: failed to connect to firefox-ci-tc.services.mozilla.com/35.190.5.182 (port 443) from /10.111.222.1 (port 44718) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at c5.h.e(Unknown Source:5)
	at y4.f.e(SourceFile:74)
	at y4.f.c(SourceFile:20)
	at y4.d.a(SourceFile:61)
	at y4.a.intercept(SourceFile:64)
	at z4.f.a(SourceFile:144)
	at w4.a.intercept(SourceFile:164)
	at z4.f.a(SourceFile:144)
	at z4.a.intercept(SourceFile:140)
	at z4.f.a(SourceFile:144)
	at z4.h.intercept(SourceFile:155)
	at z4.f.a(SourceFile:144)
	at y4.e.f(SourceFile:97)
	at y4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.net.SocketException: Software caused connection abort
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
		at java.net.SocketInputStream.read(SocketInputStream.java:173)
		at java.net.SocketInputStream.read(SocketInputStream.java:143)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
		at g5.m.read(SourceFile:46)
		at g5.c.read(SourceFile:13)
		at g5.r.f(SourceFile:31)
		at g5.r.B(Unknown Source:0)
		at b5.q.a(SourceFile:11)
		at b5.f$c.invoke(SourceFile:12)
		at x4.b.a(Unknown Source:2)
		at x4.d.a(SourceFile:19)
		at x4.e.run(SourceFile:46)
		... 3 more
```

Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.5.0 (121) release |
| Device | moto g52 (rhode_g, rhode, rhode) |
| Manufacturer | motorola (motorola) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | ilclbld154, hudsoncm, release-keys, 1667208685000 |

**Comment by Tobi823** [comment]
Your smartphone lost network during the background update check.

I will implement a new notification for network errors in the background job. This should help users to distinguish between critical errors and not so critical network errors.
