### ISSUE TITLE
Error when going in landscape mode while viewing browser options (+ button)

### ISSUE THREAD

**Issue by floringolintchi** [Tobi823/ffupdater#30]
Doesn't actually crash the application. Seems to be caused by changing viewing mode while viewing the + browser menu. Returns following stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.marmaro.krt.ffupdater.dialog.InstallAppDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3477)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5514)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5422)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.marmaro.krt.ffupdater.dialog.InstallAppDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:625)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2714)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:307)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:269)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at de.marmaro.krt.ffupdater.MainActivity.onCreate(MainActivity.kt:42)
	at android.app.Activity.performCreate(Activity.java:7822)
	at android.app.Activity.performCreate(Activity.java:7811)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
	... 13 more
Caused by: java.lang.NoSuchMethodException: de.marmaro.krt.ffupdater.dialog.InstallAppDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:610)
	... 28 more
```

**Comment by Tobi823** [comment]
Thanks for the good description. I've able to reproduce and fix the bug. 
(I have wrongly used the DialogFrament-API https://stackoverflow.com/a/19196843 https://gist.github.com/runemart/b3e3778ec9663852837d)

Version 71.0.4 will contain the fix.
