### ISSUE TITLE
Failed to update FF Nightly on Android 8.0.0

### ISSUE THREAD

**Issue by thjwong** [Tobi823/ffupdater#301]
Here's the bug report from the crash with native option:

Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_NIGHTLY in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:226)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: Installation failed. resultCode: 1, INSTALL_RESULT: -4
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(SourceFile:111)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(Unknown Source:2)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate$lambda-0(Unknown Source:5)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.b(Unknown Source:0)
	at y.c.a(Unknown Source:6)
	at androidx.activity.result.ActivityResultRegistry$1.a(SourceFile:98)
	at androidx.lifecycle.p$a.a(SourceFile:18)
	at androidx.lifecycle.p.h(SourceFile:332)
	at androidx.lifecycle.p.g(SourceFile:50)
	at androidx.lifecycle.p.f(Unknown Source:9)
	at androidx.lifecycle.y.a(Unknown Source:30)
	at androidx.lifecycle.y.b(Unknown Source:10)
	at androidx.lifecycle.y.onStart(SourceFile:36)
	at android.app.Fragment.performStart(Fragment.java:2657)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1317)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1554)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1617)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3047)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchStart(FragmentController.java:189)
	at android.app.Activity.performStart(Activity.java:7409)
	at android.app.Activity.performRestart(Activity.java:7477)
	at android.app.Activity.performResume(Activity.java:7482)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4256)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | WAS-LX1A (WAS-LX1A, HWWAS-H, hi6250) |
| Manufacturer | HUAWEI (HUAWEI) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 8.0.0 (SDK: 26) |
| OS | cn-west-3a-752a333081594803188947-4136138148-qtgq0, test, release-keys, 1594699997000 |

**Comment by Tobi823** [comment]
Does the SessionInstaller work (the other option beside of the native installer)?

**Comment by thjwong** [comment]
I had the SessionInstaller failed on me first before trying out the native installer.

**Comment by Tobi823** [comment]
Do you have enough storage/memory to install the update? This random website https://dev.to/devwithzachary/what-do-mobile-app-installation-result-codes-on-huawei-devices-mean-and-how-to-resolve-them-2a3g claims that result code -4 mean:

> Insufficient storage space (result code: -4).
Cause analysis: The storage space is insufficient for installing an app.
Solution: Open Optimizer and tap Cleanup to free up some storage space on your phone.

**Comment by thjwong** [comment]
Thanks Tobi, it's now solved - I thought 1 Gb free space was already enough for the update, and didn't think of free space as a problem again.

**Comment by Tobi823** [comment]
The Huawei INSTALL_CODE explanations from https://dev.to/devwithzachary/what-do-mobile-app-installation-result-codes-on-huawei-devices-mean-and-how-to-resolve-them-2a3g are now in FFUpdater and will be displayed.
