### ISSUE TITLE
can't update KIWI

### ISSUE THREAD

**Issue by dirt2022** [Tobi823/ffupdater#302]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for KIWI.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for Kiwi.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 9 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of src.next from GitHub.
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.updateCheck(SourceFile:2)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$updateCheck$1.invokeSuspend(Unknown Source:19)
	... 9 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/kiwibrowser/src.next/releases?per_page=3&page=1 failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:64)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.FileDownloader.validateAndReturnResponseBody(SourceFile:93)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadSmallFileInternal(Unknown Source:78)
	at de.marmaro.krt.ffupdater.network.FileDownloader.access$downloadSmallFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileInternal$1.invokeSuspend(Unknown Source:12)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.5.0 (121) release |
| Device | JDN2-AL50 (JDN2-AL50, HWJDN2, JDN2) |
| Manufacturer | HUAWEI (HUAWEI) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | cn-central-1b-f189cca201593764352721-2149612947-6z4tg, test, release-keys, 1593769262000 |

**Comment by Tobi823** [comment]
That'r really strange - for some reason the URL https://api.github.com/repos/kiwibrowser/src.next/releases?per_page=3&page=1 was not found (HTTP code 404).

Can you open the URL https://api.github.com/repos/kiwibrowser/src.next/releases?per_page=3&page=1 with your favourite Android brower and check if the website is available?

**Comment by Tobi823** [comment]
The website should look like this 
![image](https://user-images.githubusercontent.com/10066140/209954404-739d0658-efe1-4183-ae42-982fd20bb897.png)

**Comment by dirt2022** [comment]
No，It always doesn't work

**Comment by Tobi823** [comment]
Can you make a screenshot of this website https://api.github.com/repos/kiwibrowser/src.next/releases?per_page=3&page=1 and upload it here?

**Comment by dirt2022** [comment]
![Uploading Screenshot_20230103_082122.jpg…]()

**Comment by dirt2022** [comment]
I flushed the DNS cache. And it works!

**Comment by dirt2022** [comment]
resolved
