### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by Zoomaaa** [Tobi823/ffupdater#303]
Here is crash report
Stacktrace:
```
java.lang.IllegalStateException: Can't find version with regex pattern '\((.+)\)'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.getInstalledVersion(SourceFile:83)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.getDisplayInstalledVersion(Unknown Source:8)
	at de.marmaro.krt.ffupdater.MainActivity.addAppToUserInterface(Unknown Source:179)
	at de.marmaro.krt.ffupdater.MainActivity.addAppsToUserInterface(Unknown Source:211)
	at de.marmaro.krt.ffupdater.MainActivity.access$addAppsToUserInterface(Unknown Source:0)
	at de.marmaro.krt.ffupdater.MainActivity$addAppsToUserInterface$1.invokeSuspend(Unknown Source:11)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: m4.g0: [k1{Cancelling}@9f49b9e, Dispatchers.Main]
Timestamp: 2023-01-04T02:01:25.124

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.5.0 (121) release |
| Device | SM-A315F (a31xx, a31, a31) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | VPDJR104, dpi, release-keys, 1667397053000 |

**Comment by Tobi823** [comment]
Strange - I can't reproduce the error. I just released version 77.6.0 with an improved logic - can you try it again with version 77.6.0?

**Comment by Zoomaaa** [comment]
I installed 77.6.0 and I got this

Stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4872)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.getInstalledVersion(Unknown Source:24)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.getDisplayInstalledVersion(Unknown Source:8)
	at de.marmaro.krt.ffupdater.MainActivity$InstalledAppsAdapter.onBindViewHolderWhenNormal(Unknown Source:10)
	at de.marmaro.krt.ffupdater.MainActivity$InstalledAppsAdapter.onBindViewHolder(Unknown Source:90)
	at de.marmaro.krt.ffupdater.MainActivity$InstalledAppsAdapter.onBindViewHolder(Unknown Source:2)
	at androidx.recyclerview.widget.RecyclerView$e.onBindViewHolder(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$e.bindViewHolder(SourceFile:32)
	at androidx.recyclerview.widget.RecyclerView$s.i(SourceFile:1159)
	at androidx.recyclerview.widget.LinearLayoutManager$c.b(SourceFile:59)
	at androidx.recyclerview.widget.LinearLayoutManager.P0(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.C0(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.W(SourceFile:958)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:39)
	at androidx.recyclerview.widget.RecyclerView.o(SourceFile:91)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at d2.e.t(SourceFile:160)
	at d2.f.h(SourceFile:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:43)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1331)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4031)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Timestamp: 2023-01-04T10:26:18.827

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.0 (122) release |
| Device | SM-A315F (a31xx, a31, a31) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | VPDJR104, dpi, release-keys, 1667397053000 |

**Comment by Tobi823** [comment]
I found the error - can you try this version? 
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/10343385/ffupdater-release.zip)

**Comment by Zoomaaa** [comment]
This worked. Thank you.

**Comment by Tobi823** [comment]
Version 77.6.1 with this release is now released.
