### ISSUE TITLE
crash when clicking the warning icon on non installed apps

### ISSUE THREAD

**Issue by thismoon** [Tobi823/ffupdater#309]
how to reproduce:
1. click on the yellow add button
2. click on the warning icon on any entry with warning icon
3. ffupdater crashed and opens the crash reporter window

crash report:
```
java.lang.IllegalArgumentException: Required value was null.
	at de.marmaro.krt.ffupdater.dialog.AppWarningDialog$Companion.newInstance(Unknown Source:46)
	at de.marmaro.krt.ffupdater.AddAppActivity$AvailableAppsAdapter.onBindViewHolderApp$lambda-1(Unknown Source:12)
	at de.marmaro.krt.ffupdater.AddAppActivity$AvailableAppsAdapter.c(Unknown Source:0)
	at de.marmaro.krt.ffupdater.a.onClick(Unknown Source:10)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

expected behavior: show a warning about the app
info button works as expected
also i rember 😁 it working in older versions

**Comment by Tobi823** [comment]
that was a small mistake on my part - version 77.6.3 should fix this problem
