### ISSUE TITLE
de.marmaro.krt.ffupdater.background.BackgroundException

### ISSUE THREAD

**Issue by foxmask** [Tobi823/ffupdater#310]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:59)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at r4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FIREFOX_RELEASE.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FirefoxRelease.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of mobile.v2.fenix.release.latest.arm64-v8a from Mozilla (log).
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiLogConsumer.updateCheck(SourceFile:162)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiLogConsumer$updateCheck$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.arm64-v8a/artifacts/public/logs/chain_of_trust.log failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at r4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.UnknownHostException: Unable to resolve host "firefox-ci-tc.services.mozilla.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at u4.m.lookup(SourceFile:6)
	at z4.d.a(SourceFile:34)
	at z4.a.intercept(SourceFile:64)
	at a5.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:164)
	at a5.f.a(SourceFile:144)
	at a5.a.intercept(SourceFile:140)
	at a5.f.a(SourceFile:144)
	at a5.h.intercept(SourceFile:155)
	at a5.f.a(SourceFile:144)
	at z4.e.f(SourceFile:97)
	at z4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 17 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.1 (123) release |
| Device | Redmi Note 9S (curtana_eea, curtana, curtana) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | c4-miui-ota-bd089.bj, builder, release-keys, 1628091368000 |

**Comment by Tobi823** [comment]
Update your FFUpdater to version 77.6.3.
The real issue that FFUpdater tries to check for updates although no network is available - this was fixed in 77.6.2 or 77.6.3.
