### ISSUE TITLE
ffupdater crashes when request of HTTP-API failed (No address associated with hostname)

### ISSUE THREAD

**Issue by Saboe** [Tobi823/ffupdater#312]
I got this message from ffupdater today:

Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(SourceFile:105)
at z3.a.resumeWith(Unknown Source:8)
at m4.i0.run(Unknown Source:100)
at q4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FIREFOX_RELEASE.
at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FirefoxRelease.
at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of mobile.v2.fenix.release.latest.arm64-v8a from Mozilla (log).
at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiLogConsumer.updateCheck(SourceFile:162)
at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiLogConsumer$updateCheck$1.invokeSuspend(Unknown Source:12)
... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.arm64-v8a/artifacts/public/logs/chain_of_trust.log failed.
at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:110)
at z3.a.resumeWith(Unknown Source:8)
at m4.i0.run(Unknown Source:100)
at p4.e.run(Unknown Source:11)
at q4.j.run(Unknown Source:2)
... 1 more
Caused by: java.net.UnknownHostException: Unable to resolve host "firefox-ci-tc.services.mozilla.com": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
at java.net.InetAddress.getAllByName(InetAddress.java:1152)
at t4.m.lookup(SourceFile:6)
at y4.d.a(SourceFile:34)
at y4.a.intercept(SourceFile:64)
at z4.f.a(SourceFile:144)
at w4.a.intercept(SourceFile:164)
at z4.f.a(SourceFile:144)
at z4.a.intercept(SourceFile:140)
at z4.f.a(SourceFile:144)
at z4.h.intercept(SourceFile:155)
at z4.f.a(SourceFile:144)
at y4.e.f(SourceFile:97)
at y4.e$a.run(SourceFile:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
... 17 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.5.0 (121) release |
| Device | FP3 (FP3, FP3, FP3) |
| Manufacturer | Fairphone (Fairphone) |
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | jenkins-agent-03, jenkins, release-keys, 1664043912000 |

**Comment by Tobi823** [comment]
Update to version 77.6.3 - prior to this version, FFupdater performs background update checks even if no internet is available

**Comment by Saboe** [comment]
Currently the latest version on F-Droid is version 77.5.0 (as of 27/12/2022).

**Comment by Tobi823** [comment]
Are you sure? The website says 77.6.2 https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/

**Comment by Saboe** [comment]
The app showed until yesterday (7/1/2023) version 77.5.0 as the latest available version. Now I've manually started the re-sync of the f-droid database an now it shows that there were three updates in the meantime. I suppose that's a f-droid app issue.
