### ISSUE TITLE
Crash Reporter

### ISSUE THREAD

**Issue by white-gecko** [Tobi823/ffupdater#313]
I hope, this is enough information, as provided by the app:

Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:59)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at r4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FENNEC_FDROID.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FennecFdroid.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of org.mozilla.fennec_fdroid from F-Droid.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(SourceFile:311)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(Unknown Source:13)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://f-droid.org/api/v1/packages/org.mozilla.fennec_fdroid failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at r4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.UnknownHostException: Unable to resolve host "f-droid.org": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at u4.m.lookup(SourceFile:6)
	at z4.d.a(SourceFile:34)
	at z4.a.intercept(SourceFile:64)
	at a5.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:164)
	at a5.f.a(SourceFile:144)
	at a5.a.intercept(SourceFile:140)
	at a5.f.a(SourceFile:144)
	at a5.h.intercept(SourceFile:155)
	at a5.f.a(SourceFile:144)
	at z4.e.f(SourceFile:97)
	at z4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 17 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.2 (124) release |
| Device | POCO F1 (beryllium, beryllium, sdm845) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |

**Comment by Tobi823** [comment]
Update to version 77.6.3 - prior to this version, FFupdater performs background update checks even if no internet is available
