### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Santeeo** [Tobi823/ffupdater#317]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:59)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at r4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for DUCKDUCKGO_ANDROID.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for DuckDuckGo Android.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of Android from GitHub.
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.getLatestRelease(SourceFile:136)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.access$getLatestRelease(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$getLatestRelease$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/duckduckgo/Android/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at r4.j.run(Unknown Source:2)
	... 1 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at u4.m.lookup(SourceFile:6)
	at z4.d.a(SourceFile:34)
	at z4.a.intercept(SourceFile:64)
	at a5.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:164)
	at a5.f.a(SourceFile:144)
	at a5.a.intercept(SourceFile:140)
	at a5.f.a(SourceFile:144)
	at a5.h.intercept(SourceFile:155)
	at a5.f.a(SourceFile:144)
	at z4.e.f(SourceFile:97)
	at z4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 17 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.3 (125) release |
| Device | SM-A127F (a12snseea, a12s, exynos850) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | 21DKGB21, dpi, release-keys, 1668090674000 |

**Comment by Tobi823** [comment]
I discovered that I introduced a new bug to the background update check: If the background update check fails, FFUpdater will not retry it and display the error notification.

The fix is already committed (036ddc96) and will be released with the next version.
