### ISSUE TITLE
Error after finishing downloaded 'update' file

### ISSUE THREAD

**Issue by Universalizer** [Tobi823/ffupdater#319]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/brave/brave-browser/releases/download/v1.49.24/BraveMonoarm.apk failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadBigFileAsync$deferred$1.invokeSuspend(SourceFile:166)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at r4.j.run(Unknown Source:2)
	at r4.a$a.run(SourceFile:82)
Caused by: java.net.SocketTimeoutException: timeout
	at c5.r$c.j(Unknown Source:4)
	at c5.r$c.l(Unknown Source:8)
	at c5.r$b.read(SourceFile:137)
	at z4.c$b.read(SourceFile:16)
	at h5.r.read(SourceFile:4)
	at h5.i.read(Unknown Source:7)
	at de.marmaro.krt.ffupdater.network.ProgressResponseBody$trackTransmittedBytes$1.read(Unknown Source:5)
	at h5.r$a.read(SourceFile:4)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at androidx.activity.m.k(Unknown Source:9)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadBigFileInternal(Unknown Source:135)
	at de.marmaro.krt.ffupdater.network.FileDownloader.access$downloadBigFileInternal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadBigFileInternal$1.invokeSuspend(Unknown Source:12)
	... 5 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.3 (125) release |
| Device | SM-J600G (j6ltedx, j6lte, exynos7870) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | dpi, release-keys, |

**Comment by Tobi823** [comment]
Did the app crash or is it just the detailed error message?

**Comment by Tobi823** [comment]
The new version should handle this type of error better.

**Comment by Tobi823** [comment]
> Surprisinglyinterrobang, Even didn't found "cached downloaded .apk" file in app's folder.

The old FFUpdater version uses only one file or downloading and cache => If you start a download, the cache will be cleared. But this is also improved in the latest version.

**Comment by Tobi823** [comment]
Thanks :)

The problem was, that I registered a component to late. But for ever reason this mistake did not crash the app in the emulator or my real device (Fairphone 4)
