### ISSUE TITLE
Crash on Android 7, Lineage OS

### ISSUE THREAD

**Issue by NotSoImportant** [Tobi823/ffupdater#32]
After clicking the "install" button. 
ffupdater version: 71.0.2

android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/download_1615533914771_123742997906281366.apk exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
	at android.net.Uri.checkFileUriExposed(Uri.java:2354)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
	at android.app.Activity.startActivityForResult(Activity.java:4229)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
	at android.app.Activity.startActivityForResult(Activity.java:4187)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
	at de.marmaro.krt.ffupdater.installer.IntentInstaller.installInternal(IntentInstaller.kt:64)
	at de.marmaro.krt.ffupdater.installer.IntentInstaller.install(IntentInstaller.kt:40)
	at de.marmaro.krt.ffupdater.InstallActivity$State$10.invokeSuspend(InstallActivity.kt:283)
	at de.marmaro.krt.ffupdater.InstallActivity$State$10.invoke(InstallActivity.kt)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invokeSuspend(InstallActivity.kt:136)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invoke(InstallActivity.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by NotSoImportant** [comment]
Duplicate of #27
