### ISSUE TITLE
Crash asked to be reported: brave browser can't be updated.

### ISSUE THREAD

**Issue by libellula** [Tobi823/ffupdater#321]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.InvalidApiResponseException: Invalid API response for Brave.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.checkForUpdateAsync(SourceFile:165)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$checkForUpdateAsync$1.invokeSuspend(Unknown Source:12)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.InvalidApiResponseException: can't find release after all tries - abort
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.updateCheck(SourceFile:2)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$updateCheck$1.invokeSuspend(Unknown Source:19)
	at z3.a.resumeWith(Unknown Source:8)
	at m4.i0.run(Unknown Source:100)
	at p4.d.run(Unknown Source:11)
	at q4.j.run(Unknown Source:2)
	at q4.a$a.run(SourceFile:82)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.5 (119) release |
| Device | SM-G780G (r8qeea, r8q, kona) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DK7917, dpi, release-keys, 1670383468000 |         

I'm constantly getting this crash. Brave browser refuses to be updated and it shows "BUG" rather than its current available version.

![Screenshot_20230117_190030_FFUpdater](https://user-images.githubusercontent.com/61087558/212976462-8f32576c-7708-44cb-b81b-9086698b8332.jpg)

**Comment by Tobi823** [comment]
I can't reproduce the error - does it still persist?

**Comment by libellula** [comment]
With the latest version, it's gone. Thanks.
