### ISSUE TITLE
frequent background errors

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [Tobi823/ffupdater#324]
I frequently get these background errors every few days.
If you need me to install/compile something to pinpoint the problem I can do this :)

Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:52)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at r4.a$a.run(SourceFile:82)
Caused by: l4.b1: Job was cancelled; job=d1{Cancelling}@f774e41
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.3 (125) release |
| Device | LG-H850 (h1_global_com, h1, MSM8996) |
| Manufacturer | lge (LGE) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | 434dfc3e3d25, root, dev-keys, 1662139190000 |

**Comment by 7sillyeaters** [comment]
I also am getting frequent background errors, just in the last couple days:

`Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:59)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at r4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for ICERAVEN.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for Iceraven.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of iceraven-browser from GitHub.
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.getLatestRelease(SourceFile:136)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.access$getLatestRelease(Unknown Source:0)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$getLatestRelease$1.invokeSuspend(Unknown Source:12)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
	at z3.a.resumeWith(Unknown Source:8)
	at l4.l0.run(Unknown Source:100)
	at p4.e.run(Unknown Source:11)
	at r4.j.run(Unknown Source:2)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at z4.f.g(SourceFile:94)
	at z4.f.c(SourceFile:20)
	at z4.d.a(SourceFile:61)
	at z4.a.intercept(SourceFile:64)
	at a5.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:164)
	at a5.f.a(SourceFile:144)
	at a5.a.intercept(SourceFile:140)
	at a5.f.a(SourceFile:144)
	at a5.h.intercept(SourceFile:155)
	at a5.f.a(SourceFile:144)
	at z4.e.f(SourceFile:97)
	at z4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 23 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 37 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.3 (125) release |
| Device | Moto X4 (lineage_payton, payton, SDM660) |
| Manufacturer | motorola (Motorola) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | 86a99d2930d3, root, release-keys, 1672118073000 |         `

**Comment by Tobi823** [comment]
> I frequently get these background errors every few days.
If you need me to install/compile something to pinpoint the problem I can do this :)

Thanks for the offer but it should be fixed in the latest version

**Comment by tmolitor-stud-tu** [comment]
Cool, thanks!!

**Comment by 7sillyeaters** [comment]
It still did happen a couple times with data saver off, but just now I installed the new update, so that might fix it.

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
