### ISSUE TITLE
unrecoverable exception in background job on Samsung j5

### ISSUE THREAD

**Issue by pabloski80** [Tobi823/ffupdater#326]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(SourceFile)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(SourceFile)
	at z3.a.resumeWith(SourceFile)
	at l4.l0.run(SourceFile)
	at r4.a$a.run(SourceFile:82)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FENNEC_FDROID.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(SourceFile)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(SourceFile)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for FennecFdroid.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(SourceFile)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of org.mozilla.fennec_fdroid from F-Droid.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(SourceFile:311)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(SourceFile)
	... 3 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://f-droid.org/api/v1/packages/org.mozilla.fennec_fdroid failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
	at z3.a.resumeWith(SourceFile)
	at l4.l0.run(SourceFile)
	at p4.e.run(SourceFile)
	at r4.j.run(SourceFile)
	... 1 more
Caused by: java.net.ConnectException: Failed to connect to f-droid.org/136.243.44.143:443
	at z4.f.e(SourceFile:132)
	at z4.f.c(SourceFile:20)
	at z4.d.a(SourceFile:61)
	at z4.a.intercept(SourceFile:64)
	at a5.f.a(SourceFile:144)
	at x4.a.intercept(SourceFile:164)
	at a5.f.a(SourceFile:144)
	at a5.a.intercept(SourceFile:140)
	at a5.f.a(SourceFile:144)
	at a5.h.intercept(SourceFile:155)
	at a5.f.a(SourceFile:144)
	at z4.e.f(SourceFile:97)
	at z4.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
	Suppressed: java.net.ConnectException: Failed to connect to f-droid.org/65.21.79.229:443
		... 16 more
	Caused by: java.net.ConnectException: failed to connect to f-droid.org/65.21.79.229 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
		at libcore.io.IoBridge.isConnected(IoBridge.java:234)
		at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
		at libcore.io.IoBridge.connect(IoBridge.java:122)
		at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
		at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
		at java.net.Socket.connect(Socket.java:884)
		at d5.b.e(SourceFile)
		at z4.f.e(SourceFile:74)
		... 15 more
	Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
		at libcore.io.IoBridge.isConnected(IoBridge.java:223)
		... 22 more
Caused by: java.net.ConnectException: failed to connect to f-droid.org/136.243.44.143 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:234)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
	at java.net.Socket.connect(Socket.java:884)
	at d5.b.e(SourceFile)
	at z4.f.e(SourceFile:74)
	... 15 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
	... 22 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.6.3 (125) release |
| Device | SM-J500FN (j5nltexx, j5nlte, MSM8916) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 6.0.1 (SDK: 23) |
| OS | SWDD6411, dpi, release-keys, 1499319767000 |

**Comment by Tobi823** [comment]
should be improve in the latest version.
