### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by toxcien** [Tobi823/ffupdater#328]
Stacktrace:
```
java.lang.IllegalStateException: LifecycleOwner de.marmaro.krt.ffupdater.DownloadActivity@8272152 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
	at androidx.activity.result.f.c(SourceFile:92)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate(Unknown Source:21)
	at androidx.lifecycle.FullLifecycleObserverAdapter.a(Unknown Source:42)
	at androidx.lifecycle.p$a.a(SourceFile:18)
	at androidx.lifecycle.p.a(SourceFile:115)
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:104)
	at de.marmaro.krt.ffupdater.DownloadActivity.fetchDownloadInformationOrUseCache(Unknown Source:276)
	at de.marmaro.krt.ffupdater.DownloadActivity.checkIfEnoughStorageAvailable(SourceFile:13)
	at de.marmaro.krt.ffupdater.DownloadActivity.checkIfStorageIsMounted(Unknown Source:14)
	at de.marmaro.krt.ffupdater.DownloadActivity.startInstallationProcess(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startInstallationProcess(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$onCreate$3.invokeSuspend(Unknown Source:28)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: i4.j0: [p1{Cancelling}@8a6aef7, Dispatchers.Main]
Timestamp: 2023-01-31T18:49:38.423

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.0 (126) release |
| Device | POCO F2 Pro (lmi_eea, lmi, lmi) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-xztq7, builder, release-keys, 1672051495000 |

**Comment by Tobi823** [comment]
#327
