### ISSUE TITLE
FFUpdater crashed while using Shizuku Installer as Installer method

### ISSUE THREAD

**Issue by muntasimfuad** [Tobi823/ffupdater#330]
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller.executeInstallerSpecificLogic(Unknown Source:266)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(Unknown Source:170)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(Unknown Source:30)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
	Suppressed: i4.j0: [p1{Cancelling}@acd9b36, Dispatchers.Main]
Timestamp: 2023-02-01T22:40:03.184

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.0 (126) release |
| Device | M2006C3MII (cattail, cattail, cattail) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | c4-xm-ota-bd053.bj, builder, release-keys, 1661486991000 |

**Comment by Tobi823** [comment]
I found the error https://github.com/Tobi823/ffupdater/blob/34c53f694ee3059934f13fa730340279c6be1573/ffupdater/src/main/java/de/marmaro/krt/ffupdater/installer/impl/ShizukuInstaller.kt#36

**Comment by Tobi823** [comment]
Version 77.7.1 with the fix for your problem is now released

**Comment by muntasimfuad** [comment]
@Tobi823 Thanks. It was so fast !
