### ISSUE TITLE
Crash after Firefox download, no install. 

### ISSUE THREAD

**Issue by Cheechoz** [Tobi823/ffupdater#332]
Stacktrace:
```
java.lang.IllegalArgumentException: Unrecognized stream
	at android.content.pm.PackageInstaller$Session.fsync(PackageInstaller.java:1180)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.copyApkToSession(Unknown Source:91)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.install(Unknown Source:31)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$executeInstallerSpecificLogic$3.invokeSuspend(Unknown Source:39)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: i4.j0: [p1{Cancelling}@58c8095, Dispatchers.Main]
Timestamp: 2023-02-02T11:08:32.250

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.1 (127) release |
| Device | SM-S908U (b0qsqw, b0q, taro) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6222, dpi, release-keys, 1672997606000 |

**Comment by Tobi823** [comment]
https://github.com/Tobi823/ffupdater/files/10570687/ffupdater-release.zip 

Maybe I fixed the problem. Can you try this version?

**Comment by Cheechoz** [comment]
I downloaded ff directly and installed it manually but I used the new app you sent in the zip and downloaded and installed Tor Browser just fine.

Feb 2, 2023 11:15:06 AM Tobias Hellmann ***@***.***>:

**Comment by Tobi823** [comment]
Perfect. I will release the fix as version 77.7.2

**Comment by Cheechoz** [comment]
Great will update as soon as released 👍

Feb 2, 2023 11:23:38 AM Tobias Hellmann ***@***.***>:

**Comment by Tobi823** [comment]
77.7.2 is now released
