### ISSUE TITLE
Crash while using ffupdater 77.7.1 to update to 77.7.2

### ISSUE THREAD

**Issue by dreamsyntax** [Tobi823/ffupdater#333]
Attempts to install again within the app result in the same crash each time.

Stacktrace:
```
java.lang.IllegalArgumentException: Unrecognized stream
	at android.content.pm.PackageInstaller$Session.fsync(PackageInstaller.java:1174)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.copyApkToSession(Unknown Source:91)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.install(Unknown Source:31)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$executeInstallerSpecificLogic$3.invokeSuspend(Unknown Source:39)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
	Suppressed: i4.j0: [p1{Cancelling}@710f2d4, Dispatchers.Main]
Timestamp: 2023-02-02T10:46:21.731

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.1 (127) release |
| Device | Pixel 6 (oriole, oriole, oriole) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | grapheneos
```

**Comment by Tobi823** [comment]
This is the bug that is fixed in 77.7.2. Sadly you have to use a different method to install the latest FFUpdater version
