### ISSUE TITLE
Tor Browser fail

### ISSUE THREAD

**Issue by Cheechoz** [Tobi823/ffupdater#336]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Wrong file was downloaded. It should be 10485760 bytes long but actual it was 93038389 bytes.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(Unknown Source:68)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(SourceFile:511)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.4 (130) release |
| Device | SM-S908U (b0qsqw, b0q, taro) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6222, dpi, release-keys, 1672997606000 |

**Comment by Tobi823** [comment]
Should be fixed in 77.7.5
