### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ijustlogissues** [Tobi823/ffupdater#342]
Stacktrace:
```
java.lang.Exception: Can't find latest update for ORBOT.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:195)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
	Suppressed: i4.j0: [p1{Cancelling}@645baf9, Dispatchers.Main]
Caused by: java.lang.Exception: Can't find latest update for Orbot.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(Unknown Source:126)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
	... 9 more
Caused by: i4.b1: Job was cancelled; job=q1{Cancelling}@73535ec
Timestamp: 2023-02-13T22:40:39.992

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.5 (131) release |
| Device | SM-A105FN (a10eea, a10, exynos7884B) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | SWDH7913, dpi, release-keys, 1616750502000 |

**Comment by Tobi823** [comment]
Should be fixed in 77.7.8
