### ISSUE TITLE
Can't update Firefox nightly

### ISSUE THREAD

**Issue by xmha97** [Tobi823/ffupdater#354]
# Screenshot
![Screenshot_2023-02-27-23-18-12-822_de.marmaro.krt.ffupdater.jpg](https://user-images.githubusercontent.com/23485114/221667657-60759837-001e-41ca-8151-98961a99e13e.jpg)

# Log
```
java.lang.Exception: Can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(MetadataCache.kt:33)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(MetadataCache.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dbd56b5, Dispatchers.Main]
Caused by: java.lang.Exception: Can't find latest update for FirefoxNightly.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(AppBase.kt:96)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(AppBase.kt:0)
	... 10 more
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.updateCheck(MozillaCiJsonConsumer.kt:35)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$updateCheck$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
	... 10 more
Timestamp: 2023-02-27T23:17:55.069
```

**Comment by APPLESOFT98** [comment]
Tried to download Firefox Nightly and crashed. There's a similar problem while downloading Chromium, it reaches 100% and then crash. Sometime even with Firefox Beta but on the third try it worked with it. Now I don't know if it's a problem with Android/AOSP 13 devices since my old smartphone with Android 10 download and install Chromium just fine (except Firefox Nightly now).

Stacktrace:
```
java.lang.Exception: Can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(MetadataCache.kt:33)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(MetadataCache.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@235fe4b, Dispatchers.Main]
Caused by: java.lang.Exception: Can't find latest update for FirefoxNightly.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(AppBase.kt:96)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(AppBase.kt:0)
	... 10 more
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.updateCheck(MozillaCiJsonConsumer.kt:35)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$updateCheck$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
	... 10 more
Timestamp: 2023-02-27T23:42:53.979

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.7 (133) release |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1675073918000 |

**Comment by RogerioTDS** [comment]
> # Captura de tela
> 
> ![Screenshot_2023-02-27-23-18-12-822_de.marmaro.krt.ffupdater.jpg](https://user-images.githubusercontent.com/23485114/221667657-60759837-001e-41ca-8151-98961a99e13e.jpg)
> # Registro
> 
> ```
> java.lang.Exception: Can't find latest update for FIREFOX_NIGHTLY.
> 	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(MetadataCache.kt:33)
> 	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(MetadataCache.kt:0)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:211)
> 	at android.os.Looper.loop(Looper.java:300)
> 	at android.app.ActivityThread.main(ActivityThread.java:8143)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
> 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dbd56b5, Dispatchers.Main]
> Caused by: java.lang.Exception: Can't find latest update for FirefoxNightly.
> 	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(AppBase.kt:96)
> 	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(AppBase.kt:0)
> 	... 10 more
> Caused by: java.lang.NullPointerException
> 	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.updateCheck(MozillaCiJsonConsumer.kt:35)
> 	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$updateCheck$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
> 	... 10 more
> Timestamp: 2023-02-27T23:17:55.069
> ```

Idem.

**Comment by Tobi823** [comment]
Should be fixed in 77.7.8

**Comment by Tobi823** [comment]
@APPLESOFT98 The Firefox Nightly bug also effected Chromium (because the parsing of web JSON files was broken by my last change to the Proguard rules)

**Comment by xmha97** [comment]
Ok, thanks for your reply. 🙏

**Comment by PsykoRider** [comment]
Stacktrace:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Failed to install FIREFOX_NIGHTLY in the background with SESSION_INSTALLER.
	at de.marmaro.krt.ffupdater.BackgroundJob.installApplication(BackgroundJob.kt:266)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$installApplication(BackgroundJob.kt:46)
	at de.marmaro.krt.ffupdater.BackgroundJob$installApplication$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Can't validate the signature of the APK file.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:32)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(AbstractAppInstaller.kt:15)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(AbstractAppInstaller.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Can't extract the signature from APK file '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fenix_2023-03-01 04:01.apk', length: 42224939, absolutePath: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fenix_2023-03-01 04:01.apk, isFile: true
	at de.marmaro.krt.ffupdater.security.PackageManagerUtil.getPackageArchiveInfo(PackageManagerUtil.kt:48)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invokeSuspend(FingerprintValidator.kt:29)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(FingerprintValidator.kt:0)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(FingerprintValidator.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(FingerprintValidator.kt:28)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:29)
	... 10 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.9 (135) release |
| Device | RMX3561 (RMX3561, RED8BEL1, k6895v1_64) |
| Manufacturer | realme (realme) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | dg02-pool03-kvm41, root, release-keys, 1672839940000 |

**Comment by xmha97** [comment]
Now it working fine.
