### ISSUE TITLE
77.7.8 crash while downloading Chromium

### ISSUE THREAD

**Issue by APPLESOFT98** [Tobi823/ffupdater#356]
Refering to issue [#340](https://github.com/Tobi823/ffupdater/issues/340) that was closed with the last update, but the issue is still present in 77.7.8. When downloading Chromium the download reach 100% and then crash.

Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:17)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:330)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@33bc975, Dispatchers.Main]
Timestamp: 2023-02-28T20:53:53.187

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.8 (134) release |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1675073918000 |

**Comment by Tobi823** [comment]
77.7.9 should really fixed it ;)
