### ISSUE TITLE
ffupdater crash in instation of chromium 

### ISSUE THREAD

**Issue by Sprungles** [Tobi823/ffupdater#359]
Stacktrace:
```
java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.DownloadActivity.reuseCurrentDownload(DownloadActivity.kt:365)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$reuseCurrentDownload(DownloadActivity.kt:59)
	at de.marmaro.krt.ffupdater.DownloadActivity$reuseCurrentDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@27ff810, Dispatchers.Main]
Timestamp: 2023-03-01T14:33:12.695

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.9 (135) release |
| Device | PH-1 (lineage_mata, mata, Mata) |
| Manufacturer | essential (Essential Products) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | ODS-PROD, nolenjohnson, release-keys, 1675913280000 |

**Comment by Tobi823** [comment]
I can't reproduce the issue but I may have fixed the bug
