### ISSUE TITLE
can't update firefox nightly

### ISSUE THREAD

**Issue by ericJrdn** [Tobi823/ffupdater#361]
Stacktrace:
```
java.lang.Exception: Can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(MetadataCache.kt:33)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(MetadataCache.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.Exception: Can't find latest update for FirefoxNightly.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(AppBase.kt:96)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(AppBase.kt:0)
	... 10 more
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.updateCheck(MozillaCiJsonConsumer.kt:35)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$updateCheck$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
	... 10 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.7 (133) release |
| Android version | 13 (SDK: 33) |

**Comment by ericJrdn** [comment]
Duplicate
