### ISSUE TITLE
发生错误

### ISSUE THREAD

**Issue by biange200** [Tobi823/ffupdater#363]
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:28)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:329)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:59)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8496)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@817f1e4, Dispatchers.Main]
Timestamp: 2023-03-04T11:56:22.605

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.9 (135) release |
| Device | V2232A (PD2232, PD2232, taro) |
| Manufacturer | vivo (vivo) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | comdg01146094, compiler, release-keys, 1676635994000 |       

![Screenshot_20230304_115628.jpg](https://user-images.githubusercontent.com/37582806/222874681-2531a1a7-bb1f-4ac5-a497-7af84cb9c099.jpg)

**Comment by Tobi823** [comment]
It seems that the download failed (because the "failed requirement" was caused by the missing download file).

I can't reproduce your error but I will improve the error message. I hope that with the improved error message it will be easier to find a fix.
