### ISSUE TITLE
Problem with installation upgrafe

### ISSUE THREAD

**Issue by Donieck** [Tobi823/ffupdater#367]
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:28)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:328)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@416293f, Dispatchers.Main]
Timestamp: 2023-03-07T00:46:05.983

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.7 (133) release |
| Device | Mi A1 (lineage_tissot, tissot, MSM8953) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | 1144e8cc4fbe, root, release-keys, 1677553666000 |

**Comment by Tobi823** [comment]
I suspect that this is bug #368. Can you update to FFUpdater version 77.7.9 and post the new error message into a new issue? I improved the error messages in 77.7.9 and I need the additional information from the improved error messages.
