### ISSUE TITLE
Crash with self-signed certificate

### ISSUE THREAD

**Issue by linsui** [Tobi823/ffupdater#37]
```
de.marmaro.krt.ffupdater.InstallActivity$InstallActivityFetchException: fail to fetch BROMITE
	at de.marmaro.krt.ffupdater.InstallActivity$State$5.invokeSuspend(InstallActivity.kt:227)
	at de.marmaro.krt.ffupdater.InstallActivity$State$5.invoke(Unknown Source:10)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invokeSuspend(InstallActivity.kt:137)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$ApiConsumerRetryIOException: Fail to consume API. Previous exceptions: [java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.; java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.; java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.; java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.; java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.]. Last exception:
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consumeWithNetworkRetries(ApiConsumer.kt:54)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeWithNetworkRetries$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consume(ApiConsumer.kt:62)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.consumeWithNetworkRetries(ApiConsumer.kt:46)
	... 7 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:658)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
	... 22 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 33 more
```

Could you please add self-signed certificate support?

**Comment by Tobi823** [comment]
What are you doing? I've never seen this error :smile: 

The exception tells me that your android smartphone doesn't trust the SSL/TLS certificate of Github - but why? Are you using a machine-in-the-middle-setup for security analysis?

**Comment by Tobi823** [comment]
Why do you need support for self-signed SSL/TLS certificates?

**Comment by linsui** [comment]
It's a user certificate. You can test it with AdGuard which [filters HTTPS traffic using user certificate](https://kb.adguard.com/en/general/https-filtering#https-filtering-issues-on-android-7). It's easy to support it, see https://gist.github.com/luciopaiva/aa9cb30863804fb2ac3ed1ccd11c95c7 . Thsnks!

**Comment by Tobi823** [comment]
FFUpdater 73.1.0 will support user certificates.

Allowing user certificates will reduce the security. But I think that this risk is acceptable because:
- FFUpdater checks the signature of downloaded APK files
- FFUpdater doesn't send or receive sensible data like passwords 
- FFUpdater uses JSON + GSON-library for update checking. I expect that this technology stack should not be vulnerable to attacks except for DOS-attacks/"stress"-attacks

**Comment by linsui** [comment]
Thanks!
