### ISSUE TITLE
Crash while downloading mulch

### ISSUE THREAD

**Issue by artisan-digital** [Tobi823/ffupdater#371]
I hope this helps.  Thank you for your effort.

ffupdater version 77.7.9

Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:28)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:329)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:59)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4a6ceb0, Dispatchers.Main]
Timestamp: 2023-03-09T10:47:13.476

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.9 (135) release |
| Device | Pixel 3a (sargo, sargo, sargo) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | abfarm801, android-build, release-keys, 1656526244000 |

**Comment by Tobi823** [comment]
Thanks :)

I think this is #368. Unfortunately, these sporadic errors are harder to fix. Unfortunately, I don't have that much time to spare to investigate these sporadic errors - I hope it is not too annoying. I try to fix it as soon as I can.
