### ISSUE TITLE
Failed to update Firefox - crash report

### ISSUE THREAD

**Issue by ssssamstrup** [Tobi823/ffupdater#381]
Have tried several times over the past few days, and failed every time. Have tried switching to legacy which didn't succeed either.

Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:226)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(Unknown Source:4)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$fail(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$fallbackAppInstallationResultListener$1.onFinished(Unknown Source:9)
	at android.content.pm.-$$Lambda$zO9HBUVgPeroyDQPLJE-MNMvSqc.accept(Unknown Source:14)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:285)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
	... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.1 (115) release |
| Device | H8324 (H8324, H8324, sdm845) |
| Manufacturer | Sony (Sony) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | BuildHost, BuildUser, release-keys, 1593023469000 |

**Comment by ssssamstrup** [comment]
With Native installer (after an FFUpdater update) I get this crash message:

**Comment by Tobi823** [comment]
Can you update to FFUpdater 77.7.11 and try updating Firefox again?

INSTALL_RESULT: -25 could mean that FFUpdater tries to update the Firefox with an old version.  And FFUpdater 77.7.10 can't download the latest Firefox because the download origin changed.

**Comment by ssssamstrup** [comment]
The last error report was on FFU 77.7.11. Just tried with normal/session and it failed. This is the error report:

Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:405)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:59)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(SessionInstaller.kt:187)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:126)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:29)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(SessionInstaller.kt:207)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.10 (136) release |
| Device | H8324 (H8324, H8324, sdm845) |
| Manufacturer | Sony (Sony) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | BuildHost, BuildUser, release-keys, 1593023469000 |
