### ISSUE TITLE
Questionable 

### ISSUE THREAD

**Issue by DxBONESxBACK** [Tobi823/ffupdater#383]
Notification just popped up...  ??? 

Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(BackgroundJob.kt:94)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(BackgroundJob.kt:49)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(BackgroundJob.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.FFUpdaterException: Can't find latest update for BROMITE.
	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(MetadataCache.kt:31)
	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(MetadataCache.kt:0)
	... 6 more
Caused by: de.marmaro.krt.ffupdater.FFUpdaterException: Can't find latest update for Bromite.
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(AppBase.kt:94)
	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(AppBase.kt:0)
	... 6 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of bromite from GitHub.
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.getLatestRelease(GithubConsumer.kt:59)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.access$getLatestRelease(GithubConsumer.kt:12)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$getLatestRelease$1.invokeSuspend(GithubConsumer.kt:0)
	... 6 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/bromite/bromite/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(FileDownloader.kt:89)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invoke(FileDownloader.kt:0)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invoke(FileDownloader.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadSmallFileAsync(FileDownloader.kt:83)
	at de.marmaro.krt.ffupdater.network.ApiConsumer.consume(ApiConsumer.kt:18)
	at de.marmaro.krt.ffupdater.network.ApiConsumer$consume$3.invokeSuspend(ApiConsumer.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Missing connection details for custom DoH server.
	at de.marmaro.krt.ffupdater.settings.NetworkSettingsHelper.customDohServer(NetworkSettingsHelper.kt:48)
	at de.marmaro.krt.ffupdater.network.FileDownloader.createDnsConfigurationFromUserInput(FileDownloader.kt:193)
	at de.marmaro.krt.ffupdater.network.FileDownloader.createDnsConfiguration(FileDownloader.kt:187)
	at de.marmaro.krt.ffupdater.network.FileDownloader.createClient(FileDownloader.kt:143)
	at de.marmaro.krt.ffupdater.network.FileDownloader.callUrl(FileDownloader.kt:122)
	at de.marmaro.krt.ffupdater.network.FileDownloader.callUrl$default(FileDownloader.kt:117)
	at de.marmaro.krt.ffupdater.network.FileDownloader.downloadSmallFileInternal(FileDownloader.kt:98)
	at de.marmaro.krt.ffupdater.network.FileDownloader.access$downloadSmallFileInternal(FileDownloader.kt:27)
	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(FileDownloader.kt:85)
	... 16 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.11 (137) release |
| Device | REVVL V+ 5G (Sprout, Sprout, S98115AA1) |
| Manufacturer | T-Mobile (Wingtech) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | ubuntu, cibuild, release-keys, 1677932900000 |

**Comment by Tobi823** [comment]
Seems that you have 

- enabled the DoH in the network settings and
- did not enter the address of the DoH server

You can either change "DNS settings" to "Use system DNS" or enter the address of your favourite DNS over HTTPS server

**Comment by Tobi823** [comment]
Real reason for the crash:

> Caused by: java.lang.IllegalArgumentException: Missing connection details for custom DoH server.

**Comment by DxBONESxBACK** [comment]
Wow your ⚡ fast... That's what I just found as well and came back to let you know its solved.  Thanks
