### ISSUE TITLE
Excessive Updates

### ISSUE THREAD

**Issue by DxBONESxBACK** [Tobi823/ffupdater#387]
I am not sure if they're actually different because I haven't been paying attention to the version numbers however in the last couple days the FFUpdater has been attempting to update chromium in the background and failing every time! When I see this I manually do it in the foreground and it works saying installation successful and then an hour or two later I notice another notification that it's done the same thing again! So I'm not sure if I'm getting some compromised versions or if there is actually this many updates concerning Chromium? 
See error log below:
Thank you for all your work and time invested! 👍

Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.chromium.chrome.zip
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:29)
	at de.marmaro.krt.ffupdater.BackgroundJob.downloadUpdateAndReturnAvailability(BackgroundJob.kt:237)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$downloadUpdateAndReturnAvailability(BackgroundJob.kt:49)
	at de.marmaro.krt.ffupdater.BackgroundJob$downloadUpdateAndReturnAvailability$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.11 (137) release |
| Device | REVVL V+ 5G (Sprout, Sprout, S98115AA1) |
| Manufacturer | T-Mobile (Wingtech) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | ubuntu, cibuild, release-keys, 1677932900000 |

**Comment by Tobi823** [comment]
> there is actually this many updates concerning Chromium?

I haven't paid attention to how often a new version of Chrome is released until now. But I am surprised - they release every two hours a new version. The reason I did not notice this is that FFUpdater only checks every eight hours for updates. 

I should limit it for the background update check. Chromium should only be automatically updated once a day because - updating Chromium twice a day has no benefits in my opinion.

But why the download failed is yet unclear to me. I will move your bug report to the corresponding ticket.
