### ISSUE TITLE
Chromium won't update 

### ISSUE THREAD

**Issue by Sammey1995** [Tobi823/ffupdater#389]
Stacktrace:
```
de.marmaro.krt.ffupdater.FFUpdaterException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:24)
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion$throwIfApkFileIsNoValidZipFile$1.invokeSuspend(ApkChecker.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8747)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@65fb231, Dispatchers.Main]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
	at java.util.zip.ZipFile.<init>(ZipFile.java:201)
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion$throwIfApkFileIsNoValidZipFile$2.invokeSuspend(ApkChecker.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Timestamp: 2023-04-03T05:06:42.958

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.12 (138) release |
| Device | SM-S918U (dm3qsqw, dm3q, kalama) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1677820386000 |

**Comment by Tobi823** [comment]
I fixed a bug in 78.0.1 that could cause data corruption if two downloads were running at the same time. I think this is the cause for your problem.

Please open a new ticket if the bug still persists.
