### ISSUE TITLE
ffupdater tries to downgrade firefox

### ISSUE THREAD

**Issue by danielleontiev** [Tobi823/ffupdater#392]
Stacktrace:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Failed to install FIREFOX_RELEASE in the background with SESSION_INSTALLER.
	at de.marmaro.krt.ffupdater.BackgroundJob.installApplication(BackgroundJob.kt:308)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$installApplication(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$installApplication$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 2015941331 is older than current 2015942699. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(SessionInstaller.kt:191)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:127)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:30)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(SessionInstaller.kt:211)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | Mi 9 SE (lineage_grus, grus, sdm710) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 3c9440f5c346, root, dev-keys, 1678296245000 |    

This is how Firefox looks like in the application (available version shown is older than installed):

<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/24596613/230747825-faef8852-9c53-44f5-b991-cd6ed952b538.png" />

</details>

**Comment by Tobi823** [comment]
I fixed a bug in 78.0.1 that could cause data corruption if two downloads were running at the same time. I think this is the cause for your problem.

Please open a new ticket if the bug still persists.
