### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by greyhemlock** [Tobi823/ffupdater#394]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_firefox_111_1_1.apk
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:29)
	at de.marmaro.krt.ffupdater.BackgroundJob.downloadUpdateAndReturnAvailability(BackgroundJob.kt:248)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$downloadUpdateAndReturnAvailability(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$downloadUpdateAndReturnAvailability$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | SM-G781U1 (r8quex, r8q, kona) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6112, dpi, release-keys, 1677229712000 |

**Comment by Tobi823** [comment]
Fixed in 78.0.1. If not, please create a new issue.
