### ISSUE TITLE
Updater tries to DOWNgrade my Firefox

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [Tobi823/ffupdater#395]
Stacktrace:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Failed to install FIREFOX_RELEASE in the background with ROOT_INSTALLER.
	at de.marmaro.krt.ffupdater.BackgroundJob.installApplication(BackgroundJob.kt:308)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$installApplication(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$installApplication$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Root command 'pm install-commit 811551323' failed. Result code is: '1', stdout: '[Failure [INSTALL_FAILED_VERSION_DOWNGRADE]]', stderr: '[]'
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller$execute$2.invokeSuspend(RootInstaller.kt:76)
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller$execute$2.invoke(RootInstaller.kt:0)
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller$execute$2.invoke(RootInstaller.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller.execute(RootInstaller.kt:73)
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller.installApp(RootInstaller.kt:69)
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller.executeInstallerSpecificLogic(RootInstaller.kt:25)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:43)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(AbstractAppInstaller.kt:15)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(AbstractAppInstaller.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | LG-H850 (h1_global_com, h1, MSM8996) |
| Manufacturer | lge (LGE) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | 95d1d6be1c19, root, dev-keys, 1676952546000 |

**Comment by Tobi823** [comment]
Does the issue still persist?

**Comment by Tobi823** [comment]
I think it is fixed now

**Comment by tmolitor-stud-tu** [comment]
Yes, I guess it is fixed. I did not experience this bug again, but since I don't know what triggered the bug, it could also just be that the firefox release numbering didn't trigger the bug again, yet.

I'll reopen the issue if I see this bug again (hopefully that never happens ;) )
