### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by mgw2013** [Tobi823/ffupdater#407]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(BackgroundJob.kt:97)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(BackgroundJob.kt:88)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invoke(BackgroundJob.kt:0)
	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invoke(BackgroundJob.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at de.marmaro.krt.ffupdater.BackgroundJob.doWork(BackgroundJob.kt:81)
	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@2f5cfbe
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | Redmi Note 4 (lineage_mido, mido, MSM8953) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | BuildMachine, zeelog, release-keys, 1681282088000 |

**Comment by Tobi823** [comment]
Should be fixed now.
