### ISSUE TITLE
Failed Chromium update Crash Report

### ISSUE THREAD

**Issue by mboom** [Tobi823/ffupdater#408]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.chromium.chrome.zip
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:29)
	at de.marmaro.krt.ffupdater.BackgroundJob.downloadUpdateAndReturnAvailability(BackgroundJob.kt:248)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$downloadUpdateAndReturnAvailability(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$downloadUpdateAndReturnAvailability$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | FP3 (lineage_FP3, FP3, FP3) |
| Manufacturer | Fairphone (Fairphone) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | 7ff400be34c2, root, release-keys, 1679279143000 |

**Comment by Tobi823** [comment]
Fixed in 78.0.1. If not, please create a new issue.
