### ISSUE TITLE
android 11 can't install update

### ISSUE THREAD

**Issue by 2aq112x35** [Tobi823/ffupdater#41]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_INSTALL (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5436)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivityForResult(Activity.java:5394)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
	at android.app.Activity.startActivity(Activity.java:5780)
	at android.app.Activity.startActivity(Activity.java:5733)
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.onNewIntentCallback(SessionInstaller.kt:23)
	at de.marmaro.krt.ffupdater.InstallActivity.onNewIntent(InstallActivity.kt:149)
	at android.app.Activity.performNewIntent(Activity.java:8163)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1410)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1423)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3769)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3781)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by Tobi823** [comment]
Which device/OS/apps/special settings are you using?

**Comment by 2aq112x35** [comment]
> Which device/OS/apps/special settings are you using?

device: Redmi K20 Pro
OS: MIUI12.5
apps: Firefox stable
special settings: no, and I opened ‘install unknown apps' permissions.

**Comment by Tobi823** [comment]
Can you try disabling the MIUI Optimization?

**Comment by 2aq112x35** [comment]
> Can you try disabling the MIUI Optimization?

omg, I disable the MIUI Optimization then OK.

**Comment by Tobi823** [comment]
But you are not the first user who has this issue.

I will add this error message for the next user :)

![Screenshot_1620397759](https://user-images.githubusercontent.com/10066140/117465022-87c55380-af51-11eb-88d5-61ccff4c0c58.png)
