### ISSUE TITLE
FF Updater bug

### ISSUE THREAD

**Issue by WellDread** [Tobi823/ffupdater#411]
(https://github.com/Tobi823/ffupdater/assets/81600815/98f321ed-0060-4d92-a7bd-3445e9dd0fb1)

Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:405)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(SessionInstaller.kt:186)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:126)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:29)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(SessionInstaller.kt:206)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1805)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.6 (132) release |
| Device | SM-G970U (beyond0qltesq, beyond0q, msmnile) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | 21DJFC17, dpi, release-keys, 1679311310000 |

**Comment by Tobi823** [comment]
I fixed a bug in 78.0.1 that could cause data corruption if two downloads were running at the same time. I think this is the cause for your problem.

Please open a new ticket if the bug still persists.
