### ISSUE TITLE
Issue when downloading Brave from ffupdater

### ISSUE THREAD

**Issue by DreamingCuttlefish** [Tobi823/ffupdater#412]
When I download and attempt to open Brave from ffupdater, I encounter the following error:

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ2A.230505.002/2023050500:user/release-keys
package: com.brave.browser:415111423
process: com.brave.browser
processUptime: 116 + 242 ms
 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.brave.browser/org.chromium.chrome.browser.firstrun.WelcomeOnboardingActivity}: java.lang.RuntimeException: Starting in 64-bit mode requires the 64-bit native library. If the device is 64-bit only, see alternatives here: https://crbug.com/1303857#c7.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.RuntimeException: Starting in 64-bit mode requires the 64-bit native library. If the device is 64-bit only, see alternatives here: https://crbug.com/1303857#c7.
	at xV.c(chromium-MonochromePublic.apk-stable-415111423:90)
	at Jh.onCreate(chromium-MonochromePublic.apk-stable-415111423:176)
	at android.app.Activity.performCreate(Activity.java:8388)
	at android.app.Activity.performCreate(Activity.java:8367)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	... 14 more
```

I am running on a Google Pixel 7 Pro with Grapheneos installed. I have tried clearing Brave's cache and it didn't help. Downloading Brave from aurorastore/google play works fine, but from ffupdater it won't work for some reason.

Please help!

**Comment by Tobi823** [comment]
Looks like FFUpdater is downloading the wrong APK file. Is the issue still present in the latest versions (78.0.0 or later)?

**Comment by DreamingCuttlefish** [comment]
> Looks like FFUpdater is downloading the wrong APK file. Is the issue still present in the latest versions (78.0.0 or later)?

Unfortunately it still happens. I just tried on 78.0.4 and when I try to open brave it says "Your device couldn't open Brave. To fix the issue, download the latest update from your app store."

**Comment by Tobi823** [comment]
Can you install and use the Brave APK from Brave's GitHub repository (https://github.com/brave/brave-browser/releases/download/v1.52.130/BraveMonoarm64.apk)? I want to rule out the possibility that the APK file is corrupted or incompatible.

**Comment by Tobi823** [comment]
Looks like Brave is publishing incorrect 64-bit versions:

> I found the problem: Brave github apks are only in 32-bit, even ones that say they're 64-bit, which the Pixel 7 doesn't support :( 
https://www.reddit.com/r/brave_browser/comments/zwqdjy/comment/jb5qss0/

**Comment by DreamingCuttlefish** [comment]
> Can you install and use the Brave APK from Brave's GitHub repository (https://github.com/brave/brave-browser/releases/download/v1.52.130/BraveMonoarm64.apk)? I want to rule out the possibility that the APK file is corrupted or incompatible.

Just tried this out and the same problem occurs. I guess it is a problem with the apk file!?

**Comment by Tobi823** [comment]
I think too.

Should I (or do you want to) create an issue at https://github.com/brave/brave-browser? Maybe the Brave developers don't know that their 64 bit APK files don't work on "64 bit only" machines.

**Comment by Tobi823** [comment]
I think this is the same problem https://github.com/brave/brave-browser/issues/28712

I will close this issue for now because only the developer of Brave can fix it.

**Comment by Rathmox** [comment]
@Tobi823 Yes, it's the same problem. I discovered it also with FFupdater
