### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by keynlotepan** [Tobi823/ffupdater#418]
Stacktrace:
```
kotlin.UninitializedPropertyAccessException: lateinit property appUpdateStatus has not been initialized
	at de.marmaro.krt.ffupdater.DownloadActivity.startInstallationProcess(DownloadActivity.kt:216)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startInstallationProcess(DownloadActivity.kt:61)
	at de.marmaro.krt.ffupdater.DownloadActivity$startInstallationProcess$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1deb53, Dispatchers.Main]
Timestamp: 2023-06-10T13:43:22.757

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | Mi A1 (lineage_tissot, tissot, MSM8953) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | lineageos-buildkite, buildkite-agent, release-keys, 1586238968000 |

**Comment by Tobi823** [comment]
Fixed in version 78.0.4
