### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [Tobi823/ffupdater#419]
Notification shown in a dress bar that a new update was available, clicked on notification and recieved error message

Stacktrace:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Failed to install FENNEC_FDROID in the background with SESSION_INSTALLER.
	at de.marmaro.krt.ffupdater.BackgroundJob.installApplication(BackgroundJob.kt:308)
	at de.marmaro.krt.ffupdater.BackgroundJob.internalDoWork(BackgroundJob.kt:146)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$internalDoWork(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$internalDoWork$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Can't validate the signature of the APK file.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:32)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(AbstractAppInstaller.kt:15)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(AbstractAppInstaller.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Can't extract the signature from APK file '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_114_0_0.apk', length: 360448, absolutePath: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_114_0_0.apk, isFile: true
	at de.marmaro.krt.ffupdater.security.PackageManagerUtil.getPackageArchiveInfo(PackageManagerUtil.kt:48)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invokeSuspend(FingerprintValidator.kt:29)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(FingerprintValidator.kt:0)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(FingerprintValidator.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(FingerprintValidator.kt:28)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:29)
	... 10 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | SM-S515DL (a51tfn, a51, exynos9611) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DK7906, dpi, release-keys, 1680613931000 |

**Comment by Tobi823** [comment]
I fixed a bug in 78.0.1 that could cause data corruption if two downloads were running at the same time. I think this is the cause for your problem.

Please open a new ticket if the bug still persists.
