### ISSUE TITLE
BRAVE_NIGHTLY update older than current version

### ISSUE THREAD

**Issue by lu-ckystars** [Tobi823/ffupdater#426]
# not really sure how i did this

Stacktrace:
```
java.lang.RuntimeException: Failed to install BRAVE_NIGHTLY in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:391)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:61)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Shizuku command 'pm install-commit 1412268256' failed. Result code is: '1', stdout: 'Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 415500221 is older than current 415507321]
', stderr: ''
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller$execute$2.invokeSuspend(ShizukuInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller$execute$2.invoke(ShizukuInstaller.kt:0)
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller$execute$2.invoke(ShizukuInstaller.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller.execute(ShizukuInstaller.kt:85)
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller.installApp(ShizukuInstaller.kt:81)
	at de.marmaro.krt.ffupdater.installer.impl.ShizukuInstaller.executeInstallerSpecificLogic(ShizukuInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(AbstractAppInstaller.kt:43)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(AbstractAppInstaller.kt:15)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(AbstractAppInstaller.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | Pixel 4a (sunfish, sunfish, sunfish) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | calyxos-ic-dev, cdesai, release-keys, 1686823197000 |

**Comment by adeptnerd** [comment]
I got the same error! ⚠️ 

Stacktrace:
```
java.lang.RuntimeException: Failed to install BRAVE_BETA in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:391)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:61)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 415407821 is older than current 415507622. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(SessionInstaller.kt:191)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:127)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:30)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(SessionInstaller.kt:211)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1918)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | SM-M536B (m53xnnxx, m53x, m53x) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DKGA08, dpi, release-keys, 1685687545000 |

**Comment by lu-ckystars** [comment]
I also tried switching from nightly to beta and got the same error. I even went to braves repo and tried installing it from there through App Manager and also got the error. it's working for regular brave now though so try that..?

**Comment by adeptnerd** [comment]
Now the error is gone in version `77.7.15` which was released yesterday!
