### ISSUE TITLE
crash report mcwimpy #3

### ISSUE THREAD

**Issue by mcwimpy** [Tobi823/ffupdater#429]
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:391)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:61)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(SessionInstaller.kt:191)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:127)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:30)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(SessionInstaller.kt:211)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.14 (140) release |
| Device | SM-A505FN (a50eea, a50, exynos9610) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | VPDJR204, dpi, release-keys, 1677547753000 |

**Comment by Tobi823** [comment]
I fixed a bug in 78.0.1 that could cause data corruption if two downloads were running at the same time. I think this is the cause for your problem.

Please open a new ticket if the bug still persists.
