### ISSUE TITLE
Unsuccessful Download if not permanent in foreground 

### ISSUE THREAD

**Issue by Andreas-ddl** [Tobi823/ffupdater#433]
Android 13 Galaxy S10Lite 

Download unsuccessful if screen switched off

Please copy and paste the error message with the stacktrace here:

Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/com_brave_browser_1_52_130.apk
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(Unknown Source:95)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(Unknown Source:622)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.0.1 (143) release |
| Device | SM-G770F (r5qnaeea, r5q, msmnile) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DKG901, dpi, release-keys, 1687154238000 |         

Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/com_brave_browser_1_52_130.apk
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(Unknown Source:95)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(Unknown Source:622)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.0.1 (143) release |
| Device | SM-G770F (r5qnaeea, r5q, msmnile) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |

de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/com_brave_browser_1_52_130.apk
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(Unknown Source:95)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(Unknown Source:622)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Tobi823** [comment]
Fixed in the lastest version 78.0.2. If not please create a new issue.

**Comment by Andreas-ddl** [comment]
Hallo,
die letzte Version von github.com meldet sich als ...6 er Version. Irgendetwas ist da schief gegangen.

Grüße

Andreas Schmidt

**Comment by Tobi823** [comment]
@Andreas-ddl mir ist ein Fehler unterlaufen, den ich gerade gefixt habe. 

Ich habe vergessen, Gradle in Android Studio zu aktualisieren. Dadurch wurde nicht die neuste APK-Datei gebaut, sodass mein Release-Skript eine alte APK-Datei auf Github hochgeladen hat.
