### ISSUE TITLE
Background download of Chromium update failed

### ISSUE THREAD

**Issue by yogi-lo** [Tobi823/ffupdater#436]
**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.chromium.chrome.zip
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfDownloadedFileHasDifferentSize(ApkChecker.kt:29)
	at de.marmaro.krt.ffupdater.BackgroundJob.downloadUpdateAndReturnAvailability(BackgroundJob.kt:248)
	at de.marmaro.krt.ffupdater.BackgroundJob.access$downloadUpdateAndReturnAvailability(BackgroundJob.kt:52)
	at de.marmaro.krt.ffupdater.BackgroundJob$downloadUpdateAndReturnAvailability$1.invokeSuspend(BackgroundJob.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Tobi823** [comment]
Which version are you using? 78.0.3, 78.0.2, 78.0.1, 78.0.0?

**Comment by Tobi823** [comment]
I can reproduce the error in version 78.0.1 and that in later version (e.g. 78.0.6) the bug is fixed

**Comment by Tobi823** [comment]
The latest version should be soon available on F-Droid

**Comment by yogi-lo** [comment]
version 117.0.5893.0
????

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by yogi-lo** [comment]
I'm using Ff updater version

version 78.0.5

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Tobi823** [comment]
Has the error occurred again with FFUpdater 78.0.5?

**Comment by yogi-lo** [comment]
I just updated and it worked 😀

Thank you 🙌

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
