### ISSUE TITLE
FFUpdater crashing on load

### ISSUE THREAD

**Issue by th0mcat** [Tobi823/ffupdater#437]
**Describe the bug**
FFUpdater crashes when I try to open the app

**To Reproduce**
1. Open the app

**Expected behavior**
Not to crash upon opening the app

**Error message from FFUpdater**
```
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonObject com.google.gson.JsonElement.getAsJsonObject()' on a null object reference
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.findChainOfTrustJson(Unknown Source:172)
	at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$findChainOfTrustJson$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b071aa9, Dispatchers.Main]
Timestamp: 2023-07-13T13:51:46.318
```

Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.0.1 (143) release |
| Device | SM-T970 (gts7xlwifixx, gts7xlwifi, kona) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | VPDJR1010, dpi, release-keys, 1681887240000 |

**Comment by Tobi823** [comment]
Quick fix: Delete the cache + storage of FFUpdater

The real fix is already published in version 78.0.2 - but F-Droid takes some time to distribute new versions.
