### ISSUE TITLE
App crash and unable to update Firefox Beta

### ISSUE THREAD

**Issue by Gontier-Julien** [Tobi823/ffupdater#44]
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException: fail to check FIREFOX_BETA for updates
	at de.marmaro.krt.ffupdater.MainActivity$checkForAppUpdate$1.invokeSuspend(MainActivity.kt:204)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxBeta.updateCheckWithoutCaching(FirefoxBeta.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
	... 6 more

**Comment by briannalee** [comment]
Similar error, FF beta is the only  installed browser. "Error" is reported under Installed Version of FF Beta, available version # ok. Tried restart, clear cache/storage, uninstall reinstall of FF updater. Will try uninstall/reinstall once I have a chance to copy my about:config

java.lang.NullPointerException at MozillaCiLogConsumer.kt:28
java.lang.NullPointerException

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxBeta.updateCheckWithoutCaching(FirefoxBeta.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


Android Version: 30
Device Manufacturer: motorola
Device Model: moto g power

**Comment by Gontier-Julien** [comment]
I've done the same, no change at all.
I've even downgraded some version, no change.
Idk if this is an api issue or something because the endpoint to download it is still there.

**Comment by Tobi823** [comment]
It was an API issue. The bug is now fixed and the fixed version should be soon available on F-Droid.

**Comment by Gontier-Julien** [comment]
Thank you for the quick fix!

**Comment by Gontier-Julien** [comment]
The update is now on F-Droid and everything is working, closing the issue.
