### ISSUE TITLE
Crash when updating Kiwi Browser

### ISSUE THREAD

**Issue by goodevilgenius** [Tobi823/ffupdater#441]
**Describe the bug**
App crashed when updating Kiwi to version from earlier today.

**To Reproduce**
1. Update Kiwi Browser to must recent version
5. No update

**Expected behavior**
Update should happen without error.

**Error message from FFUpdater**
Stacktrace:
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.true flg=0x10 pkg=de.marmaro.krt.ffupdater (has extras) } in de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$2$1@77f58b3
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1444)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createConfirmInstallationIntent(SessionInstaller.kt:204)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.requestInstallationPermission(SessionInstaller.kt:188)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(SessionInstaller.kt:127)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(SessionInstaller.kt:32)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$2$1.onReceive(SessionInstaller.kt:237)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1434)
	... 8 more

--------- beginning of main
07-17 21:40:50.213 D/FFUpdater( 4565): startInstallationProcess(): Start process for KIWI.
07-17 21:40:50.216 D/FFUpdater( 4565): findAppUpdateStatus(): Search for latest KIWI update.
07-17 21:40:50.496 I/FFUpdater( 4565): findAppUpdateStatus(): Found KIWI 5579794346 (280ms).
07-17 21:40:50.500 D/FFUpdater( 4565): DownloadActivity: Use APK cache of KIWI.
07-17 21:40:50.501 D/FFUpdater( 4565): Install app KIWI.
--------- beginning of system
--------- beginning of crash
07-17 21:41:32.478 I/FFUpdater( 4632): InstalledAppsCache: Update cache of installed apps.
07-17 21:41:32.490 I/FFUpdater( 4632): InstalledAppsCache: Update cache of installed apps.
07-17 21:41:32.520 I/FFUpdater( 4632): InstalledAppsCache: Cache was updated.
07-17 21:41:32.823 I/FFUpdater( 4632): InstalledAppsCache: Cache was updated.
07-17 21:41:32.823 I/FFUpdater( 4632): InstalledAppsCache: Update cache of installed apps.
07-17 21:41:32.836 I/FFUpdater( 4632): InstalledAppsCache: Cache was updated.
07-17 21:41:32.836 D/FFUpdater( 4632): findAppUpdateStatus(): Search for latest KIWI update.
07-17 21:41:32.903 I/FFUpdater( 4632): findAppUpdateStatus(): Found KIWI 5579794346 (67ms).
07-17 21:41:32.904 D/FFUpdater( 4632): findAppUpdateStatus(): Search for latest ORBOT update.
07-17 21:41:32.963 I/FFUpdater( 4632): findAppUpdateStatus(): Found ORBOT 17.0.0-RC-1-tor.0.4.7.11 (59ms).
07-17 21:41:37.665 D/FFUpdater( 4632): findAppUpdateStatus(): Search for latest KIWI update.
07-17 21:41:37.671 I/FFUpdater( 4632): findAppUpdateStatus(): Found KIWI 5579794346 (6ms).
07-17 21:41:37.671 D/FFUpdater( 4632): installOrDownloadApp(): Start DownloadActivity to install or update KIWI.
07-17 21:41:37.792 D/FFUpdater( 4632): startInstallationProcess(): Start process for KIWI.
07-17 21:41:37.794 D/FFUpdater( 4632): findAppUpdateStatus(): Search for latest KIWI update.
07-17 21:41:37.825 I/FFUpdater( 4632): findAppUpdateStatus(): Found KIWI 5579794346 (30ms).
07-17 21:41:37.828 D/FFUpdater( 4632): DownloadActivity: Use APK cache of KIWI.
07-17 21:41:37.830 D/FFUpdater( 4632): Install app KIWI.

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.0.5 (147) release |
| Device | KFTRWI (trona, trona, trona) |
| Manufacturer | Amazon (Amazon) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | i3-ri-14-use1a-b-16-04-fos-114, build, amz-p,release-keys, 1684880586000 |

**Comment by goodevilgenius** [comment]
Fixed by latest version. Thanks for the quick fix!
