### ISSUE TITLE
The application is closed

### ISSUE THREAD

**Issue by PsykoRider** [Tobi823/ffupdater#443]
**Describe the bug**
The app closes after downloading an update and trying to install the app. My device is a Realme GT Neo 3

Stacktrace:
```
java.lang.IllegalStateException: Too many active sessions for UID 10403
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3048)
	at android.os.Parcel.createException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2949)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:462)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:518)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$install$2.invokeSuspend(SessionInstaller.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8908282, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:881)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:635)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:225)
	at android.os.Binder.execTransactInternal(Binder.java:1326)
	at android.os.Binder.execTransact(Binder.java:1268)

--------- beginning of main
07-18 14:03:26.872 I/FFUpdater(28509): InstalledAppsCache: Update cache of installed apps.
07-18 14:03:26.908 I/FFUpdater(28509): InstalledAppsCache: Cache was updated.
07-18 14:03:27.203 I/FFUpdater(28509): InstalledAppsCache: Update cache of installed apps.
07-18 14:03:27.215 I/FFUpdater(28509): InstalledAppsCache: Cache was updated.
07-18 14:03:27.222 I/FFUpdater(28509): InstalledAppsCache: Update cache of installed apps.
07-18 14:03:27.333 I/FFUpdater(28509): InstalledAppsCache: Cache was updated.
07-18 14:03:27.333 I/FFUpdater(28509): InstalledAppsCache: Update cache of installed apps.
07-18 14:03:27.338 I/FFUpdater(28509): InstalledAppsCache: Cache was updated.
07-18 14:03:27.339 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest BRAVE update.
07-18 14:03:29.676 I/FFUpdater(28509): Execute real network request: https://api.github.com/repos/brave/brave-browser/releases?per_page=40&page=2
07-18 14:03:29.937 I/FFUpdater(28509): findAppUpdateStatus(): Found BRAVE 1.52.130 (2598ms).
07-18 14:03:29.938 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest DUCKDUCKGO_ANDROID update.
07-18 14:03:29.944 I/FFUpdater(28509): findAppUpdateStatus(): Found DUCKDUCKGO_ANDROID 5.164.0 (6ms).
07-18 14:03:29.945 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest FFUPDATER update.
07-18 14:03:29.970 I/FFUpdater(28509): findAppUpdateStatus(): Found FFUPDATER 78.0.6 (25ms).
07-18 14:03:29.970 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest FIREFOX_BETA update.
07-18 14:03:29.979 I/FFUpdater(28509): findAppUpdateStatus(): Found FIREFOX_BETA 116.0b6 (9ms).
07-18 14:03:29.979 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest MULL_FROM_REPO update.
07-18 14:03:29.991 I/FFUpdater(28509): findAppUpdateStatus(): Found MULL_FROM_REPO 115.2.0 (12ms).
07-18 14:03:29.991 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest ORBOT update.
07-18 14:03:30.007 I/FFUpdater(28509): findAppUpdateStatus(): Found ORBOT 17.0.0-RC-1-tor.0.4.7.11 (16ms).
07-18 14:03:31.578 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest DUCKDUCKGO_ANDROID update.
07-18 14:03:31.592 I/FFUpdater(28509): findAppUpdateStatus(): Found DUCKDUCKGO_ANDROID 5.164.0 (14ms).
07-18 14:03:31.593 D/FFUpdater(28509): installOrDownloadApp(): Start DownloadActivity to install or update DUCKDUCKGO_ANDROID.
07-18 14:03:31.674 D/FFUpdater(28509): startInstallationProcess(): Start process for DUCKDUCKGO_ANDROID.
07-18 14:03:31.676 D/FFUpdater(28509): findAppUpdateStatus(): Search for latest DUCKDUCKGO_ANDROID update.
07-18 14:03:31.690 I/FFUpdater(28509): findAppUpdateStatus(): Found DUCKDUCKGO_ANDROID 5.164.0 (14ms).
07-18 14:03:31.691 D/FFUpdater(28509): DownloadActivity: Use APK cache of DUCKDUCKGO_ANDROID.
07-18 14:03:31.692 D/FFUpdater(28509): Install app DUCKDUCKGO_ANDROID.

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.0.6 (148) release |
| Device | RMX3561 (RMX3561, RED8BEL1, k6895v1_64) |
| Manufacturer | realme (realme) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | dg02-pool03-kvm152, root, release-keys, 1686723267000 |

**Comment by Tobi823** [comment]
I think I found the source code which throws the "too many active sessions" exception https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/pm/PackageInstallerService.java#814

I will look into the documentation if I close all session which I open

**Comment by Tobi823** [comment]
@PsykoRider Reboot your phone. This helped https://gitlab.com/fdroid/privileged-extension/-/issues/82

**Comment by Tobi823** [comment]
In the next FFUpdater release I will make sure that all open sessions are closed
