### ISSUE TITLE
App crash: downloading Brave

### ISSUE THREAD

**Issue by myuseraccount** [Tobi823/ffupdater#45]
I just installed the newest version of the app from F-Droid, and then tried upgrading Brave. Stack trace below.

Device: rooted Android 8, LG G6 (H472)

kotlin.io.FileAlreadyExistsException: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/BRAVE__2021_06_02__416095783.apk -> /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/cache/Download/BRAVE__2021_06_02__416095783.apk: The destination file already exists.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:224)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at de.marmaro.krt.ffupdater.download.DownloadedApkCache.copyFileToCache(DownloadedApkCache.kt:20)
	at de.marmaro.krt.ffupdater.InstallActivity$State$8.invokeSuspend(InstallActivity.kt:283)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by Tobi823** [comment]
Can you delete the cache of the app? (On my phone: (Global) Settings > Apps & notifications > Click on "FFUpdater" > Storage & cache > Clear cache)

**Comment by myuseraccount** [comment]
I haven't tried that, but it makes sense. I think it automatically downloaded the update in the background, but the UI hadn't updated to reflect that, so it gave me a download button instead of install. Next time I opened the app, it had the button to install the update, and worked fine.

This might have something to do with having upgraded FFUpdater recently: the previous version downloaded a Brave update, but the new version didn't see it right away when starting fresh after the upgrade?

June 3, 2021 2:51 AM, "Tobias Hellmann" ***@***.*** ***@***.******@***.***>)> wrote:
	Can you delete the cache of the app? (On my phone: (Global) Settings > Apps & notifications > Click on "FFUpdater" > Storage & cache > Clear cache)
