### ISSUE TITLE
Can't check the updates for Tor Browser

### ISSUE THREAD

**Issue by SpiritOTHawk** [Tobi823/ffupdater#455]
**Describe the bug**
Can't check the updates for Tor Browser

**Expected behavior**
Tor Browser will be checked for the updates

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here: 
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for TOR_BROWSER.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:34)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://www.torproject.org/download/ failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.NoRouteToHostException: Host unreachable
	at libcore.io.IoBridge.connect(IoBridge.java:137)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
		at java.net.SocketInputStream.read(SocketInputStream.java:176)
		at java.net.SocketInputStream.read(SocketInputStream.java:144)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
		at java.net.SocketInputStream.read(SocketInputStream.java:176)
		at java.net.SocketInputStream.read(SocketInputStream.java:144)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for TOR_BROWSER.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:34)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://www.torproject.org/download/ failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.NoRouteToHostException: Host unreachable
	at libcore.io.IoBridge.connect(IoBridge.java:137)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
		at java.net.SocketInputStream.read(SocketInputStream.java:176)
		at java.net.SocketInputStream.read(SocketInputStream.java:144)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
	Suppressed: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
		at java.net.SocketInputStream.read(SocketInputStream.java:176)
		at java.net.SocketInputStream.read(SocketInputStream.java:144)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
		at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 17 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more
	Suppressed: java.net.NoRouteToHostException: Host unreachable
		... 27 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.1 (150) release F-Droid/other |
| Device | SM-A405FM (a40ser, a40, exynos7904) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | VPHLR216, dpi, release-keys, 1680078129000 |

**Comment by Tobi823** [comment]
Looks like a temporary network error (e.g. phone lost internet connection).

**Comment by Application-maker** [comment]
Same thing for me, tried many times, *still* doesn't work

**Comment by Tobi823** [comment]
Can you open https://www.torproject.org/download/#android on your phone?

**Comment by SpiritOTHawk** [comment]
> Can you open https://www.torproject.org/download/#android and https://dist.torproject.org/torbrowser/ on your phone?

1: No
2: Yes

**Comment by Application-maker** [comment]
> > Can you open https://www.torproject.org/download/#android and https://dist.torproject.org/torbrowser/ on your phone?
> 
> 1: No

What country do you live in?

**Comment by Application-maker** [comment]
> > Can you open https://www.torproject.org/download/#android and https://dist.torproject.org/torbrowser/ on your phone?
> 
> 1: No 2: Yes

I found out that you live in Russian Federation, according to [this article](https://ntc.party/t/ooni-reports-of-tor-blocking-in-certain-isps-since-2021-12-01/1477) Russian government is blocking Tor website, so when ffupdater tries to check for updates it gives an error.

**Comment by Tobi823** [comment]
I'm not an expert on the current situation in Russia but you can try to enable a different DNS server.
![1](https://github.c
![2](https://github.com/Tobi823/ffupdater/assets/10066140/da263cbc-b4a3-4044-8af9-d0091661a26d)
om/Tobi823/ffupdater/assets/10066140/dcd33c54-f54a-4ce8-bee2-9989d0bb9512)

**Comment by Tobi823** [comment]
![2](https://github.com/Tobi823/ffupdater/assets/10066140/bcc4394e-e558-4cfd-a05f-1fa5e42f1c7d)

**Comment by Tobi823** [comment]
But I have an idea. If https://www.torproject.org/download/#android is blocked and https://dist.torproject.org/torbrowser/ not, I could use only dist.torproject.org to check for updates. #464
