### ISSUE TITLE
Shizuku installation error

### ISSUE THREAD

**Issue by JW10234** [Tobi823/ffupdater#456]
**Describe the bug**
In the two latest versions of ffupdater, when I tried to update Firefox, it gave me the error INSTALL_FAILED_ALREADY_EXISTS attempt to reinstall the package without first uninstalling

**To Reproduce**
1. Download an old version of a browser and install it using a file manager.
2. Try to update the browser with ffupdater using the Shizuku installer.

When I used version 78.0.6, it was able to update the browser just fine.

**Expected behavior**
Everything updates flawlessly, like in version 78.0.6.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install org.mozilla.firefox without first uninstalling.. The installation failed because it conflicts (or is inconsistent with) with another package already installed on the device.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	... 7 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install org.mozilla.firefox without first uninstalling.. The installation failed because it conflicts (or is inconsistent with) with another package already installed on the device.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	... 7 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.1 (150) release F-Droid/other |
| Device | WayDroid x86_64 Device (lineage_waydroid_x86_64, waydroid_x86_64, unknown) |
| Manufacturer | waydroid (Waydroid) | 
| Supported ABIs | x86_64, x86 |
| Android version | 11 (SDK: 30) |
| OS | fl-a-w-1, jenkins, test-keys, 1690607849000 |

**Comment by marcdw1289** [comment]
Been having the same issue when trying to update Kiwi.
Also using Shizuku but never thought to check further.

**Comment by Tobi823** [comment]
I have to look into but I suspect that:

- FFUpdater thinks Firefox Release needs to be updated due to bug #453
- Installing the same version with Shizuku always throws a `Attempt to re-install org.mozilla.firefox without first uninstalling.` error

**Comment by Tobi823** [comment]
And the problem with the app Kiwi is, that it is likely that FFUpdater also thinks that the app needs to be updated although the latest version is already installed

**Comment by Tobi823** [comment]
TODO for me:

- fix #453
- ignore the "Attempt to re-install org.mozilla.firefox without first uninstalling." errors when using Shizuku

**Comment by oiao** [comment]
Same issue for other browser as well here: Tor, Mulch & Firefox Nightly

**Comment by JW10234** [comment]
I think the problem might be the new shizuku installer, which was implemented in version 78.1.0.

**Comment by Tobi823** [comment]
@JW10234 Just be sure...

Do you try to update Firefox or do you install the same version again?

Second question ... does the Shizuku installer of Aurora Store work for you? I used its source code as a base for my implementation - but maybe I forgot to copy+paste some important code lines

**Comment by JW10234** [comment]
@Tobi823 I downloaded an old version from GitHub and upgraded Firefox. Aurora Store's Shizuku installer worked for installing new apps, but not for updates (It gave me the same error).

**Comment by Tobi823** [comment]
Thanks for the info. I will look into it. Maybe I forgot to set some special values.

**Comment by theimpulson** [comment]
Encountered this repo while I was looking for related issues. There is actually a flag to replace the app if it already exists which I have gone with (for now) assuming this is how it's supposed to be done.

https://gitlab.com/AuroraOSS/AuroraStore/-/commit/213bf98ffb909cf08688de8b099ff288485cba03

**Comment by Xynonners** [comment]
would be cool if this was fixed like in Aurora Store 👍

**Comment by Tobi823** [comment]
@theimpulson thanks for your help. It saved me a lot of time
