### ISSUE TITLE
Error updating Tor Browser

### ISSUE THREAD

**Issue by CorMelse** [Tobi823/ffupdater#458]
**Describe the bug**
While downloading a new Tor version,  FFupdater halted at 24% and after some time crashed with the reports below.

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://dist.torproject.org/torbrowser/12.5.2/tor-browser-12.5.2-android-aarch64-multi.apk failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$deferred$1.invokeSuspend(FileDownloader.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:150)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:339)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:376)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at de.marmaro.krt.ffupdater.network.file.ProgressInterceptorResponseBody$trackTransmittedBytes$1.read(ProgressInterceptorResponseBody.kt:42)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.downloadFile(FileDownloader.kt:164)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$downloadFile(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$2.invokeSuspend(FileDownloader.kt:0)
	... 8 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	... 24 more

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://dist.torproject.org/torbrowser/12.5.2/tor-browser-12.5.2-android-aarch64-multi.apk failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$deferred$1.invokeSuspend(FileDownloader.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:150)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:339)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:376)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at de.marmaro.krt.ffupdater.network.file.ProgressInterceptorResponseBody$trackTransmittedBytes$1.read(ProgressInterceptorResponseBody.kt:42)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.downloadFile(FileDownloader.kt:164)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$downloadFile(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$2.invokeSuspend(FileDownloader.kt:0)
	... 8 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	... 24 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.1 (150) release F-Droid/other |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6907, dpi, release-keys, 1687335348000 |

**Comment by Tobi823** [comment]
Can you open https://www.torproject.org/download/#android and https://dist.torproject.org/torbrowser/ on your phone? I want to make sure that your internet service provider is not blocking Tor.

**Comment by CorMelse** [comment]
Both are working on my S21 android with Firefox. 
I can download from the sites

**Comment by Tobi823** [comment]
Good to know.

**Comment by Tobi823** [comment]
I guess that the error (you have posted) was just a temporary network problem.

**Comment by CorMelse** [comment]
Could be indeed.
Then you can close this one.
Whenever i get another i will report it ofcourse.
