### ISSUE TITLE
App Crashes whenever I pull down to refresh

### ISSUE THREAD

**Issue by Napster8** [Tobi823/ffupdater#46]
`
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException at MainActivity.kt:204
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException

de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException: fail to check FIREFOX_BETA for updates
 at de.marmaro.krt.ffupdater.MainActivity$checkForAppUpdate$1.invokeSuspend(MainActivity.kt:204)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
 at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
 at de.marmaro.krt.ffupdater.app.impl.FirefoxBeta.updateCheckWithoutCaching(FirefoxBeta.kt:39)
 at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
 ... 6 more

Android Version: 28
Device Manufacturer: HUAWEI
Device Model: BND-AL10
`

**Comment by Tobi823** [comment]
I think it's this bug: https://github.com/Tobi823/ffupdater/issues/44

I already fixed it and the fix will be soon available on F-Droid.
