### ISSUE TITLE
Everyday crash during updates.

### ISSUE THREAD

**Issue by Cheechoz** [Tobi823/ffupdater#474]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Stacktrace:
```
java.lang.SecurityException: Caller has no access to session 1707712765
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:530)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:582)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.abandonSession(SessionInstaller.kt:205)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.installApkFile$suspendImpl(SessionInstaller.kt:55)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$installApkFile$1.invokeSuspend(SessionInstaller.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@db49a45, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.abandonSession(PackageInstallerService.java:1127)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:265)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)


```
Logs:
```
java.lang.SecurityException: Caller has no access to session 1707712765
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:530)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:582)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.abandonSession(SessionInstaller.kt:205)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.installApkFile$suspendImpl(SessionInstaller.kt:55)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$installApkFile$1.invokeSuspend(SessionInstaller.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@db49a45, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.abandonSession(PackageInstallerService.java:1127)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:265)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)


```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.2 (151) release Github |
| Device | SM-S908U (b0qsqw, b0q, taro) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6620, dpi, release-keys, 1687518029000 |

**Comment by Tobi823** [comment]
Is now fixed. The fix will be part of the next release.
