### ISSUE TITLE
ffupdater keeps crashing on checking 

### ISSUE THREAD

**Issue by ffu-user** [Tobi823/ffupdater#477]
As requested by app crash message, here it is following description of behaviour:

- app settings only accessible when phone in flight modus, otherwise app crashes too fast to enter it;
- in flight modus changed background / foreground settings, Check update on metered network 

if Foreground: Update checks on metered: app crash and crash message

if no Foreground check, Background only, unmetered (but with no unmetered connection possible, so just checked without connecting) : no crash 

The crash message:

Stacktrace:
```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-libart.jar)
 at kotlin.internal.jdk8.JDK8PlatformImplementations$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
 at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:45)
 at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:372)
 at kotlin.text.jdk8.RegexExtensionsJDK8Kt.get(RegexExtensions.kt:35)
 at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.findTaskId(MozillaCiJsonConsumer.kt:28)
 at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$findTaskId$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5477)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3cb2914, Dispatchers.Main]

```
Logs:
```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-libart.jar)
 at kotlin.internal.jdk8.JDK8PlatformImplementations$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
 at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:45)
 at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:372)
 at kotlin.text.jdk8.RegexExtensionsJDK8Kt.get(RegexExtensions.kt:35)
 at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer.findTaskId(MozillaCiJsonConsumer.kt:28)
 at de.marmaro.krt.ffupdater.network.mozillaci.MozillaCiJsonConsumer$findTaskId$1.invokeSuspend(MozillaCiJsonConsumer.kt:0)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5477)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3cb2914, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.2 (151) release Github |
| Device | 6039K (6039K, idol347, msm8916) |
| Manufacturer | TCL (TCL) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 6.0.1 (SDK: 23) |
| OS | 50493-2600, sl_nb_zpxiang, release-keys, 1474864846000 |         

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by Tobi823** [comment]
I can reproduce this error
