### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by r0dzilla** [Tobi823/ffupdater#478]
**notification**
App crashed

**To Reproduce**
1. My phone was on the desk and I saw the notification. Maybe it was updating in the background

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Stacktrace:
```
java.lang.SecurityException: Caller has no access to session 2141304716
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:511)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:581)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.abandonSession(SessionInstaller.kt:205)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.installApkFile$suspendImpl(SessionInstaller.kt:55)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$installApkFile$1.invokeSuspend(SessionInstaller.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1033aa0, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.abandonSession(PackageInstallerService.java:928)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:257)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)


```
Logs:
```
java.lang.SecurityException: Caller has no access to session 2141304716
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:511)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:581)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.abandonSession(SessionInstaller.kt:205)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.installApkFile$suspendImpl(SessionInstaller.kt:55)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$installApkFile$1.invokeSuspend(SessionInstaller.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1033aa0, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.abandonSession(PackageInstallerService.java:928)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:257)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)


```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.2 (151) release F-Droid/other |
| Device | Pixel 5 (redfin, redfin, redfin) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | calyxos-ic-dev, cdesai, release-keys, 1690402623000 |

**Comment by Tobi823** [comment]
I will publish the fix for this issue today.
