### ISSUE TITLE
Update Failed 

### ISSUE THREAD

**Issue by bantheadmin** [Tobi823/ffupdater#488]
**Describe the bug**
Automatic and manual update fail (root, Firefox & FFocus 116.3.0 -> 117.0.0)

**To Reproduce**
Install through app automatically or manually, including through notification

**Expected behavior**
Successful install

**Error message from FFUpdater**

Stacktrace:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Root command '"pm install-commit 216913052' failed. Result code: -1. Stdout: '[]'. Stderr: '[]'.
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller$execute$2.invokeSuspend(RootInstaller.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
Logs:
```
de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Root command '"pm install-commit 216913052' failed. Result code: -1. Stdout: '[]'. Stderr: '[]'.
	at de.marmaro.krt.ffupdater.installer.impl.RootInstaller$execute$2.invokeSuspend(RootInstaller.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.3 (152) release F-Droid/other |
| Device | M2102J20SG (lineage_vayu, vayu, msmnile) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 32) |
| OS | ed7505b9fd1e, root, release-keys, 1688719255000 |

**Comment by Tobi823** [comment]
Duplicated of #462
