### ISSUE TITLE
MC wimpy kid at heart ❤️ - new 23-09-05

### ISSUE THREAD

**Issue by mcwimpy** [Tobi823/ffupdater#489]
**Describe the bug**
Trying to install Firefox 

**To Reproduce**
1. Go to updates
2. Click on red arrow

**Expected behavior**
Update Firefox

**Error message from FFUpdater**
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: System failed to install the package because of system issues. ResultCode: 1, INSTALL_RESULT: -110
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.createInstallationFailedException(IntentInstaller.kt:53)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.access$createInstallationFailedException(IntentInstaller.kt:24)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:39)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:34)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate$lambda$0(IntentInstaller.kt:61)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.$r8$lambda$hiOEnwbF_xxJLT0E2s2YRHjijM0(IntentInstaller.kt:0)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:8551)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5501)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 6 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: System failed to install the package because of system issues. ResultCode: 1, INSTALL_RESULT: -110
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.createInstallationFailedException(IntentInstaller.kt:53)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.access$createInstallationFailedException(IntentInstaller.kt:24)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:39)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:34)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate$lambda$0(IntentInstaller.kt:61)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.$r8$lambda$hiOEnwbF_xxJLT0E2s2YRHjijM0(IntentInstaller.kt:0)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:8551)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5501)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 6 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.3 (152) release F-Droid/other |
| Device | M2007J20CG (surya_id, surya, surya) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-3f0fp, builder, release-keys, 1678955024000 |

**Comment by Tobi823** [comment]
Which app are you trying to install?

**Comment by Tobi823** [comment]
Nevermind, Firefox :)

**Comment by Tobi823** [comment]
Can you try installing Firefox directly from the Github APK file? Go to https://github.com/mozilla-mobile/firefox-android/releases/download/fenix-v118.1.0/fenix-118.1.0-arm64-v8a.apk , download the APK file and try to install it with a file manager or something else.

**Comment by Tobi823** [comment]
Oh ich sehe, dass du auch Deutsch kannst :)

Ich bin leider am Ende meiner Möglichkeiten. Die Fehlercodes von Xiaomi sind nicht dokumentiert, sodass ich nicht nachschlagen kann, was -110 bedeutet.

Daher bin ich auf deine Mithilfe angewiesen

**Comment by mcwimpy** [comment]
Oh sorry, ich habe das erst jetzt gesehen. Ist das noch aktuell, was kann ich machen?

**Comment by Tobi823** [comment]
Wenn sich das Problem mit der Firefox-Installation gelöst hat, dann hat sich dieses Ticker erledigt
