### ISSUE TITLE
App crashed upon boot

### ISSUE THREAD

**Issue by latacter2** [Tobi823/ffupdater#494]
**Describe the bug**
App quits immediately upon boot.
NOTE: this happened after last update & continues after today's update

**To Reproduce**
1. click on app icon
2. App begins to load
3. App quits
4. Error msg

**Expected behavior**

**Error message from FFUpdater**
Stacktrace:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a319c90, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a319c90, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.5 (154) release F-Droid/other |
| Device | BE2026 (OnePlusN10, OnePlusN10, lito) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | cndgdlbpdu00-140-22, OnePlus, release-keys, 1688541487000 |         
Please copy and paste the error message with the stacktrace and error log here:

**Comment by murtezayesil** [comment]
**Describe the bug**
App crashes while checking updates for Fennec Browser which was installed through F-Droid rather than FFUpdater.

**To Reproduce**
1. click on app icon
2. App begins to load
3. App quits
4. Error msg

**Expected behavior**
Without crashing mention that Fennec Browser was downloaded from outside FFUpdater, therefore it cannot be updated using FFUpdater. Similar to how FFUpdater lists itself as downloaded from outside source, thus cannot update itself.

**Error message from FFUpdater**

Stacktrace:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4c5fc62, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4c5fc62, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.5 (154) release F-Droid/other |
| Device | CPH2417 (CPH2417, OP5552L1, taro) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | dg02-pool03-kvm140, root, release-keys, 1690541595000 |

https://github.com/Tobi823/ffupdater/assets/24689015/5103b5bd-a272-4713-9d3a-f4278bc2b884

**Comment by latacter2** [comment]
Thank you.

Clarification needed plz

I uninstalled Fennec

I uninstalled FFU & reinstalled from FDroid

I attempted to install Fennec from within FFU, but it Crashed.

I force-stopped FFU & cleared cache.

I booted FFU & again attempted to install Fennec....crash again.

Up until these last two updates for FFU, Fennec had been updating seamlessly.

Can u help?



Sep 9, 2023 8:07:15 AM Murteza Yesil ***@***.***>:

**Comment by Tobi823** [comment]
@latacter2 FFUpdater expected that there is always two Fennec releases for each version on https://f-droid.org/packages/org.mozilla.fennec_fdroid/:

For example:
- release 116.3.0 and version code 1163020 for arm64 devices
- release 116.3.0 and version code 1163000 for arm32 /  armeabi-v7a  devices

But 117.0.0 has only one release. And the missing of the second release caused the crash.

**Comment by Tobi823** [comment]
Already fixed in https://github.com/Tobi823/ffupdater/issues/491
