### ISSUE TITLE
App don't work

### ISSUE THREAD

**Issue by 3Lord3** [Tobi823/ffupdater#495]
**Describe the bug**
Instant crash

**To Reproduce**
1. Get FFupdater on Droid-ify
2. Start it
3. See error

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bbb97a1, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bbb97a1, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.5 (154) release F-Droid/other |
| Device | ONEPLUS A6010 (OnePlus6T, OnePlus6T, sdm845) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | rd-build-72, OnePlus, release-keys, 1637854373000 |

**Comment by 3Lord3** [comment]
I installed APK from Releases and it works

**Comment by Tobi823** [comment]
On F-Droid it takes some time until the fixed version is published.

**Comment by goodevilgenius** [comment]
I've got the same issue on release from F-Droid: 78.1.5.

**Comment by Goliath0** [comment]
Same here. Installed from f-droid. Update does not work or freeze. Before it works.

**Comment by Goliath0** [comment]
> ``Stacktrace:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7e7f537, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7e7f537, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.3 (152) release F-Droid/other |
| Device | SM-G930F (heroltexx, herolte, universal8890) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 8.0.0 (SDK: 26) |
| OS | SWDH4606, dpi, release-keys, 1658817022000 |

**Comment by Tobi823** [comment]
> On F-Droid it takes some time until the fixed version is published.

Sorry. What I wanted to say was:

"The bug is already fixed in version 78.1.6. But F-Droid it takes some time until the fixed version is published."

**Comment by hoo84** [comment]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	... 6 more

```
Logs:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	... 6 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.5 (154) release Github |
| Device | Pixel 7 (panther_beta, panther, panther) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a |
| Android version | 14 (SDK: 34) |
| OS | abfarm-release-rbe-32-2004-00164, android-build, release-keys, 1693521005000 |

**Comment by Tobi823** [comment]
@hoo84 It is the same bug. You have to wait for F-Droid :)
