### ISSUE TITLE
background Check Cashes the app

### ISSUE THREAD

**Issue by Sailor-SFbay** [Tobi823/ffupdater#496]
**Describe the bug**
This has been happening for months so I figure it's nothing you don't already know about
**To Reproduce**
Just let the app do its thing

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	... 6 more

```
Logs:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	... 6 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.5 (154) release F-Droid/other |
| Device | SM-T870 (gts7lwifixx, gts7lwifi, kona) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | VPDJR212, dpi, release-keys, 1691721215000 |

**Comment by Tobi823** [comment]
This bug is fixed in the latest version (78.1.6)
