### ISSUE TITLE
crash Reporter Sticks for both Mull and Mulch 

### ISSUE THREAD

**Issue by mcwimpy** [Tobi823/ffupdater#502]
**Describe the bug**
FF updater tells me that those two browsers can be updated and I try this now and off  for a few days (to click on the update functionality) but Alex's get the same red results

**To Reproduce**
1. Go to message center of mobile phone
2. Click on 'an update is available for XYZ'
3. WAIT FOR IT TO STOP ups working
4. Scroll down to 'copy paste error log'
5. See error

**Expected behavior**
Normally when I tab the message it goes to a screen where FFupdater downloads and installs the thing. By the way it works almost all the time just like a charm. Write me a mail to mcwimpy@fettabernett.de if you need my attention, cuz I'm rarely ever around here ....

=================================================={{{
Stacktrace:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.7 (156) release F-Droid/other |
| Device | M2007J20CG (surya_id, surya, surya) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-3f0fp, builder, release-keys, 1678955024000 |

**Comment by mcwimpy** [comment]
![Screenshot_2023-10-03-00-05-38-994_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/50b7d301-53bd-4db7-a0a9-45df03d06f03)
![Screenshot_2023-10-03-00-05-31-283_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/451f3917-0659-4c2b-8a2a-d25a8e7ddaea)
![Screenshot_2023-10-03-00-05-19-906_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/1df2c9d9-3341-45f8-824d-36b3d6342053)


========================================
Stacktrace:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install MULL_FROM_REPO in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.7 (156) release F-Droid/other |
| Device | M2007J20CG (surya_id, surya, surya) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-3f0fp, builder, release-keys, 1678955024000 |

**Comment by mcwimpy** [comment]
![Screenshot_2023-10-03-00-07-08-781_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/157b2dc3-21d5-4eae-8aa7-36d1238557c0)
![Screenshot_2023-10-03-00-07-21-222_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/370520cb-955a-4881-9582-77e012c7f14b)
![Screenshot_2023-10-03-00-07-15-730_de marmaro krt ffupdater](https://github.com/Tobi823/ffupdater/assets/11300847/8132dcc3-f1ee-48c0-9941-de431454f65c)

=========================================
Stacktrace:
```
java.lang.RuntimeException: Failed to install MULCH in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install MULCH in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:92)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:41)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:71)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.7 (156) release F-Droid/other |
| Device | M2007J20CG (surya_id, surya, surya) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-3f0fp, builder, release-keys, 1678955024000 |

**Comment by mcwimpy** [comment]
Ich habe immer wieder also zwei drei Mal am Tag alle Updates eingespielt die alle Shops haben also ob das Google Play Store ist Aurora f-droid oder sonst was ich denke ich habe alle Apps aktuell auch FF Update natürlich

**Comment by Tobi823** [comment]
Seltsam. Bei meinem Smartphone kann ich Mulch und Mull installieren und aktualisieren.

Vor paar Tagen gab es Probleme mit der Downloadquelle von Mulch und Mull - daher die Frage: existiert der Fehler immer noch?

**Comment by Tobi823** [comment]
> INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.

Dieser Fehler ist unerwartet. Nutzt du auf deinem Smartphone Firmenapps, die die Installation von Anwendungen aus Drittquellen verbieten?

**Comment by Tobi823** [comment]
Wenn gar nichts hilft, probiere mal, Mulch und Mull zu deinstallieren und wieder zu installieren.

**Comment by Tobi823** [comment]
> Ich habe immer wieder also zwei drei Mal am Tag alle Updates eingespielt die alle Shops haben also ob das Google Play Store ist Aurora f-droid oder sonst was ich denke ich habe alle Apps aktuell auch FF Update natürlich

Und bitte das nächste Mal Punkte setzen :) Ich weiß leider nicht, was du mir sagen willst

**Comment by mcwimpy** [comment]
OK, sorry, war in Eile und hab Sprache zu Text Umwandlung gemacht ... Also ich hab weder Firmen Apps, noch zwweites Nutzerkonto. Aber ich habe neben FFupdater noch mit Google Store, Aurora und F-Droid weitere App Store's im Betrieb und nicht alle können den Session installer verwenden. Manche müssen den sog. "App Manager" verwenden. Den hab ich aus diesem Grund installiert. Würde das dann eine ähnliche Situation wie die von dir genannten Szenarien kreieren? Ich möchte a la long auf FOSS umsteigen, den die verschiedenen Stores, Apps und Browser. Werde reinstallieren und noch mal schreiben. Falls ich irgendwas für dich tun kann in der Art debugging oder so, bin nicht ganz Ahnungslos und könnte technisch alles umsetzen was du mir sagst.

**Comment by mcwimpy** [comment]
OK, sorry, war in Eile und hab Sprache zu Text Umwandlung gemacht ... Also ich hab weder Firmen Apps, noch zwweites Nutzerkonto. Aber ich habe neben FFupdater noch mit Google Store, Aurora und F-Droid weitere App Store's im Betrieb und nicht alle können den Session installer verwenden. Manche müssen den sog. "App Manager" verwenden. Den hab ich aus diesem Grund installiert. Würde das dann eine ähnliche Situation wie die von dir genannten Szenarien kreieren? Ich möchte a la long auf FOSS umsteigen, den die verschiedenen Stores, Apps und Browser. Werde reinstallieren und noch mal schreiben. Falls ich irgendwas für dich tun kann in der Art debugging oder so, bin nicht ganz Ahnungslos und könnte technisch alles umsetzen was du mir sagst.

**Comment by mcwimpy** [comment]
OK also: hab in der Konfiguration eingestellt, dass ich "native" verwende, so kann ich aussuchen mit welchen Installer ich die APK's installiere und nun geben die Updates durch. War kein Bug. Sondern ein "pepkäck" - PEBCAK: Problem Exists Between Chair And Keyboard XD

**Comment by mcwimpy** [comment]
Ticket erledigt
