### ISSUE TITLE
Crash Festivities

### ISSUE THREAD

**Issue by hank-tu-biz** [Tobi823/ffupdater#508]
*Stacktrace:
```
java.lang.IllegalStateException: Can't find download url with regex pattern '\Qhttps://dist.torproject.org/torbrowser/\E([0-9.]{4,})\Q/tor-browser-\E[0-9.]{4,}+\Q-android-aarch64-multi.apk\E'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findVersionAndDownloadUrl(TorBrowser.kt:72)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findVersionAndDownloadUrl(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowser.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a5932bd, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Can't find download url with regex pattern '\Qhttps://dist.torproject.org/torbrowser/\E([0-9.]{4,})\Q/tor-browser-\E[0-9.]{4,}+\Q-android-aarch64-multi.apk\E'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findVersionAndDownloadUrl(TorBrowser.kt:72)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findVersionAndDownloadUrl(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowser.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a5932bd, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.2.4 (161) release Github |
| Device | LM-G850 (mh2lm, mh2lm, msmnile) |
| Manufacturer | lge (LGE) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | LGEACI8R8, jenkins, release-keys, 1583415955000 |

**Comment by Tobi823** [comment]
I found the issue and fixed it in version 78.2.5. To update FFUpdater you can:
- download the APK file from Github/Gitlab () and install it
   - https://github.com/Tobi823/ffupdater/releases/tag/78.2.5
   - https://gitlab.com/Tobiwan/ffupdater_gitlab/-/releases/78.2.5
- use F-Droid with my own repository to update FFUpdater
- temporary uninstall Tor Browser + update FFUpdater in FFUpdater
