### ISSUE TITLE
Auto crashes at start

### ISSUE THREAD

**Issue by WPTP** [Tobi823/ffupdater#512]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Stacktrace:
```
java.lang.IllegalStateException: Can't find download url with regex pattern '\Qhttps://dist.torproject.org/torbrowser/\E([0-9.]{4,})\Q/tor-browser-\E[0-9.]{4,}+\Q-android-aarch64-multi.apk\E'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findVersionAndDownloadUrl(TorBrowser.kt:72)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findVersionAndDownloadUrl(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowser.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fead479, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Can't find download url with regex pattern '\Qhttps://dist.torproject.org/torbrowser/\E([0-9.]{4,})\Q/tor-browser-\E[0-9.]{4,}+\Q-android-aarch64-multi.apk\E'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findVersionAndDownloadUrl(TorBrowser.kt:72)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findVersionAndDownloadUrl(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowser.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fead479, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.2.4 (161) release Github |
| Device | Pixel 6 (oriole, oriole, oriole) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | abfarm-release-rbe-64-2004-0046, android-build, release-keys, 1693627309000 |

**Comment by Tobi823** [comment]
I found the issue and fixed it in version 78.2.5. To update FFUpdater you can:
- download the APK file from Github/Gitlab and install it
- use F-Droid with my own repository to update FFUpdater
- temporary uninstall Tor Browser + update FFUpdater in FFUpdater
