### ISSUE TITLE
Crashes if Cromite arm32-v7a is installed

### ISSUE THREAD

**Issue by beefykitten** [Tobi823/ffupdater#516]
**Describe the bug**
FFUpdater crashes while looking for updates, but only if Cromite arm32-v7a is installed.

**To Reproduce**
1. Open FFUpdater.
2. Watch it crash.

**Expected behavior**
The opposite of this.

**Error message from FFUpdater**

Stacktrace:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at de.marmaro.krt.ffupdater.device.DeviceAbiExtractor.findBestAbi(DeviceAbiExtractor.kt:224)
	at de.marmaro.krt.ffupdater.app.impl.Cromite.findFileName(Cromite.kt:61)
	at de.marmaro.krt.ffupdater.app.impl.Cromite.fetchLatestUpdate(Cromite.kt:39)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:29)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findInstalledAppStatus(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.MainActivity.updateMetadataOf(MainActivity.kt:207)
	at de.marmaro.krt.ffupdater.MainActivity.fetchLatestUpdates(MainActivity.kt:190)
	at de.marmaro.krt.ffupdater.MainActivity.access$fetchLatestUpdates(MainActivity.kt:64)
	at de.marmaro.krt.ffupdater.MainActivity$fetchLatestUpdates$1.invokeSuspend(MainActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@861401c, Dispatchers.Main]

```
Logs:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at de.marmaro.krt.ffupdater.device.DeviceAbiExtractor.findBestAbi(DeviceAbiExtractor.kt:224)
	at de.marmaro.krt.ffupdater.app.impl.Cromite.findFileName(Cromite.kt:61)
	at de.marmaro.krt.ffupdater.app.impl.Cromite.fetchLatestUpdate(Cromite.kt:39)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:29)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.findInstalledAppStatus(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.MainActivity.updateMetadataOf(MainActivity.kt:207)
	at de.marmaro.krt.ffupdater.MainActivity.fetchLatestUpdates(MainActivity.kt:190)
	at de.marmaro.krt.ffupdater.MainActivity.access$fetchLatestUpdates(MainActivity.kt:64)
	at de.marmaro.krt.ffupdater.MainActivity$fetchLatestUpdates$1.invokeSuspend(MainActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@861401c, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.2.5 (162) release Github |
| Device | SM-T510 (gta3xlwifixx, gta3xlwifi, exynos7904) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | 21DKG902, dpi, release-keys, 1673246928000 |

**Comment by Tobi823** [comment]
Your bug is fixed in 78.2.6
