### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by BenjaminBE4** [Tobi823/ffupdater#53]
How to reproduce:

I got a notification saying background update had failed. When I opened the notification the app had crashed.

Stacktrace:

java.lang.NullPointerException at MozillaCiLogConsumer.kt:28

java.lang.NullPointerException

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Android Version: 30
Device Manufacturer: motorola
Device Model: moto g(8) power

**Comment by Tobi823** [comment]
The bug is already fixed and should be available on F-Droid soon (couple days) https://github.com/Tobi823/ffupdater/issues/52

**Comment by Tobi823** [comment]
Update is available on F-Droid
