### ISSUE TITLE
Tor Browser can't be downloaded

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#531]

**Comment by Tobi823** [comment]
Reason: The new APKs are not yet published. The download links https://www.torproject.org/de/download/#android for Android dont work yet

**Comment by Tobi823** [comment]
Fixed

**Comment by Para-lyzed** [comment]
Experiencing this bug again. Tor is not able to download because the download links don't work yet. Since this seems to be a recurring issue, can this error be handled so the app doesn't crash? Stacktrace is posted below, but is consistent with the original issue. I navigated to the Android download page supplied by FFUpdater and receive a 404 on the download link.

Stacktrace:
```
java.lang.IllegalStateException: can't find latest update for TOR_BROWSER.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:41)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1dece91, Dispatchers.Main]
Caused by: java.lang.IllegalStateException: Can't extract creation date from website: https://dist.torproject.org/torbrowser/13.0.13/?P=tor-browser-android-aarch64-13.0.13.apk
with regex pattern: \Q</a>\E\s+(\d{4}-\d{1,2}-\d{1,2}) (\d{1,2}:\d{1,2})\s+((\d){2,3})M\s+\n
content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html> <head>  <title>Index of /torbrowser/13.0.13</title> </head> <body><h1>Index of /torbrowser/13.0.13</h1><pre><img src="/icons/blank.gif" alt="Icon "> <a href="?C=N;O=D;P=tor-browser-android-aarch64-13.0.13.apk">Name</a>                    <a href="?C=M;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Last modified</a>      <a href="?C=S;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Size</a>  <a href="?C=D;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Description</a><hr><img src="/icons/back.gif" alt="[PARENTDIR]"> <a href="/torbrowser/">Parent Directory</a>                             -   <hr></pre><address>Apache Server at dist.torproject.org Port 443</address></body></html>
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findDateTime(TorBrowser.kt:107)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findDateTime(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findDateTime$1.invokeSuspend(TorBrowser.kt:0)
	... 10 more

```
Logs:
```
java.lang.IllegalStateException: can't find latest update for TOR_BROWSER.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:41)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1dece91, Dispatchers.Main]
Caused by: java.lang.IllegalStateException: Can't extract creation date from website: https://dist.torproject.org/torbrowser/13.0.13/?P=tor-browser-android-aarch64-13.0.13.apk
with regex pattern: \Q</a>\E\s+(\d{4}-\d{1,2}-\d{1,2}) (\d{1,2}:\d{1,2})\s+((\d){2,3})M\s+\n
content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html> <head>  <title>Index of /torbrowser/13.0.13</title> </head> <body><h1>Index of /torbrowser/13.0.13</h1><pre><img src="/icons/blank.gif" alt="Icon "> <a href="?C=N;O=D;P=tor-browser-android-aarch64-13.0.13.apk">Name</a>                    <a href="?C=M;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Last modified</a>      <a href="?C=S;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Size</a>  <a href="?C=D;O=A;P=tor-browser-android-aarch64-13.0.13.apk">Description</a><hr><img src="/icons/back.gif" alt="[PARENTDIR]"> <a href="/torbrowser/">Parent Directory</a>                             -   <hr></pre><address>Apache Server at dist.torproject.org Port 443</address></body></html>
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.findDateTime(TorBrowser.kt:107)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$findDateTime(TorBrowser.kt:26)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$findDateTime$1.invokeSuspend(TorBrowser.kt:0)
	... 10 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.1 (169) release F-Droid/other |
| Device | GM1911 (OnePlus7Pro, OnePlus7Pro, msmnile) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 598119a0a0e9, root, release-keys, 1707126552000 |

**Comment by Tobi823** [comment]
I can reproduce the error. I will look into it

**Comment by Tobi823** [comment]
The problem is not in FFUpdater. The official download is broken (see https://www.torproject.org/download/). I expect that in the next hours, the Tor project will fix it.

**Comment by Para-lyzed** [comment]
> The problem is not in FFUpdater. The official download is broken (see https://www.torproject.org/download/). I expect that in the next hours, the Tor project will fix it.

Yes, I believe that to be the case. Since this seems to be a recurring problem though, I was curious if the error could be handled in the event that the download page returns a 404 so that the app doesn't crash when trying to install, or throw an error message every time it checks for updates. The download page not being reachable is not the fault of FFUpdater, but the error could be handled (or the error could be silent by default).

**Comment by Tobi823** [comment]
I still have to fight my way through all the issuses 😆 

It is really difficult to detect if the error is only temporary or not. If I would make these errors silent by default, it is likely that I spot the error months later.

I will think about it
