### ISSUE TITLE
Kiwi Browser - Temporarily network error

### ISSUE THREAD

**Issue by Daviteusz** [Tobi823/ffupdater#534]
## Important first questions
**Is your FFUpdater up-to-date?**
- Yes 

**Do you spot similar issues in** https://github.com/Tobi823/ffupdater/issues?
 - No

## Describe the bug
When app is trying to fetch updates for kiwi browser it shows: 
- Temporarily network error. Please try again later 

## To Reproduce
Please insert the steps to reproduce the behavior here:
1. Open app
2. Find Kiwi Browser
3. Read error.

## Expected behavior
Update should be fetched.

## Error message from FFUpdater
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for KIWI.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7928)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/kiwibrowser/src.next/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for KIWI.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7928)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/kiwibrowser/src.next/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.4.0 (165) release Github |
| Device | KB2003 (OnePlus8T_EU, OnePlus8T, kona) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | chris-Lenovo-Legion-R7000-2020, chris, release-keys, 1700554193000 |

**Comment by UrubuCheiroso** [comment]
This is happening to me too! Exactly the same error!

**Comment by Doc-4** [comment]
Same error, pixel 8 pro. Probably phone agnostic.

**Comment by UrubuCheiroso** [comment]
> This is happening to me too! Exactly the same error!

My phone is a Motorola E22

**Comment by UrubuCheiroso** [comment]
> I found the error and I will release the fix today or tomorrow

Ok, thanks!
