### ISSUE TITLE
Cannot update kiwi browser in the background

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [Tobi823/ffupdater#537]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater. 

Yes, it is up to date

4. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue. 

No, I don't see another report

**Describe the bug**
It tried to update in the background, but after getting the error pretty much every day, I decided to look at it. It seems that ffupdater can't get the latest kiwi browser update. I don't know why this is happening, because the url that it's requesting is properly formatted.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Install kiwi browser
2. Wait for background update
8. See the error

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

I expect it to not throw the error

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for KIWI.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	... 6 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/kiwibrowser/src.next/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Logs:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:82)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for KIWI.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	... 6 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/kiwibrowser/src.next/releases/latest failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	... 4 more
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.4.0 (165) release Github |
| Device | Pixel 6a (bluejay, bluejay, bluejay) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | abfarm-release-rbe-64-2004-0014, android-build, release-keys, 1698351037000 |

**Comment by ego-lay-atman-bay** [comment]
Or at least I thought it was the latest release, because I didn't see an update til now.

**Comment by Tobi823** [comment]
I will close it now because the latest version of FFUpdater should fix this error
