### ISSUE TITLE
Attempting to install an application through the app causes it to crash

### ISSUE THREAD

**Issue by 1Phase1** [Tobi823/ffupdater#538]
- **Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

Yes.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

No.

**Describe the bug**
Pressing the plus button on any application in FFUpdater's "Add new application" menu causes the app to immediately crash.

**To Reproduce**
1. Press the "install app" button
2. In the "add new application" menu, press the plus button on any of the listed applications.
3. FFUpdater will crash with the below listed crash log.

**Expected behavior**
The selected application should be getting installed without error.

**Error message from FFUpdater**
Stacktrace:
```
android.content.pm.PackageManager$NameNotFoundException: org.chromium.thorium
	at android.app.ApplicationPackageManager.getInstallSourceInfo(ApplicationPackageManager.java:2717)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls.wasInstalledByFFUpdater(InstalledVersionFetcher.kt:42)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.wasInstalledByFFUpdater(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog.show(CardviewOptionsDialog.kt:134)
	at de.marmaro.krt.ffupdater.activity.add.AddRecyclerView$showAddAppDialog$1.invokeSuspend(AddRecyclerView.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b7235e, Dispatchers.Main]

```
Logs:
```
android.content.pm.PackageManager$NameNotFoundException: org.chromium.thorium
	at android.app.ApplicationPackageManager.getInstallSourceInfo(ApplicationPackageManager.java:2717)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls.wasInstalledByFFUpdater(InstalledVersionFetcher.kt:42)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.wasInstalledByFFUpdater(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog.show(CardviewOptionsDialog.kt:134)
	at de.marmaro.krt.ffupdater.activity.add.AddRecyclerView$showAddAppDialog$1.invokeSuspend(AddRecyclerView.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b7235e, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.0.0 (166) release Github |
| Device | SM-G975U1 (beyond2qlteue, beyond2q, msmnile) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | SWDK3906, dpi, release-keys, 1691002401000 |

**Comment by Tobi823** [comment]
Fix is now live

**Comment by 1Phase1** [comment]
@Tobi823 The app is no longer crashing anymore. Thanks a lot for the fix.
