### ISSUE TITLE
FF Updater is unable to check for updates.

### ISSUE THREAD

**Issue by Parmanand96** [Tobi823/ffupdater#54]
java.lang.NullPointerException at MozillaCiLogConsumer.kt:28
java.lang.NullPointerException

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Android Version: 28
Device Manufacturer: OPPO
Device Model: CPH2083

**Comment by textPreferred** [comment]
Same here :


java.lang.NullPointerException at MozillaCiLogConsumer.kt:28
java.lang.NullPointerException

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$$inlined$withLock$lambda$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


Android Version: 30
Device Manufacturer: OnePlus
Device Model: A0001

**Comment by Tobi823** [comment]
The bug is already fixed and should be available on F-Droid soon https://github.com/Tobi823/ffupdater/issues/53.

The new version is already been build by the F-Droid servers (https://monitor.f-droid.org/builds/log/de.marmaro.krt.ffupdater/73). But the guys from F-Droid have to manually sign the update and release it on F-Droid.

**Comment by TPS** [comment]
v74.3.0 is available now @ F-Droid. @Tobi823 Is the version meant?

**Comment by Parmanand96** [comment]
> v74.3.0 is available now @ F-Droid. @Tobi823 Is the version meant?

Yes, the problem has been sovled.

**Comment by textPreferred** [comment]
I can confirm as well. Thank you!
