### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dirt2022** [Tobi823/ffupdater#548]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.
yes from github version.

3. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.
Yes, but the issue has been closed.The developer says it has been fixed in the latest version

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.

1. click the "install app button"

![Screenshot_20231202-185033_FFUpdater_1](https://github.com/Tobi823/ffupdater/assets/108220246/30e06d81-b284-4176-b217-08bfe98a2a2e)

2. see the screenshot below
![Screenshot_20231202-185059_FFUpdater_1_1](https://github.com/Tobi823/ffupdater/assets/108220246/a0466245-6805-49be-855b-fa64ce4c99fb)

**Expected behavior**
The app should be installed sucessfully

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
java.lang.IllegalArgumentException: Unknown package: org.mozilla.firefox_beta
	at android.os.Parcel.createException(Parcel.java:2075)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.content.pm.IPackageManager$Stub$Proxy.getInstallerPackageName(IPackageManager.java:6689)
	at android.app.ApplicationPackageManager.getInstallerPackageName(ApplicationPackageManager.java:2063)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls.wasInstalledByOtherApp(InstalledVersionFetcher.kt:45)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.wasInstalledByOtherApp(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog.show(CardviewOptionsDialog.kt:134)
	at de.marmaro.krt.ffupdater.activity.add.AddRecyclerView$showAddAppDialog$1.invokeSuspend(AddRecyclerView.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eda2238, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4241)
	at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:21792)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3057)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4121)
	at android.os.Binder.execTransactInternal(Binder.java:1021)


```
Logs:
```
java.lang.IllegalArgumentException: Unknown package: org.mozilla.firefox_beta
	at android.os.Parcel.createException(Parcel.java:2075)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.content.pm.IPackageManager$Stub$Proxy.getInstallerPackageName(IPackageManager.java:6689)
	at android.app.ApplicationPackageManager.getInstallerPackageName(ApplicationPackageManager.java:2063)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledVersionFetcher$DefaultImpls.wasInstalledByOtherApp(InstalledVersionFetcher.kt:45)
	at de.marmaro.krt.ffupdater.app.impl.AppBase.wasInstalledByOtherApp(AppBase.kt:20)
	at de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog.show(CardviewOptionsDialog.kt:134)
	at de.marmaro.krt.ffupdater.activity.add.AddRecyclerView$showAddAppDialog$1.invokeSuspend(AddRecyclerView.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eda2238, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4241)
	at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:21792)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3057)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4121)
	at android.os.Binder.execTransactInternal(Binder.java:1021)


```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.0.1 (167) release Github |
| Device | kirin710 (kirin710, kirin710, kirin710) |
| Manufacturer | kirin710 (HUAWEI) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | cg-virtualbox, crossgate, release-keys, 1628441975000 |         

Additional information:
1. My tablet (this device : HUAWEI jdn2-al50) has been flashed into lineageos GSI (android 10 , from sourceforge.net ) , Stock firmware is android 9

**Comment by Tobi823** [comment]
I found the bug - it was broken for everyone using Android 10 or lower.
