### ISSUE TITLE
First startup crash

### ISSUE THREAD

**Issue by 7ERr0r** [Tobi823/ffupdater#551]
Stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.activity.add.AddAppActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3616)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:358)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at de.marmaro.krt.ffupdater.activity.add.AddAppActivity.onCreate(AddAppActivity.kt:34)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
	... 11 more
Caused by: java.lang.NoSuchMethodException: de.marmaro.krt.ffupdater.dialog.CardviewOptionsDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 25 more
 
```

Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release Github |
| Device | ONEPLUS A6013 (OnePlus6T, OnePlus6T, sdm845) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | rd-build-72, OnePlus, release-keys, 1637854373000 |

**Comment by Tobi823** [comment]
I found the problem. I will release the fix in the next days because it is not critical
