### ISSUE TITLE
Error during manual download

### ISSUE THREAD

**Issue by DrDustwolf** [Tobi823/ffupdater#553]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

Yes FFUpdater is up-to-date.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

No.

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.

When I manually download download browsers, this error often appears. Sometimes I a somewhat similar appears while an automatic background download/update, but I'm not sure if it's exactly the same issue since I didn't report the bug untill yet...‽
My internet connection is good and stable. I'm standing right infront of the Router and got full signal. My V-DSL Bandwidth is 50 MB/S.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Open up FFUpdater.
2. Wait for the refreshment of the sources.
3. Click on the Download arrow.
4. Wait a while for the download.
5. The error appears at some point during the download.
6. Click away the error message or save it to report it later.
7. Restart the download.
8. The error appears again multiple times.
9. Maybe after around 4-6 tries you have luck and FFUpdater finishes the download successfully and finally installs the update.

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

Sucessfully download updates the first time you try.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Size of download should be 96021743 bytes, but it is 80941239 bytes.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Size of download should be 96021743 bytes, but it is 80941239 bytes.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release F-Droid/other |
| Device | SHIFT6mq (lineage_axolotl, axolotl, sdm845) |
| Manufacturer | SHIFT (SHIFT) | 
| Supported ABIs | arm64-v8a |
| Android version | 13 (SDK: 33) |
| OS | 299fad85a68f, root, dev-keys, 1701501595000 |

**Comment by Tobi823** [comment]
Which app are you trying to install?
