### ISSUE TITLE
no instala la aplicación

### ISSUE THREAD

**Issue by ivilleda** [Tobi823/ffupdater#559]
Stacktrace:
```
java.lang.RuntimeException: Failed to install FENNEC_FDROID in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FENNEC_FDROID in the foreground.
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(DownloadActivity.kt:395)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(DownloadActivity.kt:75)
	at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.3.0 (164) release Github |
| Device | 23021RAAEG (tapas_global, tapas, bengal) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | pangu-build-component-system-325662-czdzx-9m0ls-94f6z, builder, release-keys, 1694070981000 |

**Comment by Tobi823** [comment]
The real cause is that your smartphone operating system is behaving differently than FFUpdater (and the Google documentation) expect it.

But I don't have a Redmi / Xiaomi device to debug it.

You can try to use a different installation method in FFUpdater or you can try to disable the MIUI optimization.
