### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by RealJosephKnapp** [Tobi823/ffupdater#560]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater. Yes

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue. No

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is. When I install ffupdater on my Google pixel tablet I cannot get it to update to the GitHub release from the Google play release.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ... Install ffupdater from. Fdroid
2. ... Update Firefox so that ffupdater can work with it
3. ... It gives the error listed below

**Expected behavior**
Please give a clear and concise description of what you expected to happen. I expected it to update from the GitHub release so that ffupdater can work with just one tap.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 2015991658 is older than current 2015991663. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1802)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FIREFOX_RELEASE in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 2015991658 is older than current 2015991663. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1802)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release Github |
| Device | Pixel Tablet (tangorpro, tangorpro, tangorpro) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a |
| Android version | 14 (SDK: 34) |
| OS | abfarm-release-rbe-32-2004-00135, android-build, release-keys, 1699657852000 |

**Comment by Tobi823** [comment]
I suspect than Firefox was updated by another app. This bug should be fixed by now.
