### ISSUE TITLE
FFUpdater is trying to "update" to older versions

### ISSUE THREAD

**Issue by lothkang** [Tobi823/ffupdater#561]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

**Describe the bug**
If the installed version and the latest version in the repository don't match, FFUpdater will try to download and install the version from the repository, even if the installed version is newer.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Update any of the supported browsers from an external source, such as Aptoide
2. Make FFUpdater search for updates
3. If the installed version has a different version number/code FFUpdater will no longer see the app as up to date

**Expected behavior**
FFUpdater will treat the app if the installed version is newer as up-to-date

**Error message from FFUpdater**
Displayed error message:

Az alkalmazas telepitése nem volt sikeres
INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade
detected: Update version code 2015993634 is older than current 2015993639. The operation failed because one or more of the APKs was invalid. For example, they might be malformed, corrupt, incorrectly
signed, mismatched, etc.

Full error message:
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_NIGHTLY in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 2015993634 is older than current 2015993639. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1808)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FIREFOX_NIGHTLY in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 2015993634 is older than current 2015993639. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1808)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release F-Droid/other |
| Device | 2203129G (taoyao_global, taoyao, taoyao) |
| Manufacturer | Xiaomi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | pangu-build-component-system-218505-wfdw6-9gxg0-wf785, builder, release-keys, 1700804515000 |         ![Screenshot_2023-12-25-15-39-17-971_de.marmaro.krt.ffupdater.jpg](https://github.com/Tobi823/ffupdater/assets/23418584/42c6954b-ac15-4e46-b066-d92c3bc8f100)

**Comment by mandree** [comment]
To describe error circumstances and context why this is relevant:
Similar issue occurs on a Samsung device; Samsung operate their own Galaxy Store as app store, and have distributed Firefox 122 quite early, while Google's okay store still carries 121.1.0, which is currently also the version ffupdater wants to "update" to. So I second the request to let ffupdater consider "newer or same" as up-tp-date, and not just "equal version".

**Comment by Tobi823** [comment]
Thanks for the information.

This bug should be fixed because FFUpdater now only auto-updates apps if they were installed/updated by FFUpdater previously.
