### ISSUE TITLE
Cannot download firefox nightly

### ISSUE THREAD

**Issue by Wojtaz0w** [Tobi823/ffupdater#563]
**Describe the bug**
I can't download FF Nightly, when it was installed oftentimes update check for it would fail. FYI my internet's fine cause im using it right now to report issue. 

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Try to download Firefox Nightly

**Expected behavior**
It downloads...? 

**Error message from FFUpdater**
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://firefoxci.taskcluster-artifacts.net/JwehjEXqQJ6Cm9o04o1lqQ/0/public/chain-of-trust.json failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: can't find latest update for FIREFOX_NIGHTLY.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findInstalledAppStatus(InstalledAppStatusFetcher.kt:35)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findInstalledAppStatus$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://firefoxci.taskcluster-artifacts.net/JwehjEXqQJ6Cm9o04o1lqQ/0/public/chain-of-trust.json failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadWithCache$2.invokeSuspend(FileDownloader.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Response is unsuccessful. HTTP code: '404'.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.validateAndReturnResponseBody(FileDownloader.kt:179)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.callUrlWithCache(FileDownloader.kt:240)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$callUrlWithCache(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$callUrlWithCache$1.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release Github |
| Device | Redmi 9 (lineage_lancelot, lancelot, mt6768) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | android-build, nobody, release-keys, 1703928936000 |

**Comment by Tobi823** [comment]
I can't reproduce the error. Maybe it was caused by temporary fault.
