### ISSUE TITLE
UpdateCheckException: Fail to check FIREFOX_RELEASE for updates

### ISSUE THREAD

**Issue by ItsJustSomeDude** [Tobi823/ffupdater#57]
Got a notification that led to this error, and it can be triggered manually by opening the app and refreshing it.

```de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException at MainActivity.kt:204
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException

de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException: fail to check FIREFOX_RELEASE for updates
at de.marmaro.krt.ffupdater.MainActivity$checkForAppUpdate$1.invokeSuspend(MainActivity.kt:204)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$2$1.invokeSuspend(BaseAppDetail.kt:63)
... 6 more
```

Using latest f-droid version of FFUpdater.

Android Version: 30
Device Manufacturer: motorola
Device Model: moto g(7)

~~Issue appears different than #52.~~  Second part of the stack trace is the same as #52, there is some extra at the beginning.

**Comment by Tobi823** [comment]
The bug is similar to #52 :
FFUpdater has to parse the chain_of_trust.log to find the available version string. But the structure of the chain_of_trust.log has changed again :(

**Comment by Tobi823** [comment]
and Firefox Beta (aka "Firefox for Android Beta" is also affected)

**Comment by Tobi823** [comment]
and it's fixed. Should be available on F-Droid soon.

**Comment by Tobi823** [comment]
@ItsJustSomeDude Thanks for your report.

**Comment by Tobi823** [comment]
Firefox Beta is still broken - see https://github.com/Tobi823/ffupdater/issues/60#issuecomment-885063697
