### ISSUE TITLE
Tor browser alpha fails constantly

### ISSUE THREAD

**Issue by robovoice1** [Tobi823/ffupdater#570]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

**Describe the bug**
Updating of Tor browser fails constantly after downloading

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1.try to update to latest tor browser alpha
2. ...
3. ...

**Expected behavior**
Please give a clear and concise description of what you expected to happen.
Worked before (downloading and installing tor browser alpha)

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Stacktrace:
```
java.lang.RuntimeException: Failed to install TOR_BROWSER_ALPHA in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Signature of downloaded APK is invalid. Expected 15f760b41acbe4783e667102c9f67119be2af62fab07763f9d57f01e5e1074e1 but was 20061f045e737c67375c17794cfedb436a03cec6bacb7cb9f96642205ca2cec8.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.hasApkCorrectCertificate(AbstractAppInstaller.kt:42)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$hasApkCorrectCertificate(AbstractAppInstaller.kt:17)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$hasApkCorrectCertificate$1.invokeSuspend(AbstractAppInstaller.kt:0)
	... 12 more

```
Logs:
```
java.lang.RuntimeException: Failed to install TOR_BROWSER_ALPHA in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Signature of downloaded APK is invalid. Expected 15f760b41acbe4783e667102c9f67119be2af62fab07763f9d57f01e5e1074e1 but was 20061f045e737c67375c17794cfedb436a03cec6bacb7cb9f96642205ca2cec8.
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.hasApkCorrectCertificate(AbstractAppInstaller.kt:42)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$hasApkCorrectCertificate(AbstractAppInstaller.kt:17)
	at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$hasApkCorrectCertificate$1.invokeSuspend(AbstractAppInstaller.kt:0)
	... 12 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.0 (168) release Github |
| Device | Pixel 6 Pro (raven, raven, raven) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | grapheneos, grapheneos, release-keys, 1707176723000 |

**Comment by Tobi823** [comment]
> Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Signature of downloaded APK is invalid. Expected 15f760b41acbe4783e667102c9f67119be2af62fab07763f9d57f01e5e1074e1 but was 20061f045e737c67375c17794cfedb436a03cec6bacb7cb9f96642205ca2cec8.

20061f045e737c67375c17794cfedb436a03cec6bacb7cb9f96642205ca2cec8 is the fingerprint of the normal Tor browser. Maybe FFUpdater tries to download the wrong APK.

**Comment by Tobi823** [comment]
Issue now fixed

**Comment by robovoice1** [comment]
Thanks for the fast reaction and this great app 👍😎

**Comment by Tobi823** [comment]
Thanks :)

Last month I had to reset my computer and reinstall many tools. It possible that I can't release the APK today. But I'm sure that I can do it tomorrow

**Comment by Tobi823** [comment]
Fix is now released.
