### ISSUE TITLE
This error occurred during Installation.

### ISSUE THREAD

**Issue by Universalizer** [Tobi823/ffupdater#572]
Stacktrace:
```
java.lang.RuntimeException: Failed to install TOR_BROWSER_ALPHA in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Installation failed. ResultCode: 0, INSTALL_RESULT: null
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.createInstallationFailedException(IntentInstaller.kt:53)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.access$createInstallationFailedException(IntentInstaller.kt:24)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:39)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:34)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$sam$androidx_activity_result_ActivityResultCallback$0.onActivityResult(IntentInstaller.kt:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9324)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 6 more

```
Logs:
```
java.lang.RuntimeException: Failed to install TOR_BROWSER_ALPHA in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: Installation failed. ResultCode: 0, INSTALL_RESULT: null
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.createInstallationFailedException(IntentInstaller.kt:53)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.access$createInstallationFailedException(IntentInstaller.kt:24)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:39)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$appResultCallback$1.invoke(IntentInstaller.kt:34)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller$sam$androidx_activity_result_ActivityResultCallback$0.onActivityResult(IntentInstaller.kt:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9324)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 6 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.1 (169) release Github |
| Device | SM-A146B (a14xxx, a14x, s5e8535) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | #####, dpi, release-keys, ##### |

**Comment by Tobi823** [comment]
Sorry for the late reply.

Did you try another installation method? Or why do you not use the SessionInstaller?

The Native installer has the problem that the error messages are quite poor. I don't what ResultCode: 0 means and I don't have a Samsung smartphone to test it.

**Comment by Tobi823** [comment]
> Didn't found downloaded apk in app folder.

I suspect that the option "Delete the downloaded update if the installation fails" was enabled.
