### ISSUE TITLE
Crash when attempt Klar update

### ISSUE THREAD

**Issue by PapawJD** [Tobi823/ffupdater#573]
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_KLAR in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 380362030 is older than current 380440258. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1809)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Logs:
```
java.lang.RuntimeException: Failed to install FIREFOX_KLAR in the foreground.
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.installApp(DownloadActivity.kt:397)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity.access$installApp(DownloadActivity.kt:77)
	at de.marmaro.krt.ffupdater.activity.download.DownloadActivity$installApp$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: de.marmaro.krt.ffupdater.installer.exceptions.InstallationFailedException: INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 380362030 is older than current 380440258. The installation failed because one or more of the APKs was invalid.
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.createInstallFailedException(SessionInstaller.kt:98)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$createInstallFailedException(SessionInstaller.kt:45)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$intentReceiver$1.onReceive(SessionInstaller.kt:77)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1809)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.1.1 (169) release Github |
| Device | motorola edge plus (2022) (hiphi_gu, hiphi, hiphi) |
| Manufacturer | motorola (motorola) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | ilclbld237, hudsoncm, release-keys, 1700816297000 |

**Comment by segln** [comment]
Same with Firefox Nightly. I removed Firefox completely but FFUpdater reports INSTALL_FAILED_VERSION_DOWNGRADE.
Same with all installation methods.

**Comment by Tobi823** [comment]
I suspect that this was a temporary issue. For some reason the downloaded update was older than the existing app.

Today I can't reproduce it. 

Does the error occur more frequently?
