### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by ThunderHen** [Tobi823/ffupdater#586]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.
App crashed not sure why. 
**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ...opened app. 
2. ...left app runing in the background
3. ...app crashed 

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:173)
	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.internalStart(BackgroundWork.kt:200)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.internalStart$default(BackgroundWork.kt:195)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.start(BackgroundWork.kt:187)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.startOrRestartBackgroundWork(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.onResumeSuspended(MainActivity.kt:127)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.access$onResumeSuspended(MainActivity.kt:55)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity$onResumeSuspended$1.invokeSuspend(MainActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@73cd3f6, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:173)
	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.internalStart(BackgroundWork.kt:200)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.internalStart$default(BackgroundWork.kt:195)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$Companion.start(BackgroundWork.kt:187)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.startOrRestartBackgroundWork(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.onResumeSuspended(MainActivity.kt:127)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity.access$onResumeSuspended(MainActivity.kt:55)
	at de.marmaro.krt.ffupdater.activity.main.MainActivity$onResumeSuspended$1.invokeSuspend(MainActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@73cd3f6, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.0 (170) release F-Droid/other |
| Device | SM-A125U (a12usq, a12u, a12u) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | 21DK7901, dpi, release-keys, 1701250535000 |

**Comment by Tobi823** [comment]
This is a strange - I dont face this issue on my private smartphone or on my virtual Android emulators. I have to investigate

**Comment by Tobi823** [comment]
The documentation of Android WorkManager `WorkManager.getInstance(context))` reads:

> Returns: The singleton instance of [WorkManager](https://developer.android.com/reference/androidx/work/WorkManager); this may be null in unusual circumstances where you have disabled automatic initialization and have failed to manually call [initialize](https://developer.android.com/reference/androidx/work/WorkManager#initialize(android.content.Context,androidx.work.Configuration)).

**Comment by Tobi823** [comment]
Maybe I found the solution. According to https://issuetracker.google.com/issues/138465476, some Android OS are initializing software components not always in the right order.
