### ISSUE TITLE
Impossible to fetch browser version and update them

### ISSUE THREAD

**Issue by Integrat-edCircuit** [Tobi823/ffupdater#589]
**Important first questions**

1. Is your FFUpdater up-to-date?  Yes

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? No

**Describe the bug**
After upgrading to FFupdater 79.2.1, I get an "unexpected error" when fetching browser repos 

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Update the app
2. slide down to refresh the app list
3. get the error

**Expected behavior**
ffupdater displaying app version and allowing you to update

![Screenshot_20240522-073017_FFUpdater](https://github.com/Tobi823/ffupdater/assets/136177157/90937c52-f6e2-4e1b-a2d2-5af39994ae95)

**Error message from FFUpdater**
Stacktrace:
```
j$.time.format.y: Text '14-May-2024 12:37' could not be parsed at index 3
	at j$.time.format.DateTimeFormatter.g(SourceFile:0)
	at j$.time.format.DateTimeFormatter.f(Unknown Source:10)
	at j$.time.LocalDateTime.parse(Unknown Source:11)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer.findDateTimeFromPage(MozillaArchiveConsumer.kt:45)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer$findDateTimeFromPage$1.invokeSuspend(MozillaArchiveConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a3e811a, Dispatchers.Main]

```
Logs:
```
j$.time.format.y: Text '14-May-2024 12:37' could not be parsed at index 3
	at j$.time.format.DateTimeFormatter.g(SourceFile:0)
	at j$.time.format.DateTimeFormatter.f(Unknown Source:10)
	at j$.time.LocalDateTime.parse(Unknown Source:11)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer.findDateTimeFromPage(MozillaArchiveConsumer.kt:45)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer$findDateTimeFromPage$1.invokeSuspend(MozillaArchiveConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a3e811a, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.1 (171) release Github |
| Device | SM-A202F (a20eeea, a20e, exynos7884B) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | VPDJR108, dpi, release-keys, 1687915365000 |

**Comment by il-santo** [comment]
Same problem for me, same trace.

**Comment by OskyEdz** [comment]
Same here, I'm on:


Key | Value
-- | --
FFUpdater version | 79.2.1 (171) release Github
Device | 22126RN91Y (Xiaomi Earth)
Manufacturer | Xiaomi
Supported ABIs | arm64-v8a, armeabi-v7a, armeabi
Android version | 14 (SDK: 34)
OS | LineageOS 21

**Comment by PsykoRider** [comment]
Stacktrace:
```
j$.time.format.y: Text '13-May-2024 22:09' could not be parsed at index 3
	at j$.time.format.DateTimeFormatter.g(SourceFile:0)
	at j$.time.format.DateTimeFormatter.f(Unknown Source:10)
	at j$.time.LocalDateTime.parse(Unknown Source:11)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer.findDateTimeFromPage(MozillaArchiveConsumer.kt:45)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer$findDateTimeFromPage$1.invokeSuspend(MozillaArchiveConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```
Logs:
```
j$.time.format.y: Text '13-May-2024 22:09' could not be parsed at index 3
	at j$.time.format.DateTimeFormatter.g(SourceFile:0)
	at j$.time.format.DateTimeFormatter.f(Unknown Source:10)
	at j$.time.LocalDateTime.parse(Unknown Source:11)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer.findDateTimeFromPage(MozillaArchiveConsumer.kt:45)
	at de.marmaro.krt.ffupdater.network.website.MozillaArchiveConsumer$findDateTimeFromPage$1.invokeSuspend(MozillaArchiveConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.1 (171) release Github |
| Device | RMX3561 (RMX3561, RED8BEL1, k6895v1_64) |
| Manufacturer | realme (realme) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | dg02-pool06-kvm59, root, release-keys, 1711079005000 |

**Comment by Tobi823** [comment]
I think I already know how to fix it. I suspect that due to different Android runtimes or language settings, I am not able to convert "May" to the 5th month.

I will fix it tonight.

Just for curiosity ... What happens if you change the language of your smartphones to English?

**Comment by PsykoRider** [comment]
If I set the language to English no error occurs.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tobi823** [comment]
I've now published the fixed version 79.2.2

**Comment by il-santo** [comment]
I can confirm that it is working for me, now. Thanks!

**Comment by PsykoRider** [comment]
Yes, it's working now. Thank you

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
