### ISSUE TITLE
Assume falsely i'm disconnected

### ISSUE THREAD

**Issue by stemy2** [Tobi823/ffupdater#61]
Hello,

The app keeps saying i'm disconnected to internet at every upgrade attempt, even when i'm clearly not.

The traceback:

de.marmaro.krt.ffupdater.app.impl.exceptions.ApiNetworkException at ApiConsumer.kt:63
de.marmaro.krt.ffupdater.app.impl.exceptions.ApiNetworkException

de.marmaro.krt.ffupdater.app.impl.exceptions.ApiNetworkException: Fail to consume API. Previous exceptions: [https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest; https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest; https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest; https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest; https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest]. Last exception:
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResourceWithRetries(ApiConsumer.kt:63)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResourceWithRetries(ApiConsumer.kt:18)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$readNetworkResourceWithRetries$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:74)
	at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResourceWithRetries(ApiConsumer.kt:56)
	... 8 more

Android Version: 27
Device Manufacturer: samsung
Device Model: SM-G930F

**Comment by Tobi823** [comment]
The app reports that it can't access the URL https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest

Can you try to open this URL on your smartphone (with your favourite browser)?

**Comment by Tobi823** [comment]
Now I understand - this error is thrown if the GitHub API rate limit is exceeded. You can only call this API 60 times every hour.

You can visited https://api.github.com/rate_limit and check, how many API calls you can make (resources > core > used)

**Comment by Tobi823** [comment]
![Screenshot_1627608109](https://user-images.githubusercontent.com/10066140/127585671-89101570-cabb-49fe-b88a-14460e935153.jpg)

I will add a better error message.
