### ISSUE TITLE
fix background downloades

### ISSUE THREAD

**Issue by nanderer** [Tobi823/ffupdater#616]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-2.20.3/iceraven-2.20.3-browser-arm64-v8a-forkRelease.apk failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$deferred$1.invokeSuspend(FileDownloader.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:379)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at de.marmaro.krt.ffupdater.network.file.ProgressInterceptorResponseBody$trackTransmittedBytes$1.read(ProgressInterceptorResponseBody.kt:42)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.downloadFile(FileDownloader.kt:181)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$downloadFile(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$2.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Download of https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-2.20.3/iceraven-2.20.3-browser-arm64-v8a-forkRelease.apk failed.
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$deferred$1.invokeSuspend(FileDownloader.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:379)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:39)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at de.marmaro.krt.ffupdater.network.file.ProgressInterceptorResponseBody$trackTransmittedBytes$1.read(ProgressInterceptorResponseBody.kt:42)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.downloadFile(FileDownloader.kt:181)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader.access$downloadFile(FileDownloader.kt:42)
	at de.marmaro.krt.ffupdater.network.file.FileDownloader$downloadFile$2.invokeSuspend(FileDownloader.kt:0)
	... 8 more

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.3 (173) release F-Droid/other |
| Device | SHIFT6mq (axolotl, axolotl, sdm845) |
| Manufacturer | SHIFT (SHIFT) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | shiftphones.com, shiftos, release-keys, 1661346231000 |         

Why the hell is it not possible to have an download running without constantly watching the app without the ability to do anything else on the device, cant u use a service with notification for downloading. Also try to rotate your screen while a download is running, this is most embarrassing!

**Comment by nanderer** [comment]
I mean this premetive downloader is fine with good wifi connection, but try downloading an big file using unstable and slow mobile connection without it continuing downloads from the point connection interrupted and having the screen on all the time at this download activity. I use wget -c within termix for downloading even bigger files and it dose a perfect job downloading big files on unstable connections but your download code is a pain in the but

**Comment by Tobi823** [comment]
> but your download code is a pain in the but

With the next release, I want to increase the timeouts when downloading. The default values of the OkHttp library are a bit too optimistic :D
