### ISSUE TITLE
Changing device orientation causes updater to start downloading gain

### ISSUE THREAD

**Issue by marcel263** [Tobi823/ffupdater#625]
FFUpdater 79.2.4

**Describe the bug**
When the device orientation is changed, the download restarts.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Manually updating a browser, here it's Firefox Nightly.
2. Rotate the device at any stage of the update process so it changes the orientation. The download starts again.

 modified the post to reflect how it also happens while downloading

**Comment by npahakis** [comment]
Happened to me, too.
1. Download starts normal.
![1](https://github.com/user-attachments/assets/0b26512e-661a-4728-975d-349eb42b19db)
2. After orientation change the progress percentage disappears 
![2](https://github.com/user-attachments/assets/e6deb4d6-dedc-4db2-8f59-96670cf28d8f)
3. Turning it back has the percentage still missing
![3](https://github.com/user-attachments/assets/a3f76687-0031-4613-a3b4-1b4ff98c743e)
4. The progress bar starts anew but in the end it gets confused about the download and the app crashes 
![4](https://github.com/user-attachments/assets/bf144b10-8187-4424-9717-25e5690aa3d6)

Here the stacktrace:
Stacktrace:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6da8751, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6da8751, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.4 (174) release Github |
| Device | SM-G980F (x1seea, x1s, exynos990) |
| Manufacturer | samsung (samsung) |
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DK7A21, dpi, release-keys, 1721973468000 |

**Comment by Tobi823** [comment]
Sorry for the late reply. I can reproduce the error 
- rotating once restarts downloads
- rotating again will crash the app
and I will fix it

**Comment by rafnov** [comment]
Got the same on me.
Sorry for duplicate, didn't notice this thread.

**Comment by TPS** [comment]
<details>
<summary>
Something similar when accidentally pressing <kbd>🏡</kbd> while downloading & then quickly reopening FFU & attempting to resume that same download.
</summary>

Stacktrace:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:159)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:22)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e4e6134, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:159)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:22)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e4e6134, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.5 (175) release Github |
| Device | DE2118 (OnePlusN200TMO, OnePlusN200TMO, holi) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | dg02-pool06-kvm44, root, release-keys, 1721740866000 |         

</details>

**Comment by Tobi823** [comment]
Fixed. I had to execute the download in the right scope (downloadViewModel.viewModelScope instead of  lifecycleScope)

**Comment by rafnov** [comment]
@Tobi823 thank you very much for the fix. I can confirm it's fine now.
And thx for adding Thunderbird.
