### ISSUE TITLE
Background check crashed with a stacktrace

### ISSUE THREAD

**Issue by sanjayen** [Tobi823/ffupdater#626]
FFUpdater is uptodate. Got this error for the first time. No user action at all. I use Pixel 7a.

Stacktrace:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:84)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: can't find latest update for MULCH.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findStatusAndCacheIt(InstalledAppStatusFetcher.kt:56)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.access$findStatusAndCacheIt(InstalledAppStatusFetcher.kt:16)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findStatusAndCacheIt$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	... 6 more
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@b5c206c

```
Logs:
```
de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
	at de.marmaro.krt.ffupdater.background.BackgroundWork.doWork(BackgroundWork.kt:84)
	at de.marmaro.krt.ffupdater.background.BackgroundWork$doWork$1.invokeSuspend(BackgroundWork.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: can't find latest update for MULCH.
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.findStatusAndCacheIt(InstalledAppStatusFetcher.kt:56)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$DefaultImpls.access$findStatusAndCacheIt(InstalledAppStatusFetcher.kt:16)
	at de.marmaro.krt.ffupdater.app.impl.base.InstalledAppStatusFetcher$findStatusAndCacheIt$1.invokeSuspend(InstalledAppStatusFetcher.kt:0)
	... 6 more
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@b5c206c

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.4 (174) release Github |
| Device | Pixel 7a (lynx, lynx, lynx) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a |
| Android version | 14 (SDK: 34) |
| OS | r-82b05a39f2cf359a-sj74, android-build, release-keys, 1719515808000 |

**Comment by Tobi823** [comment]
Thanks for the bug report. You can ignore this error for now. 

But I have to improve the error handling in the app because some exceptions like JobCancellationException should not be catched (because it is not a problem when the background update check is cancelled by the operating system).
