### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ChrisTorpher-hue** [Tobi823/ffupdater#627]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ...
2. ...
3. ...

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Ive pasted the crash report here:

Stacktrace:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c411682, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c411682, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.4 (174) release Github |
| Device | SM-A146U (a14xmsq, a14xm, a14xm) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | 21DKG924, dpi, release-keys, 1721887802000 |

**Comment by Tobi823** [comment]
Which app did you try to download?

**Comment by ChrisTorpher-hue** [comment]
Mulch Browser
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Sep 6, 2024, 12:05 by ***@***.***:

**Comment by Tobi823** [comment]
Sadly I can't reproduce this error. I think that this is caused by a temporary problem. 

In the future I will try to improve the error handling to make this type of error easier to debug and solve.
