### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TheXerxes1** [Tobi823/ffupdater#630]
The app simply crashed while updating the browsers and this report was sent

Stacktrace:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6f06988, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:155)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6f06988, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.4 (174) release Github |
| Device | SM-X218U (gta9psqxnc, gta9p, holi) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | 21DK7A07, dpi, release-keys, 1723471278000 |

**Comment by Tobi823** [comment]
Thanks for the bug report. Sadly I can't reproduce this error. I think that this is caused by a temporary problem. 

In the future I will try to improve the error handling to make this type of error easier to debug and solve.
