### ISSUE TITLE
background update check failed, stack trace shown

### ISSUE THREAD

**Issue by myuseraccount** [Tobi823/ffupdater#637]
**Important first questions**

1. FFUpdater up-to-date: 79.2.5, F-Droid build

2. similar issues: 582 and 626, both closed

**Describe the bug**
I get notifications titled "background update failed" with a stack trace

**To Reproduce**
Not predictable. But I don't allow battery optimization exemption (unrestricted background) for ffupdater, and I leave data saver on. Update checks on metered networks is on, but not downloads.

**Expected behavior**
Ffupdater should tolerate data being turned off or restricted through intentional means in the OS.

**Error message from FFUpdater**
Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.5 (175) release F-Droid/other |
| Device | Pixel 5 (redfin, redfin, redfin) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | tuotanto.eu.calyxos.net, cdesai, release-keys, 1728652786000 |

**Comment by bearhoney** [comment]
I see same crash reports.
Device: OnePlus 8T, LineageOS with older Kernel (based on Android 11)

**Comment by Tobi823** [comment]
@myuseraccount Thanks for the detailed error report. 

I think this is a logic error on my side.

The "background update check" notification is only shown, if the  "Simple network test was not successful" failed for 5 times in a row. (with 30s waiting time between the first and second try, 60s between 2nd and 3rd, 120s ...)

("Simple network test was not successful" = a HTTP head request to e.g. https://api.github.com failed)

I guess it is quite normal to have no internet/network for 30min. Maybe you also uses the airplane mode?

**Comment by Tobi823** [comment]
@Tobi823 Solution: skip AppUpdater.kt when simple network test failed, because a failed HTTP head request is a good indicator for no internet

**Comment by myuseraccount** [comment]
Just got a slightly different crash.

Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.5 (175) release F-Droid/other |
| Device | Pixel 5 (redfin, redfin, redfin) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | tuotanto.eu.calyxos.net, cdesai, release-keys, 1728652786000 |         `

**Comment by myuseraccount** [comment]
Still happening.

See also: issues #653 and #659 

Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.3.1 (177) release F-Droid/other |
| Device | Pixel 5 (redfin, redfin, redfin) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | android-build, nobody, release-keys, 1733329613000 |

**Comment by Tobi823** [comment]
should be fixed with 80.0.0

**Comment by myuseraccount** [comment]
@Tobi823 It's been working better than ever! I've even had apps update in the background, and it was never doing that for me before.

Thanks!
