### ISSUE TITLE
Background update failure,  unable to download Tor browser due to temporary network issue.

### ISSUE THREAD

**Issue by persian-phoenix** [Tobi823/ffupdater#659]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:135)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:44)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.2.5 (175) release F-Droid/other |
| Device | SM-N960F (crownltexx, crownlte, exynos9810) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | SWDJ4104, dpi, release-keys, 1667528176000 |         

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ...
2. ...
3. ...

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by Tobi823** [comment]
should be fixed in 80.0.0
