### ISSUE TITLE
Error when checking for Firefox release

### ISSUE THREAD

**Issue by KnallbertLp** [Tobi823/ffupdater#66]
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException at MainActivity.kt:204
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException

de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException: fail to check FIREFOX_RELEASE for updates
	at de.marmaro.krt.ffupdater.MainActivity$checkForAppUpdate$1.invokeSuspend(MainActivity.kt:204)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$2$1.invokeSuspend(BaseAppDetail.kt:63)
	... 6 more

Android Version: 29
Device Manufacturer: samsung
Device Model: SM-G960F

**Comment by Tobi823** [comment]
F-Droid just released the outdated 74.3.**2** version.
Only the 74.3.**4** version works.
I have to wait until F-Droid publishes the 74.3.**4** version.
