### ISSUE TITLE
FF_updater Crashing @ 5:44pm Dec 19 2024

### ISSUE THREAD

**Issue by MisterLightsCoding** [Tobi823/ffupdater#661]
Copy and past from crash Red Screen software,
says to report at git hub and git lab.

Hello android bug report posted.

Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_download.download
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7f783ec, Dispatchers.Main.immediate]

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_download.download
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7f783ec, Dispatchers.Main.immediate]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.3.1 (177) release Github |
| Device | SM-A716U1 (a71xque, a71xq, lito) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DK7902, dpi, release-keys, 1708595438000 |         

More

de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_download.download
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7f783ec, Dispatchers.Main.immediate]

--------- beginning of main
12-19 16:48:00.966 I/FFUpdater(25440): InstalledAppsCache: Update cache of installed apps.
12-19 16:48:00.989 I/FFUpdater(25440): InstalledAppsCache: Cache was updated.
12-19 16:48:00.989 I/FFUpdater(25440): BackgroundJob:: Start BackgroundWork
12-19 16:48:00.989 I/FFUpdater(25440): StorageCleaner: Delete possible cached files of BRAVE, BRAVE_BETA, BRAVE_NIGHTLY, CHROMIUM, DUCKDUCKGO_ANDROID, FAIREMAIL, FIREFOX_BETA, FIREFOX_FOCUS, FIREFOX_FOCUS_BETA, FIREFOX_KLAR, FIREFOX_NIGHTLY, FIREFOX_RELEASE, ICERAVEN, K9MAIL, KIWI, MULCH, MULCH_SYSTEMWEBVIEW, ORBOT, PRIVACY_BROWSER, THUNDERBIRD, THUNDERBIRD_BETA, TOR_BROWSER, VIVALDI
12-19 16:48:00.990 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest CROMITE update.
12-19 16:48:01.051 I/FFUpdater(25440): BackgroundJob:: Execute background job.
12-19 16:48:01.053 I/FFUpdater(25440): BackgroundJob:: Enqueuing work requests for: {[CROMITE, FENNEC_FDROID, FFUPDATER, MULL_FROM_REPO, THORIUM, TOR_BROWSER_ALPHA]}
12-19 16:48:01.054 I/FFUpdater(25440): BackgroundJob:: Done enqueuing work requests.
12-19 16:48:01.116 I/FFUpdater(25440): AppUpdater:: Start doWork for CROMITE
12-19 16:48:01.116 I/FFUpdater(25440): AppUpdater:: Start for CROMITE.
12-19 16:48:01.353 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest CROMITE update.
12-19 16:48:01.426 I/FFUpdater(25440): InstalledAppStatusFetcher: Found CROMITE Version(versionText=131.0.6778.140, buildDate=null) (435ms).
12-19 16:48:01.427 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest FENNEC_FDROID update.
12-19 16:48:01.479 I/FFUpdater(25440): InstalledAppStatusFetcher: Found CROMITE Version(versionText=131.0.6778.140, buildDate=null) (125ms).
12-19 16:48:01.481 E/FFUpdater(25440): AppUpdater:: Failed to update app
12-19 16:48:01.481 E/FFUpdater(25440): de.marmaro.krt.ffupdater.background.exception.AppUpdaterNonRetryableException: No update available for CROMITE.
12-19 16:48:01.481 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.background.AppUpdater.doUpdateCheck-gIAlu-s(AppUpdater.kt:96)
12-19 16:48:01.481 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$doUpdateCheck-gIAlu-s(AppUpdater.kt:49)
12-19 16:48:01.481 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.background.AppUpdater$doUpdateCheck$1.invokeSuspend(AppUpdater.kt:0)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-19 16:48:01.481 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12-19 16:48:01.501 I/FFUpdater(25440): AppUpdater:: Start doWork for FENNEC_FDROID
12-19 16:48:01.501 I/FFUpdater(25440): AppUpdater:: Start for FENNEC_FDROID.
12-19 16:48:02.664 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest FENNEC_FDROID update.
12-19 16:48:03.635 I/FFUpdater(25440): FdroidConsumer: Found latest version 133.0.3
12-19 16:48:03.635 I/FFUpdater(25440): InstalledAppStatusFetcher: Found FENNEC_FDROID Version(versionText=133.0.3, buildDate=null) (2208ms).
12-19 16:48:03.639 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest FFUPDATER update.
12-19 16:48:03.738 I/FFUpdater(25440): InstalledAppStatusFetcher: Found FFUPDATER Version(versionText=79.3.1, buildDate=null) (98ms).
12-19 16:48:03.741 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest MULL_FROM_REPO update.
12-19 16:48:03.817 I/FFUpdater(25440): FdroidConsumer: Found latest version 133.0.3
12-19 16:48:03.817 I/FFUpdater(25440): InstalledAppStatusFetcher: Found FENNEC_FDROID Version(versionText=133.0.3, buildDate=null) (1153ms).
12-19 16:48:03.852 I/FFUpdater(25440): ApkDownloader: Delete older files from FENNEC_FDROID
12-19 16:48:04.215 I/FFUpdater(25440): AppUpdater:: Start downloading FENNEC_FDROID
12-19 16:48:04.217 I/FFUpdater(25440): AppUpdater:: Download update for FENNEC_FDROID.
12-19 16:48:04.217 I/FFUpdater(25440): AppUpdater:: Download update for FENNEC_FDROID.
12-19 16:48:04.498 I/FFUpdater(25440): InstalledAppStatusFetcher: Found MULL_FROM_REPO Version(versionText=133.0.3, buildDate=null) (757ms).
12-19 16:48:04.499 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest THORIUM update.
12-19 16:48:04.609 I/FFUpdater(25440): InstalledAppStatusFetcher: Found THORIUM Version(versionText=126.0.6478.246, buildDate=null) (110ms).
12-19 16:48:04.609 D/FFUpdater(25440): InstalledAppStatusFetcher: Search for latest TOR_BROWSER_ALPHA update.
12-19 16:48:05.593 I/FFUpdater(25440): InstalledAppStatusFetcher: Found TOR_BROWSER_ALPHA Version(versionText=14.5a1, buildDate=null) (984ms).
12-19 16:48:11.407 D/FFUpdater(25440): MainActivity: Start DownloadActivity to install or update FENNEC_FDROID.
12-19 16:48:11.514 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: start fetching, downloading and installation process
12-19 16:48:11.519 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: fetching download information for FENNEC_FDROID
12-19 16:48:11.541 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: check if an existing download can be reused
12-19 16:48:11.541 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: check if no APK file is cached
12-19 16:48:11.556 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: start download (1/2)
12-19 16:48:11.557 D/FFUpdater(25440): DownloadActivity FENNEC_FDROID: start downloading (2/2)
12-19 16:49:39.116 E/FFUpdater(25440): AppUpdater:: Failed to update app
12-19 16:49:39.116 E/FFUpdater(25440): java.lang.IllegalArgumentException: Downloaded or extracted APK file is not a valid ZIP file.
12-19 16:49:39.116 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.checkApkFile(ApkDownloader.kt:148)
12-19 16:49:39.116 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$DefaultImpls.access$checkApkFile(ApkDownloader.kt:21)
12-19 16:49:39.116 E/FFUpdater(25440): 	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkApkFile$1.invokeSuspend(ApkDownloader.kt:0)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-19 16:49:39.116 E/FFUpdater(25440): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12-19 16:49:51.213 E/FFUpdater(25440): CrashListener: Uncaught exception: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fennec_fdroid_download.download

**Comment by CaseOf** [comment]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/eu_faircode_email_download.download
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9ed9859, Dispatchers.Main.immediate]

```
Logs:
```
de.marmaro.krt.ffupdater.network.exceptions.NetworkException: File was not downloaded: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/eu_faircode_email_download.download
	at de.marmaro.krt.ffupdater.app.impl.base.ApkDownloader$checkDownloadFile$2.invokeSuspend(ApkDownloader.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9ed9859, Dispatchers.Main.immediate]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.3.1 (177) release Github |
| Device | FP3 (lineage_FP3, FP3, FP3) |
| Manufacturer | Fairphone (Fairphone) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | d900d91c1dc3, root, release-keys, 1734481110000 |
