### ISSUE TITLE
Crashes - stack trace below

### ISSUE THREAD

**Issue by diznanl** [Tobi823/ffupdater#67]
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException at MainActivity.kt:204
de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException

de.marmaro.krt.ffupdater.MainActivity$UpdateCheckException: fail to check FIREFOX_RELEASE for updates
	at de.marmaro.krt.ffupdater.MainActivity$checkForAppUpdate$1.invokeSuspend(MainActivity.kt:204)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$2$1.invokeSuspend(BaseAppDetail.kt:63)
	... 6 more

Android Version: 30
Device Manufacturer: OnePlus
Device Model: GM1917

**Comment by Tobi823** [comment]
Bug is already fixed in version 74.3.**4** - but it seems that the folks from F-Droid need more time to distribute the latest version. 

You can either wait until F-Droid distribute the latest version or you can temporarily install my self compiled APK file (see https://github.com/Tobi823/ffupdater#temporary-builds)

**Comment by Tobi823** [comment]
Fix is available on F-Droid
