### ISSUE TITLE
FFUpdater crash

### ISSUE THREAD

**Issue by sanjayen** [Tobi823/ffupdater#68]
Installed FFUpdater 74.3.2 from f-droid. I already have Firefox 90.1.3 and Bromite 92.0.4515.125 installed. FFUpdater retrieves the available version of Bromite correctly but shows an ERROR for Firefox. The notification states -

Background update check failed.
Due to an unknown bug the background check failed...

This is the stacktrace;

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$2$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Tobi823** [comment]
Bug is already fixed in version 74.3.**4** - but it seems that the folks from F-Droid need more time to distribute the latest version. 

You can either wait until F-Droid distribute the latest version or you can temporarily install my self compiled APK file (see https://github.com/Tobi823/ffupdater#temporary-builds)

**Comment by sanjayen** [comment]
@Tobi823  F-Droid finally pushed version 74.3.4 and the crash is now solved.
