### ISSUE TITLE
Crashing on download

### ISSUE THREAD

**Issue by UltraBlackLinux** [Tobi823/ffupdater#7]
I love the app, but the first time I get an update for firefox, the app is crashing xD
Every time I click the download button the app simply crashes.
Log (idk how paste files via my app oof, im sorry):
<<< log_count = 82 >>>
[05-19 17:58:01.988 939:1263 I/qti_sensors_hal]
processReportInd: 520000 82.000000

[05-19 17:58:05.315 1494:2214 V/InputDispatcher]
Asynchronous input event injection succeeded.

[05-19 17:58:05.415 1494:2214 V/InputDispatcher]
Asynchronous input event injection succeeded.

[05-19 17:58:05.428 2359:2359 V/StatusBar]
mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{bd7425f V.E...... ........ 0,0-1440,84} canPanelBeCollapsed(): false

[05-19 17:58:05.430 1494:2210 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 pkg=com.android.launcher3 cmp=com.android.launcher3/.lineage.LineageLauncher (has extras)} from uid 10102

[05-19 17:58:05.457 10379:10379 D/LogcatReader]
[Logcat] onActivityInBackground

[05-19 17:58:05.470 1494:3673 W/ActivityManager]
Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10102?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found

[05-19 17:58:05.529 2359:2359 D/ImageWallpaper]
wallpaper visibility changes to: true

[05-19 17:58:05.549 3771:3771 I/HK/LatinKbdBaseView]
closing org.pocketworkstation.pckeyboard.LatinKeyboardView{a1d7b55 V.ED..... ......ID 0,0-1440,836 #7f080004 app:id/LatinkeyboardBaseView}

[05-19 17:58:05.629 2531:2563 W/System]
A resource failed to call release. 

[05-19 17:58:05.629 2531:2563 W/System]
A resource failed to call release. 

[05-19 17:58:05.806 652:652 E/Layer]
[Surface(name=AppWindowToken{ed06d44 token=Token{7242e57 ActivityRecord{326cbd6 u0 com.dp.logcatapp/.activities.MainActivity t323}}})/@0xeeab4e7 - animation-leash#0] No local sync point found

[05-19 17:58:05.806 652:652 E/Layer]
[Surface(name=AppWindowToken{ed06d44 token=Token{7242e57 ActivityRecord{326cbd6 u0 com.dp.logcatapp/.activities.MainActivity t323}}})/@0xeeab4e7 - animation-leash#0] No local sync point found

[05-19 17:58:05.806 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:05.806 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:05.814 652:652 E/Layer]
[Surface(name=AppWindowToken{ed06d44 token=Token{7242e57 ActivityRecord{326cbd6 u0 com.dp.logcatapp/.activities.MainActivity t323}}})/@0xeeab4e7 - animation-leash#0] No local sync point found

[05-19 17:58:05.814 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:06.643 1494:3674 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=de.marmaro.krt.ffupdater/.MainActivity} from uid 10102

[05-19 17:58:06.662 1494:1545 E/system_server]
Invalid ID 0x00000000.

[05-19 17:58:06.689 914:914 D/Zygote]
Forked child process 11430

[05-19 17:58:06.692 1494:1565 I/ActivityManager]
Start proc 11430:de.marmaro.krt.ffupdater/u0a198 for activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}

[05-19 17:58:06.719 11430:11430 E/o.krt.ffupdate]
Not starting debugger since process cannot load the jdwp agent.

[05-19 17:58:06.736 11430:11430 V/Riru]
hook removed

[05-19 17:58:06.736 11430:11430 V/Riru]
edxp: forkAndSpecializePost

[05-19 17:58:06.780 913:12854 I/netd]
bandwidthAddNiceApp(10198) <4.05ms>

[05-19 17:58:07.025 11430:11430 I/MainActivity]
enable StrictMode for everyday usage to prevent unencrypted data connection

[05-19 17:58:07.050 11430:11430 W/MainActivity]
disableApps: [FIREFOX_KLAR, FENIX, FIREFOX_FOCUS, FIREFOX_LITE]

[05-19 17:58:07.050 11430:11430 W/MainActivity]
checkInterval: 360

[05-19 17:58:07.050 11430:11430 W/MainActivity]
automaticCheck: true

[05-19 17:58:07.063 11430:11457 D/NetworkSecurityConfig]
No Network Security Config specified, using platform default

[05-19 17:58:07.094 11430:11451 I/Adreno]
QUALCOMM build                   : cf6f28e, I1fbdd7a9d4
Build Date                       : 02/28/19
OpenGL ES Shader Compiler Version: EV031.25.03.02
Local Branch                     : mybranche93b5c3a-ead7-f1e6-b2ac-5cb90179c3e0
Remote Branch                    : quic/gfx-adreno.lnx.1.0.r49-rel
Remote Branch                    : NONE
Reconstruct Branch               : NOTHING

[05-19 17:58:07.094 11430:11451 I/Adreno]
Build Config                     : S L 6.0.7 AArch64

[05-19 17:58:07.099 11430:11451 I/Adreno]
PFP: 0x005ff112, ME: 0x005ff066

[05-19 17:58:07.100 2359:2359 D/ImageWallpaper]
wallpaper visibility changes to: false

[05-19 17:58:07.101 11430:11451 E/libEGL]
Driver indicates EGL 1.5 support, but does not have a critical API

[05-19 17:58:07.104 652:652 E/Layer]
[Surface(name=AppWindowToken{f552634 token=Token{6b57507 ActivityRecord{88b3f46 u0 de.marmaro.krt.ffupdater/.MainActivity t324}}})/@0x520d291 - animation-leash#0] No local sync point found

[05-19 17:58:07.104 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:07.105 913:11459 E/ResolverController]
No valid NAT64 prefix (198, <unspecified>/0)

[05-19 17:58:07.112 652:652 E/Layer]
[Surface(name=AppWindowToken{f552634 token=Token{6b57507 ActivityRecord{88b3f46 u0 de.marmaro.krt.ffupdater/.MainActivity t324}}})/@0x520d291 - animation-leash#0] No local sync point found

[05-19 17:58:07.112 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:07.132 610:610 I/hwservicemanager]
getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.

[05-19 17:58:07.132 11430:11451 W/Gralloc3]
mapper 3.x is not supported

[05-19 17:58:07.162 1494:1563 I/ActivityTaskManager]
Displayed de.marmaro.krt.ffupdater/.MainActivity: +514ms

[05-19 17:58:07.183 3771:3771 I/HK/LatinKbdBaseView]
closing org.pocketworkstation.pckeyboard.LatinKeyboardView{a1d7b55 V.ED..... ......ID 0,0-1440,836 #7f080004 app:id/LatinkeyboardBaseView}

[05-19 17:58:07.208 11430:11463 D/Notificator]
start background update check

[05-19 17:58:07.274 11430:11460 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=68e806aa-7843-4605-beef-b65258de6395, tags={ de.marmaro.krt.ffupdater.notification.Notificator } ]

[05-19 17:58:07.652 939:1263 I/qti_sensors_hal]
processReportInd: X: -0.016754 Y: 0.057465 Z: 9.849747

[05-19 17:58:08.543 1494:25379 I/ActivityTaskManager]
START u0 {cmp=de.marmaro.krt.ffupdater/.InstallActivity (has extras)} from uid 10198

[05-19 17:58:08.585 11430:11430 W/ActivityThread]
handleWindowVisibility: no activity for token android.os.BinderProxy@35977da

[05-19 17:58:08.701 11430:11430 D/AndroidRuntime]
Shutting down VM

[05-19 17:58:08.702 11430:11430 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: de.marmaro.krt.ffupdater, PID: 11430
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.InstallActivity}: java.util.IllegalFormatConversionException: a != java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.util.IllegalFormatConversionException: a != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2898)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2845)
	at java.util.Formatter.format(Formatter.java:2530)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Resources.java:485)
	at android.content.Context.getString(Context.java:655)
	at de.marmaro.krt.ffupdater.InstallActivity.y(Unknown Source:44)
	at de.marmaro.krt.ffupdater.InstallActivity.E(Unknown Source:8)
	at de.marmaro.krt.ffupdater.InstallActivity.onCreate(Unknown Source:118)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more

[05-19 17:58:08.707 1494:2210 W/ActivityTaskManager]
  Force finishing activity de.marmaro.krt.ffupdater/.InstallActivity

[05-19 17:58:08.708 1494:11470 I/DropBoxManagerService]
add tag=data_app_crash isTagEnabled=true flags=0x2

[05-19 17:58:08.728 1494:2210 W/ActivityTaskManager]
  Force finishing activity de.marmaro.krt.ffupdater/.MainActivity

[05-19 17:58:08.740 1494:1540 I/ActivityManager]
Showing crash dialog for package de.marmaro.krt.ffupdater u0

[05-19 17:58:08.841 2359:2376 I/ndroid.systemu]
NativeAlloc concurrent copying GC freed 7888(464KB) AllocSpace objects, 0(0B) LOS objects, 75% free, 9440KB/36MB, paused 62us total 102.603ms

[05-19 17:58:09.225 1494:1544 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{d9fa2fb u0 de.marmaro.krt.ffupdater/.InstallActivity t324 f}

[05-19 17:58:09.226 1494:1544 W/ActivityTaskManager]
Activity pause timeout for ActivityRecord{d9fa2fb u0 de.marmaro.krt.ffupdater/.InstallActivity t324 f}

[05-19 17:58:09.282 1494:4873 W/ActivityManager]
Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10102?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found

[05-19 17:58:09.321 2359:2359 D/ImageWallpaper]
wallpaper visibility changes to: true

[05-19 17:58:09.352 913:12854 I/netd]
bandwidthRemoveNiceApp(10198) <6.74ms>

[05-19 17:58:09.807 1494:2210 W/ActivityTaskManager]
  Force finishing activity de.marmaro.krt.ffupdater/.InstallActivity

[05-19 17:58:09.810 1494:2210 W/ActivityTaskManager]
  Force finishing activity de.marmaro.krt.ffupdater/.MainActivity

[05-19 17:58:09.814 1494:8439 D/OpenGLRenderer]
endAllActiveAnimators on 0x7931eac000 (RippleDrawable) with handle 0x79b5baa8c0

[05-19 17:58:09.861 1494:3674 E/InputDispatcher]
Window handle Window{36d1f9a u0 Application Error: de.marmaro.krt.ffupdater} has no registered input channel

[05-19 17:58:09.868 1494:2210 I/ActivityManager]
Killing 11430:de.marmaro.krt.ffupdater/u0a198 (adj 900): crash

[05-19 17:58:09.897 3771:3771 I/HK/LatinKbdBaseView]
closing org.pocketworkstation.pckeyboard.LatinKeyboardView{a1d7b55 V.ED..... ......ID 0,0-1440,836 #7f080004 app:id/LatinkeyboardBaseView}

[05-19 17:58:09.939 914:914 I/Zygote]
Process 11430 exited due to signal 9 (Killed)

[05-19 17:58:09.940 1494:1544 W/ActivityManager]
setHasOverlayUi called on unknown pid: 11430

[05-19 17:58:09.943 1494:1567 I/libprocessgroup]
Successfully killed process cgroup uid 10198 pid 11430 in 73ms

[05-19 17:58:10.316 1494:2214 V/InputDispatcher]
Asynchronous input event injection succeeded.

[05-19 17:58:10.414 1494:2214 V/InputDispatcher]
Asynchronous input event injection succeeded.

[05-19 17:58:10.422 2359:2359 V/StatusBar]
mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{bd7425f V.E...... ........ 0,0-1440,84} canPanelBeCollapsed(): false

[05-19 17:58:10.832 1494:3619 E/TaskPersister]
File error accessing recents directory (directory doesn't exist?).

[05-19 17:58:11.552 10379:10379 D/LogcatReader]
[Logcat] onActivityInForeground

[05-19 17:58:11.552 10379:10379 D/LogcatReader]
[Logcat] Posting pending logs

[05-19 17:58:11.597 10379:10379 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[05-19 17:58:11.602 1494:1563 W/system_server]
Insufficient pre-allocated space to mmap vdex.

[05-19 17:58:11.606 3771:3771 I/HK/LatinKbdBaseView]
closing org.pocketworkstation.pckeyboard.LatinKeyboardView{a1d7b55 V.ED..... ......ID 0,0-1440,836 #7f080004 app:id/LatinkeyboardBaseView}

[05-19 17:58:11.849 2359:2359 D/ImageWallpaper]
wallpaper visibility changes to: false

[05-19 17:58:11.876 652:652 E/Layer]
[Surface(name=AppWindowToken{e590b5d token=Token{f3c8134 ActivityRecord{855c07 u0 com.android.launcher3/.lineage.LineageLauncher t232}}})/@0xabcc33d - animation-leash#0] No local sync point found

[05-19 17:58:11.876 652:652 E/Layer]
[Surface(name=AppWindowToken{ed06d44 token=Token{7242e57 ActivityRecord{326cbd6 u0 com.dp.logcatapp/.activities.MainActivity t323}}})/@0xeeab4e7 - animation-leash#0] No local sync point found

Can you help me?

**Comment by Tobi823** [comment]
Are you using the app with the german translation?

In 68.2 I introduce a bug by using the wrong placeholder for a string - instead of "Download-URL von %1$s wurde abgerufen" I wrote "Download-URL von %1$a wurde abgerufen".

And the "decrypted" stacktrace seems to support my theorie:
```
Caused by: java.util.IllegalFormatConversionException: a != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2898)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2845)
at java.util.Formatter.format(Formatter.java:2530)
at java.util.Formatter.format(Formatter.java:2459)
at java.lang.String.format(String.java:2911)
at android.content.res.Resources.getString(Resources.java:485)
at android.content.Context.getString(Context.java:655)
at de.marmaro.krt.ffupdater.InstallActivity.void actionFetchSuccessful()(Unknown Source:44)
at de.marmaro.krt.ffupdater.InstallActivity.void fetchUrlForDownload()(Unknown Source:8)
at de.marmaro.krt.ffupdater.InstallActivity.onCreate(Unknown Source:118)
```
Enabling Proguard was a big mistake. It only safes ca. 400KB? and makes debugging much more difficult.

The improved version 68.3 is already pushed to the git repository but not yet available over F-Droid.

Can you verify that by installing the latest pre-release builds from https://notabug.org/Tobiwan/ffupdater/releases? Direct link: https://notabug.org/attachments/7fecdb40-4413-49fb-a128-8a43d6ca02af

**Comment by UltraBlackLinux** [comment]
Thank you - Danke!
That fixed it!

**Comment by Tobi823** [comment]
No Problem.
