### ISSUE TITLE
java.lang.NullPointerException at Moz illaCiLogConsumer.kt:28

### ISSUE THREAD

**Issue by SuperSonicHub1** [Tobi823/ffupdater#70]
version 74.3.2

## Stack Trace

java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.fetch.mozillaci.MozillaCiLogConsumer.updateCheck(MozillaCiLogConsumer.kt:28)
	at de.marmaro.krt.ffupdater.app.impl.FirefoxRelease.updateCheckWithoutCaching(FirefoxRelease.kt:39)
	at de.marmaro.krt.ffupdater.app.BaseAppDetail$updateCheck$2$1.invokeSuspend(BaseAppDetail.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Tobi823** [comment]
Bug is already fixed in version 74.3.**4** - but it seems that the folks from F-Droid need more time to distribute the latest version.

You can either wait until F-Droid distribute the latest version or you can temporarily install my self compiled APK file (see https://github.com/Tobi823/ffupdater#temporary-builds)

**Comment by SuperSonicHub1** [comment]
Cool.
