### ISSUE TITLE
FFUpdater crashed after updating Firefox to the latest version 92.1.0

### ISSUE THREAD

**Issue by sanjayen** [Tobi823/ffupdater#76]
I am using temporary build 74.3.6 (79). FFUpdater showed an update for Firefox but did not download as it mentioned that the download manager was in use. After some time, it downloaded the apk, verified the checksum and successfully installed. Immediately after installation, it crashed with the following stacktrace.

 
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.InstallActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException
at de.marmaro.krt.ffupdater.InstallActivity.onCreate(InstallActivity.kt:80)
at android.app.Activity.performCreate(Activity.java:7994)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
... 11 more

**Comment by Tobi823** [comment]
Should be fixed in version 74.4.0. This version should be available on F-Droid in the next days. My self-signed version is available on https://github.com/Tobi823/ffupdater#temporary-builds

**Comment by sanjayen** [comment]
Thank you Tobi for fixing. Will test the temporary build.

A correction - in the changelog [https://github.com/Tobi823/ffupdater/releases/tag/74.4.0], please change the bug number to #76 and not #80

Prevent simultaneous download by the background job and the user (Tobiwan/ffupdater#80)

**Comment by Tobi823** [comment]
> A correction - in the changelog [https://github.com/Tobi823/ffupdater/releases/tag/74.4.0], please change the bug number to #76 and not #80

No, that's correct. I'm referencing this issue "Downloading many copies, sometimes leading to errors" https://notabug.org/Tobiwan/ffupdater/issues/80

This bug (#76) is a different bug. I introduced it during code cleanup (I thought that one check is not necessary and can be removed :see_no_evil: )
