### ISSUE TITLE
FFUpdater crash when background update check is disabled

### ISSUE THREAD

**Issue by sanjayen** [Tobi823/ffupdater#77]
Using the latest dev build 74.4.0 (79) and installed Firefox Focus version 93.0. Probably because of bug #75 it finds a newer version 93.0.1 and downloads the same in the background. To workaround unnecessary downloads, I disabled automatic background check and FFUpdater crashed with the following stacktrace.

java.lang.IllegalArgumentException
-
Failed requirement.
-
java.lang.IllegalArgumentException: Failed requirement.
  at de.marmaro.krt.ffupdater.download.DownloadManagerUtil.getStatusAndProgress(DownloadManagerUtil.kt:48)
  at de.marmaro.krt.ffupdater.background.BackgroundJob.downloadUpdateInBackground(BackgroundJob.kt:140)
  at de.marmaro.krt.ffupdater.background.BackgroundJob.access$downloadUpdateInBackground(BackgroundJob.kt:30)
  at de.marmaro.krt.ffupdater.background.BackgroundJob$downloadUpdateInBackground$1.invokeSuspend(Unknown Source:15)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by sanjayen** [comment]
Got the same problem today as I could reproduce this. If I cancel the background download from the notifications, FFUpdater crashes with this stacktrace.

**Comment by Tobi823** [comment]
Problem should be fixed now

**Comment by Tobi823** [comment]
* The crashing should be fixed now.
You could also leave the background check enabled and disable the check for Firefox Focus/Klar in Settings > Excluded applications

**Comment by Tobi823** [comment]
https://github.com/Tobi823/ffupdater/files/7123448/ffupdater-release.zip

**Comment by sanjayen** [comment]
@Tobi823 When Focus was at 92.1.1 - the same version as the regular Firefox browser (both downloaded using FFUpdater), the background check worked great.

From today morning or so, Focus finds a 93.0.2 version and keeps on downloading the same in the background. I tried installing it twice or thrice but the version number does not change and hence the download keeps on happening.

This I understand from a previous bug is a problem with how Focus is published.

Though the cancel download from the Notification isnt crashing FFUpdater anymore.

**Comment by Tobi823** [comment]
I think that this bug is fixed. If not, create a new one or reopen it.
