### ISSUE TITLE
Crash on enter (Critical bug)

### ISSUE THREAD

**Issue by Nickoriginal** [Tobi823/ffupdater#80]
The app just crashes on launch with no reason. Fresh install, FFUpdater 74.4.1, Samsung Galaxy A20s (ARM64), Android 11. Previous version 74.4.0 worked excellent. Installed from this APK here https://github.com/Tobi823/ffupdater/releases/download/74.4.1/ffupdater-release.apk. <s>No way to enter app.</s>

java.lang.RuntimeException
-
Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
-
java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4881)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4918)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isDnsResolvable(NetworkUtil.kt:54)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:32)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:18)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetUnavailable(NetworkUtil.kt:22)
	at de.marmaro.krt.ffupdater.MainActivity.checkForUpdates(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:94)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8353)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4871)
	... 12 more

**Comment by Nickoriginal** [comment]
Update: I can enter the app, but only when internet is disabled. It crashes on update checking: I have Firefox 92.1.1 and Brave 1.30.84 installed and it installs previous Brave 1.29.81 despite I disabled automatic background update check.

**Comment by Tobi823** [comment]
I fixed the bug and I will release the fix tomorrow.

**Comment by Tobi823** [comment]
As a quick fix, you can use this working (but not perfect) version:

[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/7238379/ffupdater-release.zip)


But you have to uninstall FFUpdater from F-Droid first, because this version is signed by my own key (see https://github.com/Tobi823/ffupdater#temporary-builds).

**Comment by Nickoriginal** [comment]
Thank you! If you are already familiar with problem and have prepared a fix, I will close this issue.

**Comment by Tobi823** [comment]
The real problem:

I want to check if device is connected to the internet. I already used getNetworkCapabilities + hasCapability but this don't work when using a VPN.

That's why I also checking if the IP address of api.github.com can be resolved with `InetAddress.getByName(url).hostAddress.isNotEmpty()`

But this triggered this NetworkOnMainThreadException.

But I don't noticed it because this exception was only thrown in the release (and not debug) version because I use different StrictPolicy configurations :(

Solution: 
- internet check withing `withContext(Dispatchers.IO) { .... }`
- using annotation @MainThread, @WorkerThread etc. to get warnings when I try to do network stuff on the main thread

**Comment by Nickoriginal** [comment]
> As a quick fix, you can use this working (but not perfect) version:

Thanks! I will prefer to wait for a public version with included fix.

> But you have to uninstall FFUpdater from F-Droid first, because this version is signed by my own key

I did it already, when uninstalled F-droid version, installed this APK and after stucking on bug rolled myself back to the previous F-droid version by uninstalling APK release.

**Comment by Nickoriginal** [comment]
https://github.com/Tobi823/ffupdater/issues/81
