### ISSUE TITLE
Issue - an error always occure when opening and uninstalling then reinstalling didnt worked

### ISSUE THREAD

**Issue by Kaki-In** [Tobi823/ffupdater#83]
Here is the traceback : 
java.lang.RuntimeException
-
Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
-
java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1588)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isDnsResolvable(NetworkUtil.kt:54)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:32)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:18)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetUnavailable(NetworkUtil.kt:22)
	at de.marmaro.krt.ffupdater.MainActivity.checkForUpdates(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:94)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8129)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
	... 12 more

**Comment by Tobi823** [comment]
Should already been fixed in version 74.4.3 - F-Droid is currently distributing the update

**Comment by Kaki-In** [comment]
I saw, thanks a lot

2 oct. 2021 01:53:08 Tobias Hellmann ***@***.***>:
