### ISSUE TITLE
Error opening app after last upgrade

### ISSUE THREAD

**Issue by orencio** [Tobi823/ffupdater#84]
Versión 74.4.1 (from fdroid).
Android 10.

Error isla produces alway I open the  app.

This is the error:

```
java.lang.RuntimeException
-
Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
-
java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isDnsResolvable(NetworkUtil.kt:54)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:32)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:18)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetUnavailable(NetworkUtil.kt:22)
	at de.marmaro.krt.ffupdater.MainActivity.checkForUpdates(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:94)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7958)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```

**Comment by Tobi823** [comment]
Should already been fixed in version 74.4.3 - F-Droid is currently distributing the update. You may have to manual search for updates in F-Droid.
