### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Diridibindy** [Tobi823/ffupdater#85]
java.lang.IllegalArgumentException
-
Failed requirement.
-
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.download.DownloadManagerUtil.getStatusAndProgress(DownloadManagerUtil.kt:48)
	at de.marmaro.krt.ffupdater.InstallActivity$State$7.invokeSuspend(InstallActivity.kt:245)
	at de.marmaro.krt.ffupdater.InstallActivity$State$7.invoke(Unknown Source:8)
	at de.marmaro.krt.ffupdater.InstallActivity$State$7.invoke(Unknown Source:4)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

It happened after I started a download, launched the app in splits screen which paused the download, then I did it again and then for the third time I let it download the firefox nightly update while the app was in split screen mode (there were 3 of them showing in the download manager). Once the download finished I maximized the app by dragging the split screen bar down, after that the app crashed.

**Comment by Diridibindy** [comment]
Nevermind, I'm using an old version and this has probably been fixed. If it has, then feel free to close the issue.

**Comment by Tobi823** [comment]
I wanted to ask you which version you use :smile: 

That should be an old error, which I have already fixed.
