### ISSUE TITLE
App crashes when no network available

### ISSUE THREAD

**Issue by gerryfrancis** [Tobi823/ffupdater#93]
Using version 74.5.2 from F-Droid, I temporarily had no network when I opened FFUpdater. This info showed up while looking for an update of Firefox Browser. When I tapped on the error message, the app crashed:

Stacktrace:

```
de.marmaro.krt.ffupdater.app.impl.exceptions.NetworkException: Fail to consume kotlin.String from 'https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.armeabi-v7a/artifacts/public/logs/chain_of_trust.log'.
  at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:61)
  at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.access$readNetworkResource(ApiConsumer.kt:23)
  at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer$consumeNetworkResource$2.invokeSuspend(ApiConsumer.kt:38)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@9dea8ba9
  at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
  at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
  at java.net.URLConnection.getContentEncoding(URLConnection.java:551)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
  at de.marmaro.krt.ffupdater.app.impl.fetch.ApiConsumer.readNetworkResource(ApiConsumer.kt:49)
  ... 8 more
Caused by: java.io.EOFException: \n not found: size=0 content=...
  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
  at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
  ... 19 more
```
Device information:
| key | value |
| --- | --- |
| version name | 74.5.2 |
| version code | 89 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | FP2 |
| brand | Fairphone |
| device | FP2 |
| manufacturer | Fairphone |
| model | FP2 |
| product | FP2 |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1636082855000 | 
```

**Comment by Tobi823** [comment]
Did I understand you correctly that instead of the available version the underlined text "Temporary network issue. Retry later." was displayed? And you click on this underlined text?

![Screenshot](https://user-images.githubusercontent.com/10066140/141464264-59a4bd6c-e2be-4f60-a740-795c6e4dfd2a.png)

# If so:

It's not a crash. The error already occured and FFUpdater thinks, that the error is caused a temporary lost of internet connection. 
If you click on the underlined text, FFUpdater shows this error (because maybe this error occurs very often and is not caused by a lost of internet).
Maybe I should change the text in the error message to make it clear, that this is not a crash.

# If not:
What have I misunderstood?

**Comment by gerryfrancis** [comment]
@Tobi823 Thank you for your prompt reply. I am a little confused, because I got the FFUpdater Crash Reporter like yours above, but you mean that it is no crash? I would say, yes, it is this scenario.
