### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BlueManedHawk** [Tobi823/ffupdater#96]
The app told me to make a report here.  I was just trying to upgrade to the latest version of Firefox Normal.  Here's the report:

Stacktrace:
```
de.marmaro.krt.ffupdater.installer.SessionInstaller$SessionInstallerException: Fail to install app.
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.install(SessionInstaller.kt:57)
	at de.marmaro.krt.ffupdater.InstallActivity$Companion.triggerInstallationProcess(InstallActivity.kt:406)
	at de.marmaro.krt.ffupdater.InstallActivity$State._init_$triggerInstallationProcess(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$State.access$_init_$triggerInstallationProcess(InstallActivity.kt:195)
	at de.marmaro.krt.ffupdater.InstallActivity$State$11.invoke(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$State$11.invoke(InstallActivity.kt:207)
	at de.marmaro.krt.ffupdater.InstallActivity$restartStateMachine$1.invokeSuspend(InstallActivity.kt:169)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6640)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
Caused by: java.io.IOException: Failed to allocate 70970285 because only 0 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:80)
	at android.os.Parcel.readParcelable(Parcel.java:2860)
	at android.os.Parcel.readException(Parcel.java:2008)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:232)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:806)
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.installInternal(SessionInstaller.kt:91)
	at de.marmaro.krt.ffupdater.installer.SessionInstaller.install(SessionInstaller.kt:55)
	... 15 more
```
Device information:
| key | value |
| --- | --- |
| version name | 74.5.2 |
| version code | 89 |
| build type | release |
| SDK version | 27 |
| android release | 8.1.0 |
| board | A502DL |
| brand | TCL |
| device | U50A_PLUS_TF |
| manufacturer | TCL |
| model | A502DL |
| product | A502DL |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1601063896000 |

**Comment by Tobi823** [comment]
Looks similar to https://notabug.org/Tobiwan/ffupdater/issues/94

**Comment by Tobi823** [comment]
I found the bug. If your phone has no or every little storage available, the installation procedure crashed before it can report, that not enough storage is available.

**Comment by Tobi823** [comment]
Version 75.0.0 with a fix for this issue is now released.
